/* Watt Admin shares authentication and assets with Watt; it never owns Work truth. */
(() => {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s);
  const content = $('#admin-content');
  let overview = null;
  let currentRun = new URLSearchParams(location.search).get('run');
  const esc = value => String(value ?? '').replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  const labels = {PAUSE_REQUESTED:'等待安全暂停',PAUSED:'已暂停',STOPPING:'等待安全停止',STOPPED:'已停止',NOT_RUN:'未执行',PASS:'通过',FAIL:'失败',BLOCKED:'受阻',QUEUED:'等待执行',RUNNING:'进行中',READY:'可接任务',BUSY:'执行中',OFFLINE:'离线',DRAINING:'排空中',UNKNOWN:'未知',NOT_CONFIGURED:'未配置健康探测',UNAVAILABLE:'不可观测',CURRENT:'当前观测',STALE:'观测过期',NOT_SAMPLED:'尚未采样',OPEN:'待处理',CLOSED:'已关闭',MISSING:'缺少服务',INTERRUPTED:'已中断',COMPLETED:'完成',WAITING_RESOURCE:'等待容量',WAITING_HUMAN:'等待人工决定',EXECUTING:'执行中',GOLDEN:'重要场景',REGRESSION:'历史回归',FRESH_HOLDOUT:'未见场景',PREFERENCE:'偏好实验',ACTIVE:'使用中',healthy:'健康',running:'运行中',exited:'已退出',unhealthy:'异常',starting:'启动中'};
  function status(value) { const kind = ['FAIL','OFFLINE','MISSING','unhealthy','exited'].includes(value) ? 'bad' : ['BLOCKED','QUEUED','STALE','WAITING_RESOURCE','WAITING_HUMAN','starting'].includes(value) ? 'waiting' : ['UNKNOWN','UNAVAILABLE','NOT_SAMPLED','NOT_CONFIGURED'].includes(value) ? 'unknown' : 'good';return `<span class="admin-status" data-kind="${kind}">${esc(labels[value] || value || '未报告')}</span>`; }
  const bytes = n => typeof n !== 'number' ? '未观测' : n >= 1073741824 ? `${(n / 1073741824).toFixed(2)} GiB` : `${(n / 1048576).toFixed(1)} MiB`;
  const date = value => value ? new Date(value).toLocaleString('zh-CN') : '未记录';
  const evidence = value => `<details class="admin-evidence"><summary>查看证据与血缘</summary><pre>${esc(JSON.stringify(value, null, 2))}</pre></details>`;
  const heading = (title, subtitle) => `<header class="admin-heading"><p class="eyebrow">Watt Admin</p><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></header>`;
  function table(headers, rows, empty = '暂时没有记录。') { return rows.length ? `<div class="admin-table-wrap"><table class="admin-table"><thead><tr>${headers.map(x => `<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(x => `<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>` : `<p class="admin-empty">${esc(empty)}</p>`; }
  function notice(text) { const node = $('#admin-notice');node.textContent = text;node.hidden = false;setTimeout(() => {node.hidden = true;}, 7000); }
  async function api(path, options = {}) { const response = await fetch(path, {credentials:'same-origin', headers:{'Content-Type':'application/json'}, ...options, ...(options.body ? {body:JSON.stringify(options.body)} : {})});let data;try {data = await response.json();} catch (_) {data = {}; }if (!response.ok) {const error = new Error(data.message || data.code || '请求未完成');error.status = response.status;error.code = data.code;throw error;}return data; }
  function route() { return location.pathname.split('/')[2] || 'overview'; }
  function navigate(section) {history.pushState({}, '', section === 'overview' ? '/admin' : `/admin/${section}`);currentRun = null;render();}
  function login() { content.innerHTML = heading('登录 Watt Admin', '使用现有 Watt 拥有者凭证。质量证据和运行数据仅对已登录的拥有者开放。') + `<form class="admin-form" data-admin-login><label>登录凭证<input type="password" name="token" required autocomplete="current-password"></label><button class="button" type="submit">登录</button></form>`; }
  function cards(items) {return `<div class="admin-cards">${items.map(([title,value,detail]) => `<section class="admin-card"><h2>${esc(title)}</h2><strong>${value}</strong><p>${esc(detail || '')}</p></section>`).join('')}</div>`;}
  function overviewPage() {
    const q = overview.quality, p = overview.operations.production, node = overview.operations.node;
    const last = q.runs[0];
    const alerts = [];
    const openClusters = q.clusters.filter(c => c.closure_state !== 'CLOSED');
    if (openClusters.length) alerts.push(`<div class="admin-alert" data-kind="bad">${openClusters.length} 个失败分组仍需审查。可在质量资格中查看最早观测偏离和回归状态。</div>`);
    if (p.queue_depth && !p.available_slots) alerts.push('<div class="admin-alert">生产队列正在等待容量。Worker 状态与执行位置来自运行时；管理面不会擅自提高并发。</div>');
    if (overview.operations.state !== 'CURRENT') alerts.push('<div class="admin-alert">主机观测尚不可用或已经过期；不能以缺失数据判断资源健康。</div>');
    if (node?.disk && node.disk.free_bytes / node.disk.total_bytes < .15) alerts.push('<div class="admin-alert" data-kind="bad">数据盘可用空间低于 15%，需要审查存储增长。此页面不自动删除工程证据。</div>');
    const abnormal = overview.operations.services.filter(s => s.state !== 'running' || s.health === 'unhealthy');
    if (overview.operations.service_observation_state === 'UNAVAILABLE' || abnormal.length) alerts.push(`<div class="admin-alert" data-kind="bad">服务观测异常：${abnormal.map(s => esc(s.service)).join('、') || 'Docker 状态不可读取'}。请查看基础设施证据。</div>`);
    const holdoutCampaignIds = q.campaigns.filter(c => c.key.startsWith('fresh-holdout-')).map(c => c.id);
    const holdoutRun = q.runs.find(r => holdoutCampaignIds.includes(r.campaign_id));
    const holdout = q.cases.filter(c => c.cohorts.includes('FRESH_HOLDOUT'));
    content.innerHTML = heading('当前系统总览', '先看需要处理的异常，再看质量、保证、生产与资源。观测不是生产授权。') + alerts.join('') + cards([
      ['最近资格运行',last ? status(last.state) : '尚未运行','可重复运行的版本化 Campaign'],['生产执行',String(p.active_executions),`${p.queue_depth} 条队列记录 · ${p.available_slots} 个可用名额`],['未见场景',holdoutRun ? status(holdoutRun.state) : String(holdout.length),holdout.length ? '答案与场景材料封存，不进入优化反馈' : '尚无已登记的未见场景，晋升门禁保持关闭'],['CPU',typeof node?.cpu_percent === 'number' ? `${node.cpu_percent}%` : '未观测','主机连续采样'],['内存',node?.memory ? bytes(node.memory.used_bytes) : '未观测','主机已使用内存'],['数据盘',node?.disk ? bytes(node.disk.free_bytes) : '未观测','剩余空间'],['服务',overview.operations.services.length ? `${overview.operations.services.filter(s => s.state === 'running').length} 个运行中` : '不可观测','进程状态与健康探测分开报告']]) + `<section class="admin-panel"><h2>最近资格记录</h2>${runsTable(q.runs.slice(0,5))}</section><section class="admin-panel"><h2>当前保证门禁</h2>${assuranceTable(overview.assurance.results.slice(0,4))}</section>`;
  }
  function runsTable(runs) {return table(['时间','状态','Watt 版本','查看'],runs.map(r => [esc(date(r.created_at)),status(r.state),`<code>${esc(r.watt_revision?.slice(0,12))}</code>`,`<button class="button secondary" data-run="${esc(r.id)}">查看本次结果</button>`]));}
  function assuranceTable(results) {return table(['结果','候选成果','精确源码','时间'],results.map(r => [status(r.gate),`<code>${esc(r.candidate_id?.slice(0,12))}</code>`,`<code>${esc(r.source_revision?.slice(0,12))}</code>${evidence(r)}`,esc(date(r.assessed_at))]),'尚无可读取的 Guardian 结果。');}
  function qualityPage() {
    const q = overview.quality;
    content.innerHTML = heading('质量资格', '重要场景、历史回归和未见场景共用同一个 Case 身份。运行记录绑定精确 Watt 版本，历史结果不会改写。') + `<div class="admin-actions"><button class="button secondary" data-register-pilot>登记 10 场景 Pilot</button><button class="button secondary" data-import-core>登记标准资格集合</button><button class="button secondary" data-generate-holdout>生成封存未见场景</button><select id="campaign-select" aria-label="选择资格集合">${q.campaigns.map(c => `<option value="${esc(c.id)}">${esc(c.name)} · v${c.version}</option>`).join('')}</select><button class="button" data-start-campaign ${q.campaigns.length ? '' : 'disabled'}>运行资格验证</button></div><section class="admin-panel"><h2>资格运行</h2>${runsTable(q.runs)}</section><section class="admin-panel"><h2>场景资产</h2>${table(['场景','用途','来源与版本','身份'],q.cases.map(c => [esc(c.definition.title),c.cohorts.map(status).join(' '),`${esc(c.definition.source)} · v${c.current_version}${c.definition.sealed ? '<small>材料已封存</small>' : ''}`,`<code>${esc(c.key)}</code><button class="button secondary" data-case-history="${esc(c.id)}">资格历史</button>`]))}</section><section class="admin-panel"><h2>失败分组</h2>${table(['偏离位置','类型','出现次数','回归状态','当前状态','证据'],q.clusters.map(c => [esc(c.stage || '归因不确定'),esc(c.finding_code),`${c.occurrence_count}<small>${esc(date(c.first_seen))} → ${esc(date(c.last_seen))}</small>`,esc(c.regression_status === 'PERMANENT_CASE' ? '已纳入永久回归' : '尚未纳入'),status(c.closure_state),`${evidence(c)}${c.regression_status === 'NOT_PROMOTED' ? `<button class="button secondary" data-regression="${esc(c.findings[0])}">纳入永久回归</button>` : ''}`]))}</section>`;
  }
  async function showRun(id) {
    const r = await api(`/api/admin/runs/${encodeURIComponent(id)}`);currentRun = id;
    if (new URLSearchParams(location.search).get('run') !== id) history.pushState({}, '', `/admin/quality?run=${encodeURIComponent(id)}`);
    const evaluator = {DETERMINISTIC:'确定性判据',RUNTIME:'运行事实',GUARDIAN:'Guardian 判断',LLM:'模型评估',HUMAN:'人工评价'};
    const active = ['QUEUED','RUNNING','PAUSE_REQUESTED','PAUSED'].includes(r.state);
    const terminal = ['PASS','FAIL','BLOCKED','STOPPED'].includes(r.state);
    const controls = `<div class="admin-actions" data-run-controls><button class="button secondary" data-back-quality>返回资格集合</button>${status(r.lifecycle || r.state)} ${terminal && r.state !== 'STOPPED' ? status(r.state) : ''}<button class="button secondary" data-run="${esc(id)}">刷新本次结果</button>
      <button class="button secondary" data-control="PAUSE" ${['QUEUED','RUNNING'].includes(r.state) ? '' : 'disabled'}>暂停</button>
      <button class="button" data-control="RESUME" ${r.state === 'PAUSED' ? '' : 'disabled'}>继续本次运行</button>
      <button class="button secondary" data-control="STOP" ${active ? '' : 'disabled'}>停止本次运行</button>
      <button class="button secondary" data-rerun="FAILED" ${terminal ? '' : 'disabled'}>重跑失败场景</button>
      <button class="button secondary" data-rerun="SELECTED" ${terminal ? '' : 'disabled'}>重跑所选场景</button>
      <button class="button secondary" data-rerun="ALL" ${terminal ? '' : 'disabled'}>重跑全部场景</button></div>`;
    const p = r.progress || {};
    const countCards = cards([['场景总数',p.total ?? r.cases.length,'冻结的 Case 版本'],['排队',p.QUEUED ?? 0,'尚未执行'],['运行',p.RUNNING ?? 0,r.current_case?.title || '无在途场景'],['完成',p.completed ?? 0,`${Math.round(r.elapsed_seconds || 0)} 秒经过时间`],...['PASS','FAIL','BLOCKED','UNKNOWN','NOT_RUN'].map(k => [labels[k],p[k] ?? 0,k])]);
    const systemStop = [...(r.controls || [])].reverse().find(e => e.action === 'SYSTEM_STOP_THE_LINE');
    content.innerHTML = heading('本次资格结果', `Run ${id} · Watt ${r.watt_revision} · ${date(r.created_at)}`) + controls + `<p class="admin-muted">暂停和停止均等待当前场景的安全边界；已完成证据永久保留。继续沿用同一 Run；重跑建立新 Run。</p>` +
      (systemStop ? `<section class="admin-alert" data-stop-the-line><strong>系统暂停依据</strong><p>最近 5 个场景中至少 4 个违反同一已观测判据，需要明确继续或停止。</p>${evidence(systemStop)}</section>` : '') + countCards +
      `<section class="admin-panel"><h2>资格摘要</h2><p>历史回归复发：${r.regression_recurrences || 0} · 新失败分组：${r.new_failure_clusters || 0}</p>${evidence({earliest_divergence_distribution:r.earliest_divergence_distribution,fresh_holdout:r.fresh_holdout,parent_run:r.parent_run_id,policy_fingerprint:r.policy_fingerprint,configuration:r.configuration})}</section>` +
      (r.members || []).map(m => {const c = m.attempt;return `<section class="admin-panel" data-case-version="${esc(m.case_version_id)}"><h2><label><input type="checkbox" data-rerun-selection value="${esc(m.case_version_id)}">${esc(m.title)}</label> ${status(m.state)}</h2>
        <p class="admin-muted">Case v${m.version} · ${m.cohorts.map(esc).join(' / ')} · ${c?.elapsed_seconds == null ? (m.state === 'RUNNING' ? '执行尚未结束' : '尚无完成证据') : `${Number(c.elapsed_seconds).toFixed(1)} 秒`} · 最早观测偏离：${esc(c?.lineage.divergence?.stage || (m.state === 'PASS' ? '未观测到失败' : 'UNKNOWN'))}</p>
        ${m.definition.sealed ? '<p>未见场景答案已封存，不进入优化与模型评价。</p>' : `<p>${esc(m.definition.motive)}</p>${evidence({input:m.definition.context,obligations:m.definition.invariants,version_fingerprint:m.fingerprint})}`}
        ${c ? table(['评估维度','结果','证据'],c.evaluations.map(e => [esc(evaluator[e.evaluator] || e.evaluator),status(e.outcome),evidence(e)])) + evidence(c.lineage) : ''}
        ${evidence({findings:m.findings,attribution:m.attribution,source_case_run_id:m.source_case_run_id,owner_references:m.owner_references})}
        ${m.state === 'QUEUED' && active ? `<button class="button secondary" data-skip-case="${esc(m.case_version_id)}">跳过排队场景</button>` : ''}
        ${terminal && ['FAIL','BLOCKED','UNKNOWN'].includes(m.state) ? `<button class="button secondary" data-rerun-case="${esc(m.case_version_id)}">重跑此失败场景</button>` : ''}
        ${c && !c.lineage.sealed && ['PASS','FAIL','BLOCKED'].includes(m.state) ? `<button class="button secondary" data-llm-evaluation="${esc(c.id)}">添加独立模型意见</button>` : ''}</section>`;}).join('') +
      `<section class="admin-panel"><h2>运行与资源关联</h2><a href="/admin/infrastructure">查看基础设施观测</a> · <a href="/admin/operations">查看生产容量</a>${evidence({operations_samples:r.operations_samples,control_history:r.controls})}</section>`;
  }

  function assurancePage() { const a = overview.assurance;content.innerHTML = heading('保证与门禁', '直接展示 Guardian 的精确结果。Quality 通过独立确定性判据评价保证能力；Guardian 不充当自己的唯一判据。') + `<p class="admin-muted">Owner 模式：${esc(a.mode)} · 结果存储：${a.store_observed ? '可读取' : '不可读取'}</p><section class="admin-panel">${assuranceTable(a.results)}</section><section class="admin-panel"><h2>独立质量评价</h2>${table(['结果','独立判据与覆盖证据'],(a.quality_evaluations || []).map(e => [status(e.outcome),evidence(e.record)]))}</section>`; }
  function operationsPage() { const p = overview.operations.production;content.innerHTML = heading('生产运行状态', 'Worker、队列与容量直接来自现有运行时。就绪与实际运行保持区分，管理面不调高生产并发。') + cards([['正在执行',String(p.active_executions),'来自有效 allocation'],['当前队列',String(p.queue_depth),'展示最早的 100 条记录'],['可用名额',String(p.available_slots),'扣除有效占用并检查心跳'],['Worker',String(p.workers.length),'已登记执行资源']]) + `<section class="admin-panel"><h2>执行资源</h2>${table(['Worker','状态','容量','当前执行','可用','最后心跳'],p.workers.map(w => [esc(w.name || w.worker_id),status(w.status),esc(w.capacity.max_concurrency),esc(w.active_execution_count),esc(w.available_slots),esc(date(w.last_heartbeat_at || w.heartbeat_at))]))}</section><section class="admin-panel"><h2>等待与执行队列</h2>${table(['Execution','状态','等待原因','入队时间','经过时间'],p.queue.map(q => [`<code>${esc(q.attempt_id.slice(0,12))}</code>`,status(q.condition),esc(q.wait_reason || '运行时未报告等待原因'),esc(date(q.enqueued_at)),`${Math.floor(q.elapsed_seconds / 60)} 分钟`]))}</section>`; }
  function trend(samples, getter, label) {const values = samples.map(getter).filter(v => typeof v === 'number');if (values.length < 2) return `<p class="admin-muted">${esc(label)}：需要至少两次有效采样。</p>`;const min = Math.min(...values),max = Math.max(...values);const points = values.map((v,i) => `${10+i*980/(values.length-1)},${95-(v-min)*80/Math.max(max-min,1)}`).join(' ');return `<figure><figcaption class="admin-muted">${esc(label)} · ${values.length} 次有效采样</figcaption><svg class="admin-trend" viewBox="0 0 1000 110" role="img" aria-label="${esc(label)}短期趋势"><polyline points="${points}"></polyline></svg></figure>`;}
  async function infrastructurePage() {const o = overview.operations,n = o.node;const history = await api('/api/admin/operations/history');content.innerHTML = heading('基础设施', '当前节点资源与服务位置来自真实观测。测量不可用时明确显示未知；存储口径不同，不相加伪造总量。') + `<p class="admin-muted">观测：${status(o.state)} · ${esc(date(n?.observed_at))}</p>` + cards([['CPU',typeof n?.cpu_percent === 'number' ? `${n.cpu_percent}%` : '未观测',n?.cpu_count ? `${n.cpu_count} 个 CPU` : '需要连续采样'],['内存',n?.memory ? bytes(n.memory.used_bytes) : '未观测',n?.memory ? `总量 ${bytes(n.memory.total_bytes)}` : '主机数据不可用'],['数据盘',n?.disk ? bytes(n.disk.used_bytes) : '未观测',n?.disk ? `总量 ${bytes(n.disk.total_bytes)}` : '尚未取得 /data 观测'],['运行时间',n?.uptime_seconds ? `${Math.floor(n.uptime_seconds / 3600)} 小时` : '未观测',n?.hostname || '主机名未绑定']]) + `<section class="admin-panel"><h2>节点与服务位置</h2>${o.topology.nodes.map(node => `<div class="admin-node"><strong>${esc(node.id)}</strong><p class="admin-muted">${esc(node.hostname || '未观测主机名')} · ${esc(node.region || 'Region 未绑定')}</p><div class="admin-placement">${o.topology.service_placements.filter(s => s.node_id === node.id).map(s => `<span>${esc(s.service)} ${status(s.health === 'NOT_CONFIGURED' ? s.state : s.health)}</span>`).join('')}</div></div>`).join('') || '<p class="admin-empty">尚未取得节点观测。</p>'}<p class="admin-muted">当前只确认此 Docker 项目的服务位置，未声明跨主机执行能力。</p></section><section class="admin-panel"><h2>服务健康</h2>${table(['服务','进程','健康探测','启动时间'],o.services.map(s => [esc(s.service),status(s.state),status(s.health),esc(date(s.started_at))]))}</section><section class="admin-panel"><h2>存储观测</h2>${table(['类别','占用','测量口径'],Object.entries(o.storage).filter(([k]) => !['docker','note'].includes(k)).map(([k,v]) => [esc({postgresql:'PostgreSQL',watt_data:'Watt 数据',workspaces:'隔离工作区',execution_data:'执行运行数据',logs:'日志',gitea:'Gitea'}[k] || k),bytes(v.bytes),`${esc(v.method)}${v.state && v.state !== 'OBSERVED' ? '<small>不可完整测量</small>' : ''}`]))}${table(['Docker 类别','总量','可回收'],o.storage.docker.categories.map(d => [esc(d.Type),esc(d.Size),esc(d.Reclaimable)]))}<p class="admin-muted">${esc(o.storage.note)}</p></section><section class="admin-panel"><h2>网络观测</h2>${table(['网卡','接收累计','发送累计','速率'],Object.entries(n?.network || {}).filter(([name]) => name !== 'lo').map(([name,v]) => [esc(name),bytes(v.rx_bytes),bytes(v.tx_bytes),v.rx_bytes_per_second == null ? '需连续采样' : `↓ ${bytes(v.rx_bytes_per_second)}/s · ↑ ${bytes(v.tx_bytes_per_second)}/s`]))}<p class="admin-muted">网卡单独显示，避免将物理口与虚拟桥流量重复相加。</p></section><section class="admin-panel"><h2>短期趋势</h2>${trend(history,s => s.cpu_percent,'CPU')}${trend(history,s => s.memory?.used_bytes,'内存占用')}${trend(history,s => s.disk?.used_bytes,'数据盘占用')}${trend(history,s => s.queue_depth,'队列深度')}${trend(history,s => s.active_executions,'活动执行')}</section>`;}
  async function arenaPage() {const arena = await api('/api/admin/arena');const cases = overview.quality.cases.filter(c => !c.cohorts.includes('FRESH_HOLDOUT'));content.innerHTML = heading('偏好与受控实验', '先固定 Case 和差异变量，再比较有精确执行证据的结果。偏好形成学习信号，不能覆盖确定性失败或直接改生产行为。') + `<section class="admin-panel"><h2>建立策略比较</h2><p class="admin-muted">v1 可比较固定资格配方在不同执行时限策略下的结果与成本。未资格化的模型、提示或规划路由不会仅因改了元数据而被报告为生效。</p><form class="admin-form" data-experiment-form><label>场景<select name="case_id" required>${cases.map(c => `<option value="${esc(c.id)}">${esc(c.definition.title)}</option>`).join('')}</select></label><label>实验名称<input name="name" required value="资格执行时限比较"></label><div class="two"><label>当前策略时限（秒）<input name="baseline" type="number" min="30" max="900" value="600" required></label><label>候选策略时限（秒）<input name="alternative" type="number" min="30" max="900" value="300" required></label></div><label>为什么比较<textarea name="rationale" required placeholder="例如：观察更紧的时限是否仍能完成完整验证，并控制资源成本。"></textarea></label><button class="button" type="submit">建立版本化实验</button></form></section>` + arena.experiments.map(e => `<section class="admin-panel"><h2>${esc(e.definition.name)} · v${e.version}</h2><p class="admin-muted">差异变量：${e.definition.changed_variables.map(esc).join('、')}</p>${table(['策略','明确差异','运行'],e.definition.variants.map(v => [esc(v.label),`${v.policy.case_timeout_seconds} 秒`,`<button class="button secondary" data-variant-run="${esc(e.id)}" data-variant="${esc(v.key)}">运行此策略</button>`]))}<div class="admin-actions"><button class="button secondary" data-preference="${esc(e.id)}">比较已有结果并记录偏好</button><button class="button secondary" data-promotion="${esc(e.id)}">检查候选策略晋升门禁</button></div>${evidence({fingerprint:e.fingerprint,definition:e.definition})}</section>`).join('') + `<section class="admin-panel"><h2>人工偏好记录</h2>${table(['时间','选择','理由','归因'],arena.preferences.map(p => [esc(date(p.created_at)),esc(p.record.winner),esc(p.record.rationale),`<button class="button secondary" data-attribute="${esc(p.id)}">形成学习信号</button>${evidence(p.record.candidate_provenance)}`]))}</section><section class="admin-panel"><h2>Owner 学习信号</h2>${table(['Owner','来源','置信度','边界'],arena.learning_signals.map(s => [esc(s.owner),esc(s.source_kind),`${Math.round(s.record.confidence*100)}%`,'优化证据；未改变生产策略']))}</section><section class="admin-panel"><h2>晋升决定</h2>${table(['时间','候选策略','决定'],arena.promotion_decisions.map(p => [esc(date(p.created_at)),esc(p.variant_key),'已批准进入受治理变更；未直接修改生产']))}</section>`;}
  async function render() {try {await api('/auth/session');overview = await api('/api/admin/overview');document.querySelectorAll('[data-admin-route]').forEach(a => {if (a.dataset.adminRoute === route()) a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if (currentRun) return showRun(currentRun);switch (route()) {case 'quality':qualityPage();break;case 'arena':await arenaPage();break;case 'assurance':assurancePage();break;case 'operations':operationsPage();break;case 'infrastructure':await infrastructurePage();break;default:overviewPage();}} catch (e) {if (e.status === 401) login();else content.innerHTML = heading('当前状态不可用', '无法取得完整 owner 数据，未将缺失数据视为健康。') + `<p class="admin-alert">${esc(e.message)}</p>`;}}
  document.addEventListener('click',async event => {const node = event.target.closest('button,a');if (!node) return;try {
    if (node.matches('[data-admin-route]')) {event.preventDefault();navigate(node.dataset.adminRoute);return;}
    if (node.id === 'admin-refresh') {await render();return;}
    if (node.dataset.run) {await showRun(node.dataset.run);return;}
    if (node.hasAttribute('data-back-quality')) {navigate('quality');return;}
    if (node.hasAttribute('data-register-pilot')) {node.disabled = true;await api('/api/admin/pilot/register',{method:'POST'});notice('恰好 10 个 Pilot 场景已登记。');await render();return;}
    if (node.hasAttribute('data-import-core')) {node.disabled = true;await api('/api/admin/catalog/import',{method:'POST'});notice('标准资格集合已登记；相同 Case 身份不会重复创建。');await render();return;}
    if (node.hasAttribute('data-start-campaign')) {node.disabled = true;const run = await api('/api/admin/runs',{method:'POST',body:{campaign_id:$('#campaign-select').value}});notice('资格运行已持久化排队。关闭此页面不影响执行。');await showRun(run.id);return;}
    if (node.dataset.control) {node.disabled = true;await api(`/api/admin/runs/${currentRun}/control`,{method:'POST',body:{action:node.dataset.control}});await showRun(currentRun);return;}
    if (node.dataset.skipCase) {node.disabled = true;await api(`/api/admin/runs/${currentRun}/cases/${node.dataset.skipCase}/skip`,{method:'POST'});await showRun(currentRun);return;}
    if (node.dataset.rerun || node.dataset.rerunCase) {node.disabled = true;const mode = node.dataset.rerun || 'SELECTED';const selected = node.dataset.rerunCase ? [node.dataset.rerunCase] : [...document.querySelectorAll('[data-rerun-selection]:checked')].map(n => n.value);if (mode === 'SELECTED' && !selected.length) throw new Error('请选择至少一个场景。');const run = await api(`/api/admin/runs/${currentRun}/rerun`,{method:'POST',body:{mode,case_version_ids:mode === 'SELECTED' ? selected : []}});await showRun(run.id);return;}
    if (node.dataset.regression) {await api(`/api/admin/findings/${node.dataset.regression}/regression`,{method:'POST'});notice('同一 Case 已纳入永久回归，没有复制场景身份。');await render();return;}
    if (node.dataset.variantRun) {const campaigns = await api('/api/admin/campaigns');const campaign = campaigns.find(c => c.key === `experiment-${node.dataset.variantRun}`);if (!campaign) throw new Error('此实验尚未绑定资格集合。');await api('/api/admin/runs',{method:'POST',body:{campaign_id:campaign.id,experiment_id:node.dataset.variantRun,variant_key:node.dataset.variant}});notice('策略比较已排队，原生产配置保持独立。');return;}
    if (node.dataset.preference) {const arena = await api('/api/admin/arena');const e = arena.experiments.find(x => x.id === node.dataset.preference);const runs = (await api('/api/admin/runs')).filter(r => r.experiment_id === e.id && ['PASS','FAIL','BLOCKED'].includes(r.state));const selected = {};
      for (const v of e.definition.variants) {const r = runs.find(r => r.variant_key === v.key);if (!r) throw new Error('请先为每个策略完成一次有证据的资格运行。');const detail = await api(`/api/admin/runs/${r.id}`);const c = detail.cases.find(c => c.case_version_id === e.case_version_id);if (!c) throw new Error('运行结果未绑定本实验的精确 Case。');selected[v.key] = c;}
      content.innerHTML = heading('比较结果并记录偏好','每个结果绑定精确 Case、策略、Watt 版本与执行证据。') + `<section class="admin-panel">${table(['策略','客观结果','耗时','结果与执行证据'],e.definition.variants.map(v => [esc(v.label),status(selected[v.key].state),`${Number(selected[v.key].elapsed_seconds).toFixed(1)} 秒`,evidence(selected[v.key])]))}</section><form class="admin-form" data-preference-form data-experiment="${esc(e.id)}"><label>优先选择<select name="winner">${e.definition.variants.map(v => `<option value="${esc(v.key)}">${esc(v.label)}</option>`).join('')}</select></label>${e.definition.variants.map(v => `<label>${esc(v.label)}是否可接受<select name="acceptable-${esc(v.key)}"><option value="true">可接受</option><option value="false">不可接受</option></select></label><input type="hidden" name="run-${esc(v.key)}" value="${esc(selected[v.key].id)}">`).join('')}<label>置信度<input name="confidence" type="number" min="0" max="1" step=".1" value=".8"></label><label>理由标签<select name="reason"><option value="resource-cost">资源成本</option><option value="result-quality">结果质量</option><option value="reliability">可靠性</option></select></label><label>具体理由<textarea name="rationale" required></textarea></label><button class="button" type="submit">记录偏好</button></form>`;return;}
    if (node.dataset.attribute) {content.innerHTML = heading('形成 Owner 学习信号','归因是有置信度的假设，不是工程事实，也不会修改生产策略。') + `<form class="admin-form" data-attribution-form data-source="${esc(node.dataset.attribute)}"><label>可能受影响的 Owner<select name="owner">${['WIC','IRK','ECF','SEARCH','PLANNING','MODEL_ROUTING','EXECUTION','VERIFICATION','GUARDIAN'].map(o => `<option>${o}</option>`).join('')}</select></label><label>置信度<input name="confidence" type="number" min="0" max="1" step=".1" value=".6"></label><label>归因依据<textarea name="rationale" required></textarea></label><button class="button" type="submit">保存学习信号</button></form>`;return;}
    if (node.hasAttribute('data-generate-holdout')) {await api('/api/admin/holdouts/generate',{method:'POST'});notice('新场景已封存；优化与偏好入口无法读取其材料。');await render();return;}
    if (node.dataset.caseHistory) {const h = await api(`/api/admin/cases/${node.dataset.caseHistory}/history`);content.innerHTML = heading('场景资格历史','Case 身份不变，版本和每次资格结果独立保留。') + `<button class="button secondary" data-back-quality>返回质量</button>${evidence(h)}`;return;}
    if (node.dataset.llmEvaluation) {node.disabled = true;await api(`/api/admin/case-runs/${node.dataset.llmEvaluation}/llm-evaluation`,{method:'POST'});await showRun(currentRun);return;}
    if (node.dataset.promotion) {const arena = await api('/api/admin/arena');const experiment = arena.experiments.find(e => e.id === node.dataset.promotion);const runs = (await api('/api/admin/runs')).filter(r => r.experiment_id === experiment.id && r.state === 'PASS');
      content.innerHTML = heading('审查候选策略晋升','选择精确策略与证据，并填写人工判断。门禁要求相同版本和配置的重要场景、历史回归与新生成未见场景。') + `<form class="admin-form" data-promotion-form data-experiment="${esc(experiment.id)}"><label>候选策略<select name="variant">${experiment.definition.variants.map(v => `<option value="${esc(v.key)}">${esc(v.label)}</option>`).join('')}</select></label>${runs.map(r => `<label><input type="checkbox" name="run_id" value="${esc(r.id)}">${esc(r.variant_key)} · ${esc(r.id)} · ${esc(r.watt_revision)}</label>`).join('') || '<p>尚无合格证据。</p>'}<label>人工晋升理由<textarea name="rationale" required></textarea></label><button class="button" type="submit">提交受治理晋升决定</button></form>`;return;}

  } catch (error) {notice(error.code === 'PROMOTION_REQUIRES_GOLDEN_REGRESSION_FRESH_HOLDOUT' ? '晋升门禁未通过：需要相同候选策略的合格重要场景、历史回归与未见场景证据。' : error.message);node.disabled = false;}});
  document.addEventListener('submit',async event => {const f = event.target;if (!(f instanceof HTMLFormElement)) return;event.preventDefault();const data = new FormData(f);try {if (f.hasAttribute('data-admin-login')) {await api('/auth/session',{method:'POST',body:{token:data.get('token')}});f.reset();await render();return;}
    if (f.hasAttribute('data-experiment-form')) {await api('/api/admin/experiments',{method:'POST',body:{case_id:data.get('case_id'),name:data.get('name'),changed_variables:['policy'],rationale:data.get('rationale'),variants:[{key:'current',label:'当前资格策略',model:'NOT_APPLICABLE',provider:'qualification-fixture',policy:{case_timeout_seconds:Number(data.get('baseline'))}},{key:'candidate',label:'候选资格策略',model:'NOT_APPLICABLE',provider:'qualification-fixture',policy:{case_timeout_seconds:Number(data.get('alternative'))}}]}});await render();return;}
    if (f.hasAttribute('data-preference-form')) {const arena = await api('/api/admin/arena');const e = arena.experiments.find(x => x.id === f.dataset.experiment);const winner = data.get('winner');const keys = e.definition.variants.map(v => v.key);await api('/api/admin/preferences',{method:'POST',body:{experiment_id:e.id,ranking:[winner,...keys.filter(k => k !== winner)],acceptability:Object.fromEntries(keys.map(k => [k,data.get(`acceptable-${k}`) === 'true'])),case_run_ids:Object.fromEntries(keys.map(k => [k,data.get(`run-${k}`)])),confidence:Number(data.get('confidence')),reason_tags:[data.get('reason')],rationale:data.get('rationale')}});notice('偏好已保存，客观验证结果未被覆盖。');navigate('arena');return;}
    if (f.hasAttribute('data-promotion-form')) {await api('/api/admin/promotion-decisions',{method:'POST',body:{experiment_id:f.dataset.experiment,variant_key:data.get('variant'),campaign_run_ids:data.getAll('run_id'),rationale:data.get('rationale')}});notice('人工晋升决定已记录；生产策略变更仍需独立治理。');navigate('arena');return;}
    if (f.hasAttribute('data-attribution-form')) {await api('/api/admin/attributions',{method:'POST',body:{source_kind:'PREFERENCE',source_id:f.dataset.source,owners:[data.get('owner')],confidence:Number(data.get('confidence')),rationale:data.get('rationale')}});notice('学习信号已保存；没有直接修改生产。');navigate('arena');}
  } catch (error) {notice(error.message);}});
  window.addEventListener('popstate', () => {currentRun = new URLSearchParams(location.search).get('run');render();});
  render();
})();
