/* Watt Admin shares authentication and assets with Watt; it never owns Work truth. */
(() => {
  'use strict';
  const $ = (s, root = document) => root.querySelector(s);
  const content = $('#admin-content');
  let overview = null;
  let currentRun = new URLSearchParams(location.search).get('run');
  const esc = value => String(value ?? '').replace(/[&<>"']/g, x => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  const labels = {PAUSE_REQUESTED:'等待安全暂停',PAUSED:'已暂停',STOPPING:'等待安全停止',STOPPED:'已停止',NOT_RUN:'未执行',PASS:'通过',FAIL:'失败',BLOCKED:'受阻',QUEUED:'等待执行',RUNNING:'进行中',READY:'可接任务',BUSY:'执行中',OFFLINE:'离线',DRAINING:'排空中',UNKNOWN:'未知',NOT_CONFIGURED:'未配置健康探测',UNAVAILABLE:'不可观测',CURRENT:'当前观测',STALE:'观测过期',NOT_SAMPLED:'尚未采样',OPEN:'待处理',CLOSED:'已关闭',MISSING:'缺少服务',INTERRUPTED:'已中断',COMPLETED:'完成',WAITING_RESOURCE:'等待容量',WAITING_HUMAN:'等待人工决定',EXECUTING:'执行中',GOLDEN:'重要场景',REGRESSION:'历史回归',FRESH_HOLDOUT:'未见场景',PREFERENCE:'偏好实验',ACTIVE:'使用中',healthy:'健康',running:'运行中',exited:'已退出',unhealthy:'异常',starting:'启动中'};
  function status(value) { const kind = ['FAIL','OFFLINE','MISSING','unhealthy','exited'].includes(value) ? 'bad' : ['BLOCKED','QUEUED','STALE','WAITING_RESOURCE','WAITING_HUMAN','starting'].includes(value) ? 'waiting' : ['UNKNOWN','UNAVAILABLE','NOT_SAMPLED','NOT_CONFIGURED'].includes(value) ? 'unknown' : 'good';return `<span class="admin-status" data-kind="${kind}">${esc(labels[value] || value || '未报告')}</span>`; }
  const bytes = n => typeof n !== 'number' ? '未观测' : n >= 1073741824 ? `${(n / 1073741824).toFixed(2)} GiB` : `${(n / 1048576).toFixed(1)} MiB`;
  const date = value => value ? new Date(value).toLocaleString('zh-CN') : '未记录';
  const evidence = value => `<details class="admin-evidence"><summary>查看证据与血缘</summary><pre>${esc(JSON.stringify(value, null, 2))}</pre></details>`;
  const heading = (title, subtitle) => `<header class="admin-heading"><p class="eyebrow">Watt Admin</p><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></header>`;
  function table(headers, rows, empty = '暂时没有记录。') { return rows.length ? `<div class="admin-table-wrap"><table class="admin-table"><thead><tr>${headers.map(x => `<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(x => `<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>` : `<p class="admin-empty">${esc(empty)}</p>`; }
  function notice(text) { const node = $('#admin-notice');node.textContent = text;node.hidden = false;setTimeout(() => {node.hidden = true;}, 7000); }
  async function api(path, options = {}) { const response = await fetch(path, {credentials:'same-origin', headers:{'Content-Type':'application/json'}, ...options, ...(options.body ? {body:JSON.stringify(options.body)} : {})});let data;try {data = await response.json();} catch (_) {data = {}; }if (!response.ok) {const error = new Error(data.message || data.code || '请求未完成');error.status = response.status;error.code = data.code;throw error;}return data; }
  function route() { return location.pathname.split('/')[2] || 'overview'; }
  function navigate(section) {history.pushState({}, '', section === 'overview' ? '/admin' : `/admin/${section}`);currentRun = null;render();}
  function login() { content.innerHTML = heading('登录 Watt Admin', '使用现有 Watt 拥有者凭证。质量证据和运行数据仅对已登录的拥有者开放。') + `<form class="admin-form" data-admin-login><label>登录凭证<input type="password" name="token" required autocomplete="current-password"></label><button class="button" type="submit">登录</button></form>`; }
  function cards(items) {return `<div class="admin-cards">${items.map(([title,value,detail]) => `<section class="admin-card"><h2>${esc(title)}</h2><strong>${value}</strong><p>${esc(detail || '')}</p></section>`).join('')}</div>`;}
  function runsTable(runs) {return table(['时间','状态','Watt 版本','查看'],runs.map(r => [esc(date(r.created_at)),status(r.state),`<code>${esc(r.watt_revision?.slice(0,12))}</code>`,`<button class="button secondary" data-run="${esc(r.id)}">查看本次结果</button>`]));}
  function assuranceTable(results) {return table(['结果','候选成果','精确源码','时间'],results.map(r => [status(r.gate),`<button class="button secondary" data-trace-entity="${esc(r.candidate_id)}" data-trace-kind="candidate">查看候选生产历程</button>`,`精确修订已记录${evidence(r)}`,esc(date(r.assessed_at))]),'尚无可读取的 Guardian 结果。');}
  async function showRun(id) {
    const r = await api(`/api/admin/runs/${encodeURIComponent(id)}`);currentRun = id;
    if (new URLSearchParams(location.search).get('run') !== id) history.pushState({}, '', `/admin/quality?run=${encodeURIComponent(id)}`);
    const evaluator = {DETERMINISTIC:'确定性判据',RUNTIME:'运行事实',GUARDIAN:'Guardian 判断',LLM:'模型评估',HUMAN:'人工评价'};
    const active = ['QUEUED','RUNNING','PAUSE_REQUESTED','PAUSED'].includes(r.state);
    const terminal = ['PASS','FAIL','BLOCKED','STOPPED'].includes(r.state);
    const controls = `<div class="admin-actions" data-run-controls><button class="button secondary" data-back-quality>返回资格集合</button>${status(r.lifecycle || r.state)} ${terminal && r.state !== 'STOPPED' ? status(r.state) : ''}<button class="button secondary" data-run="${esc(id)}">刷新本次结果</button>
      <button class="button secondary" data-control="PAUSE" ${['QUEUED','RUNNING'].includes(r.state) ? '' : 'disabled'}>暂停</button>
      <button class="button" data-control="RESUME" ${r.state === 'PAUSED' ? '' : 'disabled'}>继续本次运行</button>
      <button class="button secondary" data-control="STOP" ${active ? '' : 'disabled'}>停止本次运行</button>
      <button class="button secondary" data-rerun="FAILED" ${terminal ? '' : 'disabled'}>重跑失败场景</button>
      <button class="button secondary" data-rerun="SELECTED" ${terminal ? '' : 'disabled'}>重跑所选场景</button>
      <button class="button secondary" data-rerun="ALL" ${terminal ? '' : 'disabled'}>重跑全部场景</button></div>`;
    const p = r.progress || {};
    const countCards = cards([['符合预期',p.PASS ?? 0,'已完成场景'],['需要关注',Number(p.FAIL || 0)+Number(p.BLOCKED || 0)+Number(p.UNKNOWN || 0),'失败、受阻或资格不足'],['等待执行',p.QUEUED ?? 0,r.current_case?.title || '当前无在途场景'],['经过时间',`${Math.round(r.elapsed_seconds || 0)} 秒`,'暂停和停止以安全边界为准']]);
    const systemStop = [...(r.controls || [])].reverse().find(e => e.action === 'SYSTEM_STOP_THE_LINE');
    content.innerHTML = heading('本轮验证', `${p.total ?? r.cases.length} 个场景 · ${p.PASS ?? 0} 个符合预期 · ${Number(p.FAIL || 0)+Number(p.BLOCKED || 0)} 个需要关注 · ${date(r.created_at)}`) + evidence({run:id,revision:r.watt_revision,policy:r.policy_fingerprint}) + controls + `<p class="admin-muted">暂停和停止均等待当前场景的安全边界；已完成证据永久保留。继续沿用同一 Run；重跑建立新 Run。</p>` +
      (systemStop ? `<section class="admin-alert" data-stop-the-line><strong>系统暂停依据</strong><p>最近 5 个场景中至少 4 个违反同一已观测判据，需要明确继续或停止。</p>${evidence(systemStop)}</section>` : '') + countCards +
      `<section class="admin-panel"><h2>资格摘要</h2><p>历史回归复发：${r.regression_recurrences || 0} · 新失败分组：${r.new_failure_clusters || 0}</p>${evidence({earliest_divergence_distribution:r.earliest_divergence_distribution,fresh_holdout:r.fresh_holdout,parent_run:r.parent_run_id,policy_fingerprint:r.policy_fingerprint,configuration:r.configuration})}</section>` +
      (r.members || []).map(m => {const c = m.attempt;return `<section class="admin-panel" data-case-version="${esc(m.case_version_id)}"><h2><label><input type="checkbox" data-rerun-selection value="${esc(m.case_version_id)}">${esc(m.title)}</label> ${status(m.state)}</h2>
        <p class="admin-muted">场景版本 ${m.version} · ${m.cohorts.map(v=>esc(labels[v] || v)).join(' / ')} · ${c?.elapsed_seconds == null ? (m.state === 'RUNNING' ? '执行尚未结束' : '尚无完成证据') : `${Number(c.elapsed_seconds).toFixed(1)} 秒`} · 最早观测偏离：${esc(c?.lineage.divergence?.stage ? ownerLabel(c.lineage.divergence.stage) : (m.state === 'PASS' ? '未观测到失败' : '尚未归因'))}</p>
        ${m.definition.sealed ? '<p>未见场景答案已封存，不进入优化与模型评价。</p>' : `<p>${esc(m.definition.motive)}</p>${evidence({input:m.definition.context,obligations:m.definition.invariants,version_fingerprint:m.fingerprint})}`}
        ${c ? `<p>${esc(c.human_outcome?.quality_label || (c.state==='PASS'?'场景符合预期':'场景未完成合格验证'))}</p><p>${esc(c.human_outcome?.production_label || '场景结果与生产结果需要分开审查。')}</p><button class="button secondary" data-trace="${esc(c.id)}">查看生产历程</button>` + table(['评估维度','结果','证据'],c.evaluations.map(e => [esc(evaluator[e.evaluator] || e.evaluator),status(e.outcome),evidence(e)])) + evidence(c.lineage) : ''}
        ${evidence({findings:m.findings,attribution:m.attribution,source_case_run_id:m.source_case_run_id,owner_references:m.owner_references})}
        ${m.state === 'QUEUED' && active ? `<button class="button secondary" data-skip-case="${esc(m.case_version_id)}">跳过排队场景</button>` : ''}
        ${terminal && ['FAIL','BLOCKED','UNKNOWN'].includes(m.state) ? `<button class="button secondary" data-rerun-case="${esc(m.case_version_id)}">重跑此失败场景</button>` : ''}
        ${c && !c.lineage.sealed && ['PASS','FAIL','BLOCKED'].includes(m.state) ? `<button class="button secondary" data-llm-evaluation="${esc(c.id)}">添加独立模型意见</button>` : ''}</section>`;}).join('') +
      `<section class="admin-panel"><h2>运行与资源关联</h2><a href="/admin/infrastructure">查看基础设施观测</a> · <a href="/admin/operations">查看生产容量</a>${evidence({operations_samples:r.operations_samples,control_history:r.controls})}</section>`;
  }

  function assurancePage() { const a = overview.assurance;content.innerHTML = heading('风险与保证', '直接展示 Guardian 的精确结果。Quality 通过独立确定性判据评价保证能力；Guardian 不充当自己的唯一判据。') + `<p class="admin-muted">Owner 模式：${esc(a.mode)} · 结果存储：${a.store_observed ? '可读取' : '不可读取'}</p><section class="admin-panel">${assuranceTable(a.results)}</section><section class="admin-panel"><h2>独立质量评价</h2>${table(['结果','独立判据与覆盖证据'],(a.quality_evaluations || []).map(e => [status(e.outcome),evidence(e.record)]))}</section>`; }
  function operationsPage() { const p = overview.operations.production;content.innerHTML = heading('运行与资源', 'Worker、队列与容量直接来自现有运行时。就绪与实际运行保持区分，管理面不调高生产并发。') + `${resourceSummary(overview.operations)}<p><a href="/admin/infrastructure">查看服务器资源、服务拓扑与存储趋势</a></p>` + cards([['正在执行',String(p.active_executions),'来自有效 allocation'],['当前队列',String(p.queue_depth),'展示最早的 100 条记录'],['可用名额',String(p.available_slots),'扣除有效占用并检查心跳'],['Worker',String(p.workers.length),'已登记执行资源']]) + `<section class="admin-panel"><h2>执行资源</h2>${table(['Worker','状态','容量','当前执行','可用','最后心跳'],p.workers.map(w => [esc(w.name || w.worker_id),status(w.status),esc(w.capacity.max_concurrency),esc(w.active_execution_count),esc(w.available_slots),esc(date(w.last_heartbeat_at || w.heartbeat_at))]))}</section><section class="admin-panel"><h2>等待与执行队列</h2>${table(['Execution','状态','等待原因','入队时间','经过时间'],p.queue.map(q => [esc(q.work_title || q.objective || '已登记生产任务'),status(q.condition),esc(q.wait_reason || '运行时未报告等待原因'),esc(date(q.enqueued_at)),`${Math.floor(q.elapsed_seconds / 60)} 分钟`]))}</section>`; }
  function trend(samples, getter, label) {const values = samples.map(getter).filter(v => typeof v === 'number');if (values.length < 2) return `<p class="admin-muted">${esc(label)}：需要至少两次有效采样。</p>`;const min = Math.min(...values),max = Math.max(...values);const points = values.map((v,i) => `${10+i*980/(values.length-1)},${95-(v-min)*80/Math.max(max-min,1)}`).join(' ');return `<figure><figcaption class="admin-muted">${esc(label)} · ${values.length} 次有效采样</figcaption><svg class="admin-trend" viewBox="0 0 1000 110" role="img" aria-label="${esc(label)}短期趋势"><polyline points="${points}"></polyline></svg></figure>`;}
  async function infrastructurePage() {const o = overview.operations,n = o.node;const history = await api('/api/admin/operations/history');content.innerHTML = heading('基础设施', '当前节点资源与服务位置来自真实观测。测量不可用时明确显示未知；存储口径不同，不相加伪造总量。') + `<p class="admin-muted">观测：${status(o.state)} · ${esc(date(n?.observed_at))}</p>` + cards([['CPU',typeof n?.cpu_percent === 'number' ? `${n.cpu_percent}%` : '未观测',n?.cpu_count ? `${n.cpu_count} 个 CPU` : '需要连续采样'],['内存',n?.memory ? bytes(n.memory.used_bytes) : '未观测',n?.memory ? `总量 ${bytes(n.memory.total_bytes)}` : '主机数据不可用'],['数据盘',n?.disk ? bytes(n.disk.used_bytes) : '未观测',n?.disk ? `总量 ${bytes(n.disk.total_bytes)}` : '尚未取得 /data 观测'],['运行时间',n?.uptime_seconds ? `${Math.floor(n.uptime_seconds / 3600)} 小时` : '未观测',n?.hostname || '主机名未绑定']]) + `<section class="admin-panel"><h2>节点与服务位置</h2>${o.topology.nodes.map(node => `<div class="admin-node"><strong>${esc(node.id)}</strong><p class="admin-muted">${esc(node.hostname || '未观测主机名')} · ${esc(node.region || 'Region 未绑定')}</p><div class="admin-placement">${o.topology.service_placements.filter(s => s.node_id === node.id).map(s => `<span>${esc(s.service)} ${status(s.health === 'NOT_CONFIGURED' ? s.state : s.health)}</span>`).join('')}</div></div>`).join('') || '<p class="admin-empty">尚未取得节点观测。</p>'}<p class="admin-muted">当前只确认此 Docker 项目的服务位置，未声明跨主机执行能力。</p></section><section class="admin-panel"><h2>服务健康</h2>${table(['服务','进程','健康探测','启动时间'],o.services.map(s => [esc(s.service),status(s.state),status(s.health),esc(date(s.started_at))]))}</section><section class="admin-panel"><h2>存储观测</h2>${table(['类别','占用','测量口径'],Object.entries(o.storage).filter(([k]) => !['docker','note'].includes(k)).map(([k,v]) => [esc({postgresql:'PostgreSQL',watt_data:'Watt 数据',workspaces:'隔离工作区',execution_data:'执行运行数据',logs:'日志',gitea:'Gitea'}[k] || k),bytes(v.bytes),`${esc(v.method)}${v.state && v.state !== 'OBSERVED' ? '<small>不可完整测量</small>' : ''}`]))}${table(['Docker 类别','总量','可回收'],o.storage.docker.categories.map(d => [esc(d.Type),esc(d.Size),esc(d.Reclaimable)]))}<p class="admin-muted">${esc(o.storage.note)}</p></section><section class="admin-panel"><h2>网络观测</h2>${table(['网卡','接收累计','发送累计','速率'],Object.entries(n?.network || {}).filter(([name]) => name !== 'lo').map(([name,v]) => [esc(name),bytes(v.rx_bytes),bytes(v.tx_bytes),v.rx_bytes_per_second == null ? '需连续采样' : `↓ ${bytes(v.rx_bytes_per_second)}/s · ↑ ${bytes(v.tx_bytes_per_second)}/s`]))}<p class="admin-muted">网卡单独显示，避免将物理口与虚拟桥流量重复相加。</p></section><section class="admin-panel"><h2>短期趋势</h2>${trend(history,s => s.cpu_percent,'CPU')}${trend(history,s => s.memory?.used_bytes,'内存占用')}${trend(history,s => s.disk?.used_bytes,'数据盘占用')}${trend(history,s => s.queue_depth,'队列深度')}${trend(history,s => s.active_executions,'活动执行')}</section>`;}
  async function arenaPage() {const arena = await api('/api/admin/arena');const cases = overview.quality.cases.filter(c => !c.cohorts.includes('FRESH_HOLDOUT'));content.innerHTML = heading('学习与改进', '先固定 Case 和差异变量，再比较有精确执行证据的结果。偏好形成学习信号，不能覆盖确定性失败或直接改生产行为。') + `<details class="admin-panel"><summary>建立策略比较（需你明确提交）</summary><h2>建立策略比较</h2><p class="admin-muted">v1 可比较固定资格配方在不同执行时限策略下的结果与成本。未资格化的模型、提示或规划路由不会仅因改了元数据而被报告为生效。</p><form class="admin-form" data-experiment-form><label>场景<select name="case_id" required>${cases.map(c => `<option value="${esc(c.id)}">${esc(c.definition.title)}</option>`).join('')}</select></label><label>实验名称<input name="name" required value="资格执行时限比较"></label><div class="two"><label>当前策略时限（秒）<input name="baseline" type="number" min="30" max="900" value="600" required></label><label>候选策略时限（秒）<input name="alternative" type="number" min="30" max="900" value="300" required></label></div><label>为什么比较<textarea name="rationale" required placeholder="例如：观察更紧的时限是否仍能完成完整验证，并控制资源成本。"></textarea></label><button class="button" type="submit">建立版本化实验</button></form></details>` + arena.experiments.map(e => `<section class="admin-panel"><h2>${esc(e.definition.name)} · v${e.version}</h2><p class="admin-muted">差异变量：${e.definition.changed_variables.map(esc).join('、')}</p>${table(['策略','明确差异','运行'],e.definition.variants.map(v => [esc(v.label),`${v.policy.case_timeout_seconds} 秒`,`<button class="button secondary" data-variant-run="${esc(e.id)}" data-variant="${esc(v.key)}">运行此策略</button>`]))}<div class="admin-actions"><button class="button secondary" data-preference="${esc(e.id)}">比较已有结果并记录偏好</button><button class="button secondary" data-promotion="${esc(e.id)}">检查候选策略晋升门禁</button></div>${evidence({fingerprint:e.fingerprint,definition:e.definition})}</section>`).join('') + `<section class="admin-panel"><h2>人工偏好记录</h2>${table(['时间','选择','理由','归因'],arena.preferences.map(p => [esc(date(p.created_at)),esc(p.record.winner || '差不多，没有胜出者'),esc(p.record.rationale),`<button class="button secondary" data-attribute="${esc(p.id)}">形成学习信号</button>${evidence(p.record.candidate_provenance)}`]))}</section><section class="admin-panel"><h2>Owner 学习信号</h2>${table(['Owner','来源','置信度','边界'],arena.learning_signals.map(s => [esc(ownerLabel(s.owner)),esc(s.source_kind==='PREFERENCE'?'人工偏好':'问题观测'),`${Math.round(s.record.confidence*100)}%`,esc(s.record.rationale || '优化假设；尚未改变生产策略')]))}</section><section class="admin-panel"><h2>晋升决定</h2>${table(['时间','候选策略','决定'],arena.promotion_decisions.map(p => [esc(date(p.created_at)),esc(p.variant_key),'已批准进入受治理变更；未直接修改生产']))}</section>`;}
  const ownerLabel = value => ({WIC:'交流与表达',IRK:'意图理解',ECF:'生产上下文',WORK:'事项事实',SOURCE:'工程来源',STEERING:'推进决策',PLANNING:'生产规划',PWU:'生产单元',EXECUTION:'执行',VERIFICATION:'独立验证',GUARDIAN:'独立质量保证',CANDIDATE:'候选成果',GOVERNANCE:'人工治理',DEPLOYMENT:'部署',SEARCH:'资料检索'}[value] || value || '尚未确定');
  const classLabel = value => ({PRODUCT_INTENT:'产品意图',PRODUCT_INVARIANT:'产品不变量',APPROVED_DECISION:'已批准的产品决定',APPROVED_CONSTRAINT:'已准入的约束',WORK_REALITY:'事项事实',REPOSITORY_REALITY:'精确代码来源',VERIFICATION_EVIDENCE:'验证证据'}[value] || value);
  const measured = (value, unit='') => value == null ? '未采集' : `${Number(value).toLocaleString('zh-CN')}${unit}`;
  const timeline = events => events?.length ? `<ol class="admin-timeline">${events.map(e => `<li><time>${esc(e.timestamp ? date(e.timestamp) : '时间未采集')}</time><div><strong>${esc(e.title)}</strong> ${e.state ? status(e.state) : ''}<p class="admin-muted">${esc(ownerLabel(e.owner))}</p>${evidence({source:e.source_ref,detail:e.detail})}</div></li>`).join('')}</ol>` : '<p class="admin-empty">这一阶段未保存完整事件记录。</p>';
  function overviewPage() {
    const c=overview.cockpit || {condition:'数据不足',briefing:'尚未取得足够的质量比较证据。',issues:[],version_changes:[],active_runs:[]};
    const opened=c.issues.filter(i=>i.closure_state!=='CLOSED'),q=overview.quality;
    content.innerHTML=heading('Watt 今天怎么样？','总览：先看重要问题，再看已验证的能力与运行情况。')+`<section class="admin-briefing" data-quality-briefing><p class="eyebrow">当前结论</p><h2>${esc(c.condition)}</h2><p>${esc(c.briefing)}</p><p class="admin-muted">当前版本与验证基线${c.current_revision&&c.current_revision===c.evidence_revision?'一致':'尚未对齐'}。${esc(c.coverage_note || '缺少数据不能视为通过。')}${evidence({current_revision:c.current_revision,evidence_revision:c.evidence_revision,previous_revision:c.previous_revision})}</p></section>`+
      `<section class="admin-panel"><h2>现在需要关注</h2>${opened.length?opened.slice(0,4).map(i=>`<p><a href="/admin/issues">${esc(i.title)}</a> · ${esc(i.repair_label)}</p>`).join(''):'<p>当前账本没有未关闭的问题记录；这不代表尚未验证的能力已通过。</p>'}<a href="/admin/issues">查看全部问题</a></section>`+
      `<section class="admin-panel"><h2>有没有旧问题重新出现？</h2>${comparisonView(c.version_changes || [])}</section>`+
      `<section class="admin-panel"><h2>本轮验证</h2>${c.active_runs.length?runsTable(c.active_runs):'<p>当前没有进行中的质量验证。</p>'}<a href="/admin/quality">查看核心能力、历史问题与新场景</a></section>`+
      `<section class="admin-panel"><h2>核心能力与保证</h2><p>最近基线：${c.qualified ?? '未采集'} / ${c.observed ?? '未采集'} 个已观测场景符合预期。核心、历史回归与未见场景的覆盖不能互相替代。</p>${assuranceTable(overview.assurance.results.slice(0,3))}</section>`+
      `<section class="admin-panel"><h2>生产容量</h2><p>${overview.operations.production.active_executions} 个执行中，${overview.operations.production.queue_depth} 条排队记录，${overview.operations.production.available_slots} 个可用名额。</p><a href="/admin/operations">查看运行与资源</a></section>`;
  }
  function comparisonView(changes) {return changes.length?table(['场景','变化'],changes.map(c=>[esc(c.title),esc(c.label)])):'<p>目前没有可证明的场景回退；没有可比记录的版本不能据此判断改善。</p>';}
  function issuesPage() {const issues=overview.cockpit?.issues || [];content.innerHTML=heading('问题','聚合相同判据与 owner 的观测；后续验证通过不会改写历史失败或自动关闭问题。')+`<section class="admin-panel"><h2>当前问题 · ${issues.filter(i=>i.closure_state!=='CLOSED').length}</h2>${issues.filter(i=>i.closure_state!=='CLOSED').map(issueView).join('') || '<p>没有未关闭的问题记录。</p>'}</section><details class="admin-evidence"><summary>已关闭的问题</summary>${issues.filter(i=>i.closure_state==='CLOSED').map(issueView).join('') || '<p>尚无治理关闭记录。</p>'}</details>`;}
  function issueView(i) {return `<article class="admin-issue"><h3>${esc(i.title)}</h3><p>${esc(i.owner_label)} · ${esc(i.severity_label)} · ${esc(i.observation_label)}</p><p>${esc(i.repair_label)} · ${esc(i.regression_label)}</p><p class="admin-muted">首次：${esc(date(i.first_seen))}；最近：${esc(date(i.last_seen))}</p>${i.requalified_case_runs?.map(id=>`<button class="button secondary" data-trace="${esc(id)}">查看修后验证历程</button>`).join('') || ''}${i.regression_status==='NOT_PROMOTED'?`<button class="button secondary" data-regression="${esc(i.findings[0])}">纳入历史回归</button>`:''}${evidence(i)}</article>`;}
  function qualityPage() {const q=overview.quality;content.innerHTML=heading('质量','本轮验证、核心能力、历史问题与新场景。它们共享同一个 Case 身份，原始结果保留。')+`<section class="admin-panel"><h2>本轮与最近验证</h2>${runsTable(q.runs)}</section><section class="admin-panel"><h2>版本质量变化</h2>${comparisonView(overview.cockpit?.version_changes || [])}</section>`+[['GOLDEN','核心能力'],['REGRESSION','历史问题'],['FRESH_HOLDOUT','新场景']].map(([key,title])=>`<section class="admin-panel"><h2>${title}</h2>${table(['场景','资格历史'],q.cases.filter(c=>c.cohorts.includes(key)).map(c=>[esc(c.definition.title),`<button class="button secondary" data-case-history="${esc(c.id)}">查看历次验证</button>`]))}</section>`).join('')+`<details class="admin-evidence"><summary>选择验证范围与开始新一轮</summary><p>运行前选择精确范围；关闭浏览器不会停止后台验证。未见场景材料始终封存。</p><div class="admin-actions"><select id="campaign-select" aria-label="选择验证范围">${q.campaigns.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} · 版本 ${c.version}</option>`).join('')}</select><button class="button" data-start-campaign ${q.campaigns.length?'':'disabled'}>开始验证</button></div></details><details class="admin-evidence"><summary>高级：维护场景资产</summary><div class="admin-actions"><button class="button secondary" data-register-pilot>登记 10 场景 Pilot</button><button class="button secondary" data-import-core>登记标准资格集合</button><button class="button secondary" data-generate-holdout>生成封存未见场景</button></div>${evidence(q.cases)}</details>`;}
  let traceData=null;
  async function showTrace(id,kind=null) {
    const path=kind?`/api/admin/traces/${encodeURIComponent(kind)}/${encodeURIComponent(id)}`:`/api/admin/case-runs/${encodeURIComponent(id)}/trace`;
    traceData=await api(path);currentRun=null;
    history.pushState({},'',kind?`/admin/trace?kind=${encodeURIComponent(kind)}&entity=${encodeURIComponent(id)}`:`/admin/trace?case=${encodeURIComponent(id)}`);tracePage('story');
  }
  function tracePage(mode) {
    const t=traceData,d=t.diagnosis;
    let body='';
    if(mode==='diagnostic') {
      body=`<section class="admin-panel"><h2>最早可证明的偏离</h2><p>${esc(d.divergence_label)}。尚未观测的早期阶段不会自动视为通过。</p><p>${esc(d.quality_label)}；${esc(d.production_result)}</p></section>`+t.diagnostic_owners.map(o=>`<section class="admin-panel"><h2>${esc(ownerLabel(o.owner))}</h2>${o.owner==='ECF'?contextView(t.contexts):o.owner==='GUARDIAN'?guardianView(t.guardian):timeline(o.events)}</section>`).join('');
    } else {
      body=`<section class="admin-panel"><h2>最初的用户输入</h2><blockquote>${esc(t.first_human_input || '历史资格没有保存原始 Human 输入，不能用测试描述冒充。')}</blockquote><h3>这个场景在检查什么</h3><p>${esc(t.purpose)}</p><p class="admin-muted">${t.basis?.mode==='LIVE_ENTITY_LOOKUP'?'这是当前对象的生产记录查询。':`这是当时的资格观测，时间：${date(t.basis?.at)}；不会用当前产品状态补写历史。`}</p>${evidence(t.basis)}</section>`+
        `<section class="admin-panel"><h2>和 Watt 的完整交流</h2>${t.conversation.length?t.conversation.map(m=>`<article class="admin-dialogue"><h3>${m.actor==='HUMAN'?'你':'Watt'} <small>${esc(date(m.timestamp))}</small></h3><p>${esc(m.text)}</p>${evidence({source:m.source_ref,state:m.state})}</article>`).join(''):'<p>未采集真实对话。此自动回归只保存了场景与 owner 观测，不能生成一段虚构交流。</p>'}</section>`+
        `<section class="admin-panel"><h2>Watt 对意图的理解</h2>${t.semantic.length?t.semantic.map(ir=>`<p>${esc(ir.items?.filter(i=>i.kind==='PRODUCTION_INTENT').map(i=>i.production?.objective || i.statement).join('；') || '这次没有当前生产意图。')}</p><p>是否需要 Human 决定：${ir.human_decisions?.length?'是，有具体的决策边界':'没有已保存的必需决定'}</p><details><summary>结构化理解与义务</summary>${table(['含义','内容','是否需要人工'],(ir.items || []).map(i=>[esc({PRODUCTION_INTENT:'生产意图',CONSTRAINT:'约束',FACT:'事实',QUESTION:'问题',OPERATIONAL_INTENT:'操作请求'}[i.kind] || '语义项'),esc(i.statement),i.requires_human?'需要':'无需']))}${evidence(ir)}</details>`).join(''):'<p>未采集治理后的语义；不能反推当时的理解。</p>'}</section>`+
        `<section class="admin-panel"><h2>当时使用的上下文</h2>${contextView(t.contexts)}</section>`+
        `<section class="admin-panel"><h2>资料检索</h2><p>${esc(t.search_note)}</p>${t.search.map(s=>`<p>查询：${esc(s.query || '未采集')}；来源：${esc(s.provider || '未采集')}；记录结果 ${measured(s.results_count)} 条。</p><p>${esc(s.influence)}</p>`).join('')}${timeline(t.search)}</section>`+
        `<section class="admin-panel"><h2>推进计划</h2>${t.steering.length?`<ol>${t.steering.map(s=>`<li><strong>${esc(s.human_visible || ({PRODUCE:'按已准入目标形成精确修改',VERIFY_ACCEPT:'核对已验证成果与本次目标',COMPLETE:'完成生产义务并等待 Human 验收'}[s.type]) || s.objective || s.title || '历史步骤')}</strong> ${status(({KNOWN:'QUEUED',CURRENT:'RUNNING',CLOSED:'COMPLETED'}[s.state]) || s.state || s.condition)}${evidence(s)}</li>`).join('')}</ol>`:'<p>未采集可读计划。</p>'}<details><summary>计划变化与版本</summary>${timeline(t.plan_history.map(p=>({timestamp:p.created_at,title:p.reason || '保存计划版本或推进变更',detail:p,source_ref:p.id,owner:'STEERING'})))}</details></section>`+
        `<section class="admin-panel"><h2>生产单元与依赖</h2>${t.units.length?t.units.map(unitView).join(''):'<p>此资格没有已保存的生产单元，不能假设它进入了执行。</p>'}</section>`+
        `<section class="admin-panel"><h2>排队与容量</h2>${table(['等待或执行','原因'],t.queue.map(q=>[status(q.condition),esc(q.wait_reason || (q.condition==='COMPLETED'?'执行已完成；分配与释放见历程':'运行时未记录具体等待原因'))]))}</section>`+
        `<section class="admin-panel"><h2>可观测的模型参与</h2>${t.model_calls.map(m=>`<details><summary>模型调用 ${m.sequence} · ${esc(m.model || '模型未采集')} · ${esc(labels[m.state] || '状态未采集')}</summary><p>${esc(m.purpose)}</p><p>上下文：${m.context_classes.map(classLabel).map(esc).join('、') || '未采集'}；输入类别：${m.input_categories.map(esc).join('、') || '未采集'}</p><p>耗时 ${measured(m.duration_ms,' ms')}；输入 ${measured(m.usage?.input_tokens)} / 输出 ${measured(m.usage?.output_tokens)} token。</p>${toolProposalView(m.observable_result)}${evidence(m)}</details>`).join('') || '<p>未采集模型调用，不能声称使用或未使用模型。</p>'}<p class="admin-muted">仅展示可观测请求、输出提案、状态与用量，不展示隐藏思维链。</p></section>`+
        `<section class="admin-panel"><h2>重要工具动作</h2>${timeline(t.tool_calls)}</section>`+
        `<section class="admin-panel"><h2>自修复、重试与恢复</h2><p>${esc(d.stability)}</p>${t.recovery.map(r=>`<article><p>${esc(r.failure_family==='CANDIDATE_INCONSISTENT'?'执行产物与当前义务不一致，owner 发起一次受治理恢复。':r.diagnosis_summary || 'owner 记录了一次恢复。')}</p><p>${esc(date(r.created_at))} · ${esc(r.final_result==='LOCAL_OBLIGATION_RECOVERED'?'局部生产义务已恢复':'恢复结果见证据')}</p>${evidence(r)}</article>`).join('')}</section>`+
        `<section class="admin-panel"><h2>独立验证</h2>${table(['验证事项','结果','时间'],t.verification.map(v=>[esc({PATH_SCOPE:'修改范围',GIT_DIFF_CHECK:'代码差异一致性',TEST_COMMAND:'测试命令',ARTIFACT_EXISTS:'产物存在'}[v.obligation] || v.obligation || '已治理验证'),status(v.result),esc(date(v.timestamp))+evidence(v)]))}</section>`+
        `<section class="admin-panel"><h2>Guardian 独立质量保证</h2>${guardianView(t.guardian)}</section>`+
        `<section class="admin-panel"><h2>Human 决定与验收</h2>${timeline(t.governance)}${t.candidate.length&&!t.governance.some(e=>e.source_ref.startsWith('work_delivery_acceptances:'))?'<p>候选已形成，尚未采集 Human 接受事件；绝不自动验收。</p>':''}</section>`+
        `<section class="admin-panel"><h2>成果摘要</h2>${table(['文件','变化'],t.artifacts.map(a=>[esc(a.path),esc({CREATE:'新增',ADD:'新增',MODIFY:'修改',UPDATE:'修改',DELETE:'删除'}[a.change] || a.change || '已记录变化')]))}${t.candidate.length?'<p>已封存精确候选版本；其授权、验收、部署是独立步骤。</p>':'<p>尚无候选成果证据。</p>'}${evidence(t.candidate)}</section>`+
        `<section class="admin-panel"><h2>部署</h2><p>${esc(t.deployment_note)}</p>${t.deployment.length?table(['目标与结果','开始时间'],t.deployment.map(x=>[status(x.status || x.condition)+evidence(x),esc(date(x.created_at))])):''}</section>`+
        `<section class="admin-panel"><h2>本场景的质量诊断</h2><p>${esc(d.quality_label)}</p><p>${esc(d.production_result)}</p><p>${esc(d.production_label)}</p><p>最早可证明的偏离：${esc(d.divergence_label)}。${esc(d.safety)}</p><p>${esc(t.missing_note)}</p></section>`;
    }
    content.innerHTML=heading(t.scene || '生产历程','从 Human 输入到生产、验证、保证与候选成果。所有结论均有 owner 来源。')+`<div class="admin-actions"><button class="button ${mode==='story'?'':'secondary'}" data-trace-mode="story">故事视图</button><button class="button ${mode==='diagnostic'?'':'secondary'}" data-trace-mode="diagnostic">诊断视图</button><button class="button secondary" data-back-quality>返回质量</button></div>`+body+`<details class="admin-evidence"><summary>高级工程证据、精确身份与来源</summary>${evidence({source_references:t.source_references,...t.advanced})}</details>`;
  }
  function contextContent(o) {if(o.context_class==='PRODUCT_INTENT'){try{const x=JSON.parse(o.content);return x.desired_outcome || x.human_motive || o.content;}catch {}}return o.content;}
  function resourceSummary(o) {const n=o.node || {};return `<section class="admin-panel"><h2>服务器与服务</h2>${table(['资源','实测'],[['CPU',measured(n.cpu_percent,'%')],['内存',n.memory?`${bytes(n.memory.used_bytes)} / ${bytes(n.memory.total_bytes)}`:'未采集'],['磁盘',n.disk?`${bytes(n.disk.used_bytes)} / ${bytes(n.disk.total_bytes)}`:'未采集'],['网络',n.network?Object.entries(n.network).map(([k,v])=>`${k} 收 ${bytes(v.rx_bytes)} / 发 ${bytes(v.tx_bytes)}`).join('；'):'未采集']])}${table(['服务','状态'],(o.services || []).map(x=>[esc(x.service),status(x.health || x.state)]))}<p class="admin-muted">观测时间：${esc(date(n.observed_at))}；未采集或过期观测不能证明当前资源充足。</p></section>`;}
  function contextView(contexts) {return contexts?.length?contexts.map(c=>`<p>上下文合同：${c.contract_id==='MANAGED_GREENFIELD_PRODUCTION'?'首次受治理生产':c.contract_id==='PRODUCT_UI_CHANGE'?'既有产品修改':'已记录的决策上下文'}。</p>${c.missing_classes?.length?`<p>缺少：${c.missing_classes.map(classLabel).map(esc).join('、')}；生产保持关闭。</p>`:''}${table(['保护的事实','当时的内容'],(c.protected_obligations || []).map(o=>[esc(classLabel(o.context_class)),esc(contextContent(o))]))}<p class="admin-muted">未建立且不适用的不变量或产品决定不会凭空补造。</p>${evidence({fingerprint:c.package_fingerprint,generated_from:c.generated_from,selected_files:c.source_references,...c})}`).join(''):'<p>未采集当时的上下文；不能以今天的上下文替代。</p>';}
  function guardianView(results) {return results?.length?results.map(g=>`<p>独立保证：${status(g.gate || g.status)}</p><p>保证对象：精确 Candidate 与它的受治理效果；是否满足独立质量保证要求由 Guardian 判断。</p><p>已记录质量问题：${g.findings?.length ?? '未采集'}；受保护义务覆盖：${g.coverage_obligation_refs?.length ?? '未采集'}。</p><p>${esc(g.summary || (g.gate==='PASS'?'Guardian 对精确候选与已治理效果返回通过；不会代替 Human 验收。':'保证结果与 Finding 见 owner 证据。'))}</p>${evidence(g)}`).join(''):'<p>尚无此精确候选的 Guardian 结果，不能宣称保证通过。</p>';}
  function toolProposalView(result) {return `<p>${esc(result.summary || '结果摘要未采集')}</p>${table(['提议的外部动作','处置'],(result.tool_calls || []).map(c=>[esc(c.tool || c.tool_identity || c.name || '受控工具'),esc('提案已记录；实际生效见执行证据')]))}`;}
  function unitView(u) {return `<article class="admin-unit"><h3>${esc(u.name)}</h3><p>${status(u.state)} · ${u.dependencies.length?`依赖：${esc((u.dependency_names || []).join('、') || `${u.dependencies.length} 个前序生产单元`)}`:'没有已记录的前序依赖'}</p><p>输入来源：${u.source_revision?'绑定精确修订':'精确修订未采集'}；范围：${esc(u.scope.map(x=>String(x).replace(/^CREATE:/,'新建 ').replace(/^MODIFY:/,'修改 ').replace(/^DELETE:/,'删除 ')).join('、') || '未采集')}</p><p>允许产物路径：${esc((u.allowed_paths || []).join('、') || '以已治理范围为准；路径清单未单独采集')}；验证义务：${u.verification?.length || '未单独采集'}。</p><div class="admin-dag" role="img" aria-label="生产单元依赖">${u.dependencies.length?esc((u.dependency_names || []).join(' + ') || '所需前序成果')+' → ':''}${esc(u.name)} → 独立验证 → 候选成果</div><details open><summary>完整生命周期</summary>${timeline(u.events)}</details><h4>资源与时间</h4>${table(['指标','观测'],[['总执行时间',measured(u.metrics.elapsed_seconds,' 秒')],['排队时间',measured(u.metrics.queue_seconds,' 秒')],['模型时间',measured(u.metrics.model_seconds,' 秒')],['模型调用',measured(u.metrics.model_call_count)],['输入 token',measured(u.metrics.input_tokens)],['输出 token',measured(u.metrics.output_tokens)],['工具时间',measured(u.metrics.tool_seconds)],['验证时间',measured(u.metrics.verification_seconds)],['CPU',measured(u.metrics.cpu)],['内存',measured(u.metrics.memory)],['磁盘变化',measured(u.metrics.disk_delta)],['网络',measured(u.metrics.network)]].map(([k,v])=>[esc(k),esc(v)]))}${evidence({source:u.source_ref,id:u.id,baseline:u.baseline,revision:u.source_revision,verification:u.verification,dependencies:u.dependencies})}</article>`;}

  async function render() {try {await api('/auth/session');overview = await api('/api/admin/overview');document.querySelectorAll('[data-admin-route]').forEach(a => {if (a.dataset.adminRoute === route()) a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const query=new URLSearchParams(location.search);if(route()==='trace' && query.get('case')) return showTrace(query.get('case'));if(route()==='trace' && query.get('kind') && query.get('entity')) return showTrace(query.get('entity'),query.get('kind'));if (currentRun) return showRun(currentRun);switch (route()) {case 'quality':qualityPage();break;case 'issues':issuesPage();break;case 'arena':await arenaPage();break;case 'assurance':assurancePage();break;case 'operations':operationsPage();break;case 'infrastructure':await infrastructurePage();break;default:overviewPage();}} catch (e) {if (e.status === 401) login();else content.innerHTML = heading('当前状态不可用', '无法取得完整 owner 数据，未将缺失数据视为健康。') + `<p class="admin-alert">${esc(e.message)}</p>`;}}
  document.addEventListener('click',async event => {const node = event.target.closest('button,a');if (!node) return;try {
    if (node.matches('[data-admin-route]')) {event.preventDefault();navigate(node.dataset.adminRoute);return;}
    if (node.id === 'admin-refresh') {await render();return;}
    if(node.dataset.traceEntity){await showTrace(node.dataset.traceEntity,node.dataset.traceKind);return;}
    if(node.dataset.trace){await showTrace(node.dataset.trace);return;}
    if(node.dataset.traceMode){tracePage(node.dataset.traceMode);return;}
    if (node.dataset.run) {await showRun(node.dataset.run);return;}
    if (node.hasAttribute('data-back-quality')) {navigate('quality');return;}
    if (node.hasAttribute('data-register-pilot')) {node.disabled = true;await api('/api/admin/pilot/register',{method:'POST'});notice('恰好 10 个 Pilot 场景已登记。');await render();return;}
    if (node.hasAttribute('data-import-core')) {node.disabled = true;await api('/api/admin/catalog/import',{method:'POST'});notice('标准资格集合已登记；相同 Case 身份不会重复创建。');await render();return;}
    if (node.hasAttribute('data-start-campaign')) {node.disabled = true;const run = await api('/api/admin/runs',{method:'POST',body:{campaign_id:$('#campaign-select').value}});notice('资格运行已持久化排队。关闭此页面不影响执行。');await showRun(run.id);return;}
    if (node.dataset.control) {node.disabled = true;await api(`/api/admin/runs/${currentRun}/control`,{method:'POST',body:{action:node.dataset.control}});await showRun(currentRun);return;}
    if (node.dataset.skipCase) {node.disabled = true;await api(`/api/admin/runs/${currentRun}/cases/${node.dataset.skipCase}/skip`,{method:'POST'});await showRun(currentRun);return;}
    if (node.dataset.rerun || node.dataset.rerunCase) {node.disabled = true;const mode = node.dataset.rerun || 'SELECTED';const selected = node.dataset.rerunCase ? [node.dataset.rerunCase] : [...document.querySelectorAll('[data-rerun-selection]:checked')].map(n => n.value);if (mode === 'SELECTED' && !selected.length) throw new Error('请选择至少一个场景。');const run = await api(`/api/admin/runs/${currentRun}/rerun`,{method:'POST',body:{mode,case_version_ids:mode === 'SELECTED' ? selected : []}});await showRun(run.id);return;}
    if (node.dataset.regression) {await api(`/api/admin/findings/${node.dataset.regression}/regression`,{method:'POST'});notice('同一 Case 已纳入永久回归，没有复制场景身份。');await render();return;}
    if (node.dataset.variantRun) {const campaigns = await api('/api/admin/campaigns');const campaign = campaigns.find(c => c.key === `experiment-${node.dataset.variantRun}`);if (!campaign) throw new Error('此实验尚未绑定资格集合。');await api('/api/admin/runs',{method:'POST',body:{campaign_id:campaign.id,experiment_id:node.dataset.variantRun,variant_key:node.dataset.variant}});notice('策略比较已排队，原生产配置保持独立。');return;}
    if (node.dataset.preference) {const arena = await api('/api/admin/arena');const e = arena.experiments.find(x => x.id === node.dataset.preference);const runs = (await api('/api/admin/runs')).filter(r => r.experiment_id === e.id && ['PASS','FAIL','BLOCKED'].includes(r.state));const selected = {};
      for (const v of e.definition.variants) {const r = runs.find(r => r.variant_key === v.key);if (!r) throw new Error('请先为每个策略完成一次有证据的资格运行。');const detail = await api(`/api/admin/runs/${r.id}`);const c = detail.cases.find(c => c.case_version_id === e.case_version_id);if (!c) throw new Error('运行结果未绑定本实验的精确 Case。');selected[v.key] = c;}
      if(e.definition.variants.length!==2)throw Error('此偏好表单需要两个可比候选；保留已有多策略证据。');
      content.innerHTML = heading('比较结果并记录偏好','每个结果绑定精确 Case、策略、Watt 版本与执行证据。') + `<section class="admin-panel">${table(['策略','客观结果','耗时','结果与执行证据'],e.definition.variants.map(v => [esc(v.label),status(selected[v.key].state),`${Number(selected[v.key].elapsed_seconds).toFixed(1)} 秒`,evidence(selected[v.key])]))}</section><form class="admin-form" data-preference-form data-experiment="${esc(e.id)}"><fieldset><legend>哪个更好？A：${esc(e.definition.variants[0].label)}；B：${esc(e.definition.variants[1].label)}</legend>${[['CLEAR_A','明显 A 更好'],['SLIGHT_A','A 稍好'],['TIE','差不多'],['SLIGHT_B','B 稍好'],['CLEAR_B','明显 B 更好']].map(([value,label])=>`<label><input type="radio" name="strength" value="${value}" required>${label}</label>`).join('')}</fieldset>${e.definition.variants.map(v => `<label>${esc(v.label)}是否可接受<select name="acceptable-${esc(v.key)}"><option value="true">可接受</option><option value="false">不可接受</option></select></label><input type="hidden" name="run-${esc(v.key)}" value="${esc(selected[v.key].id)}">`).join('')}<label>置信度<input name="confidence" type="number" min="0" max="1" step=".1" value=".8"></label><label>理由标签<select name="reason"><option value="intent">理解更准确</option><option value="alignment">更符合我的意图</option><option value="reasonable">更合理</option><option value="bounded">没有过度设计</option><option value="concise">更简洁</option><option value="risk">风险考虑更好</option><option value="verification">验证更充分</option><option value="other">其他</option></select></label><label>具体理由<textarea name="rationale" required></textarea></label><button class="button" type="submit">记录偏好</button></form>`;return;}
    if (node.dataset.attribute) {content.innerHTML = heading('形成 Owner 学习信号','归因是有置信度的假设，不是工程事实，也不会修改生产策略。') + `<form class="admin-form" data-attribution-form data-source="${esc(node.dataset.attribute)}"><label>可能受影响的 Owner<select name="owner">${['WIC','IRK','ECF','SEARCH','PLANNING','MODEL_ROUTING','EXECUTION','VERIFICATION','GUARDIAN'].map(o => `<option>${o}</option>`).join('')}</select></label><label>置信度<input name="confidence" type="number" min="0" max="1" step=".1" value=".6"></label><label>归因依据<textarea name="rationale" required></textarea></label><button class="button" type="submit">保存学习信号</button></form>`;return;}
    if (node.hasAttribute('data-generate-holdout')) {await api('/api/admin/holdouts/generate',{method:'POST'});notice('新场景已封存；优化与偏好入口无法读取其材料。');await render();return;}
    if (node.dataset.caseHistory) {const h=await api(`/api/admin/cases/${node.dataset.caseHistory}/history`);content.innerHTML=heading('场景资格历史','场景身份稳定，每个版本与每次结果独立保存。')+`<button class="button secondary" data-back-quality>返回质量</button>${table(['时间','质量结果','历程'],h.case_runs.map(c=>[esc(date(c.created_at)),status(c.state),`<button class="button secondary" data-trace="${esc(c.id)}">查看生产历程</button>`]))}${evidence(h)}`;return;}
    if (node.dataset.llmEvaluation) {node.disabled = true;await api(`/api/admin/case-runs/${node.dataset.llmEvaluation}/llm-evaluation`,{method:'POST'});await showRun(currentRun);return;}
    if (node.dataset.promotion) {const arena = await api('/api/admin/arena');const experiment = arena.experiments.find(e => e.id === node.dataset.promotion);const runs = (await api('/api/admin/runs')).filter(r => r.experiment_id === experiment.id && r.state === 'PASS');
      content.innerHTML = heading('审查候选策略晋升','选择精确策略与证据，并填写人工判断。门禁要求相同版本和配置的重要场景、历史回归与新生成未见场景。') + `<form class="admin-form" data-promotion-form data-experiment="${esc(experiment.id)}"><label>候选策略<select name="variant">${experiment.definition.variants.map(v => `<option value="${esc(v.key)}">${esc(v.label)}</option>`).join('')}</select></label>${runs.map(r => `<label><input type="checkbox" name="run_id" value="${esc(r.id)}">${esc(r.variant_key)} · ${esc(r.id)} · ${esc(r.watt_revision)}</label>`).join('') || '<p>尚无合格证据。</p>'}<label>人工晋升理由<textarea name="rationale" required></textarea></label><button class="button" type="submit">提交受治理晋升决定</button></form>`;return;}

  } catch (error) {notice(error.code === 'PROMOTION_REQUIRES_GOLDEN_REGRESSION_FRESH_HOLDOUT' ? '晋升门禁未通过：需要相同候选策略的合格重要场景、历史回归与未见场景证据。' : error.message);node.disabled = false;}});
  document.addEventListener('submit',async event => {const f = event.target;if (!(f instanceof HTMLFormElement)) return;event.preventDefault();const data = new FormData(f);try {if (f.hasAttribute('data-admin-login')) {await api('/auth/session',{method:'POST',body:{token:data.get('token')}});f.reset();await render();return;}
    if (f.hasAttribute('data-experiment-form')) {await api('/api/admin/experiments',{method:'POST',body:{case_id:data.get('case_id'),name:data.get('name'),changed_variables:['policy'],rationale:data.get('rationale'),variants:[{key:'current',label:'当前资格策略',model:'NOT_APPLICABLE',provider:'qualification-fixture',policy:{case_timeout_seconds:Number(data.get('baseline'))}},{key:'candidate',label:'候选资格策略',model:'NOT_APPLICABLE',provider:'qualification-fixture',policy:{case_timeout_seconds:Number(data.get('alternative'))}}]}});await render();return;}
    if (f.hasAttribute('data-preference-form')) {const arena = await api('/api/admin/arena');const e = arena.experiments.find(x => x.id === f.dataset.experiment);const keys = e.definition.variants.map(v => v.key);const strength=data.get('strength');const winner=strength?.endsWith('_B')?keys[1]:keys[0];await api('/api/admin/preferences',{method:'POST',body:{experiment_id:e.id,ranking:[winner,...keys.filter(k => k !== winner)],strength,acceptability:Object.fromEntries(keys.map(k => [k,data.get(`acceptable-${k}`) === 'true'])),case_run_ids:Object.fromEntries(keys.map(k => [k,data.get(`run-${k}`)])),confidence:Number(data.get('confidence')),reason_tags:[data.get('reason')],rationale:data.get('rationale')}});notice('偏好已保存，客观验证结果未被覆盖。');navigate('arena');return;}
    if (f.hasAttribute('data-promotion-form')) {await api('/api/admin/promotion-decisions',{method:'POST',body:{experiment_id:f.dataset.experiment,variant_key:data.get('variant'),campaign_run_ids:data.getAll('run_id'),rationale:data.get('rationale')}});notice('人工晋升决定已记录；生产策略变更仍需独立治理。');navigate('arena');return;}
    if (f.hasAttribute('data-attribution-form')) {await api('/api/admin/attributions',{method:'POST',body:{source_kind:'PREFERENCE',source_id:f.dataset.source,owners:[data.get('owner')],confidence:Number(data.get('confidence')),rationale:data.get('rationale')}});notice('学习信号已保存；没有直接修改生产。');navigate('arena');}
  } catch (error) {notice(error.message);}});
  window.addEventListener('popstate', () => {currentRun = new URLSearchParams(location.search).get('run');render();});
  render();
})();
