/* Watt Product Experience: navigation and rendering over server-owned projections. */
(() => {
  const $ = (selector, root = document) => root.querySelector(selector);
  const content = $('#content');
  const notice = $('#route-notice');
  const dialog = $('#dialog-layer');
  const dialogContent = $('#dialog-content');
  const pendingKey = 'watt:pending-home-intent';
  const returnKey = 'watt:login-return';
  const state = { authenticated: false, actor: null, routeEpoch: 0, timer: null, dialogReturn: null, homeInteraction: null, lastQuery: null, routeTransition: null };
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  const short = (value, max = 120) => { const text = String(value ?? ''); return text.length > max ? `${text.slice(0,max - 1)}…` : text; };
  const href = (path) => esc(path);
  const productPath = (id) => `/products/${encodeURIComponent(id)}`;
  const workspacePath = (id, workId, interactionId) => `${productPath(id)}/workspace${workId || interactionId ? `?${new URLSearchParams({...(workId ? {work:workId} : {}), ...(interactionId ? {interaction:interactionId} : {})})}` : ''}`;
  const workStatus = {PRE_WORK:'正在理解',DRAFT:'待准备',NEEDS_REFINEMENT:'待完善',AWAITING_APPROVAL:'等待你确认',READY:'准备中',RUNNING:'正在生产',NEEDS_ATTENTION:'等待处理',BLOCKED:'暂时受阻',COMPLETED:'已完成',DISCARDED:'已结束'};
  const humanStatus = (raw) => workStatus[raw] || ({ACTIVE:'进行中',PAUSED:'已暂停',ARCHIVED:'已归档'}[raw] || '状态待确认');
  function showNotice(text, error = false) { notice.textContent = text; notice.hidden = false; notice.classList.toggle('notice-error', error); }
  function clearNotice() { notice.hidden = true; notice.textContent = ''; notice.classList.remove('notice-error'); }
  function busy(text = '正在读取最新状态…') { content.innerHTML = `<p class="muted" role="status">${esc(text)}</p>`; }
  function errorView(message) { content.innerHTML = `<section class="detail-panel"><h1>暂时无法读取</h1><p class="muted">${esc(message)}</p><button class="button secondary" data-refresh type="button">重试</button></section>`; }
  async function api(path, options = {}) {
    const { method = 'GET', body, ...rest } = options;
    const response = await fetch(path, {method, credentials:'same-origin', headers: body === undefined ? {} : {'Content-Type':'application/json'}, ...(body === undefined ? {} : {body:JSON.stringify(body)}), ...rest});
    const type = response.headers.get('content-type') || '';
    const value = type.includes('json') ? await response.json() : await response.text();
    if (!response.ok) { const failure = new Error(value.message || value.code || `请求失败 (${response.status})`); failure.status = response.status; failure.code = value.code; throw failure; }
    return value;
  }
  async function auth() { try { state.actor = await api('/auth/session'); state.authenticated = true; } catch (_) { state.actor = null; state.authenticated = false; } $('#account-session-action').textContent = state.authenticated ? '退出登录' : '登录'; }
  function navMark(path) { const key = path === '/' ? 'home' : path.startsWith('/products') ? 'products' : path.startsWith('/works') ? 'works' : path.startsWith('/deliverables') ? 'deliverables' : ''; document.querySelectorAll('[data-nav]').forEach(link => { if (link.dataset.nav === key) link.setAttribute('aria-current','page'); else link.removeAttribute('aria-current'); }); }
  function navigate(path, replace = false) { if (replace) history.replaceState({},'',path); else history.pushState({},'',path); render(); window.scrollTo({top:0,behavior:'instant'}); }
  function link(path, text, className = '') { return `<a href="${href(path)}" data-route class="${className}">${esc(text)}</a>`; }
  function itemList(rows, make) { return rows.length ? `<ul class="item-list">${rows.map(make).join('')}</ul>` : ''; }
  function heading(eyebrow, title, copy = '', action = '') { return `<div class="page-heading"><div><p class="eyebrow">${esc(eyebrow)}</p><h1>${esc(title)}</h1><p>${esc(copy)}</p></div>${action}</div>`; }
  function gate() { const path = `${location.pathname}${location.search}`; sessionStorage.setItem(returnKey,path); content.innerHTML = `<section class="auth-wrap"><p class="eyebrow">继续你的工作</p><h1>先登录 Watt</h1><p class="muted">登录后会回到这里。</p>${link(`/login?next=${encodeURIComponent(path)}`,'前往登录','button')}</section>`; }
  function openDialog(markup) { state.dialogReturn = document.activeElement; dialogContent.innerHTML = `<button type="button" class="dialog-close" data-close-dialog aria-label="关闭">×</button>${markup}`; dialog.hidden = false; document.body.style.overflow = 'hidden'; const focusable = $('input,textarea,button,a', dialogContent); (focusable || dialogContent).focus(); }
  function closeDialog() { dialog.hidden = true; dialogContent.replaceChildren(); document.body.style.overflow = ''; state.dialogReturn?.focus?.(); }
  function loginForm(inModal = false) { return `<form class="login-form auth-card" data-login-form><div class="field"><label for="${inModal ? 'modal-token' : 'page-token'}">登录凭证</label><input id="${inModal ? 'modal-token' : 'page-token'}" name="token" type="password" autocomplete="current-password" required></div><p class="form-error" role="alert" data-login-error></p><button class="button" type="submit">登录</button></form><p class="muted">当前为单一拥有者使用环境。${link('/register','了解注册状态')}</p>`; }
  function openLogin(reason = '保存并继续这件事需要登录。') { sessionStorage.setItem(returnKey, `${location.pathname}${location.search}`); openDialog(`<h2 id="dialog-title">登录 Watt</h2><p class="muted">${esc(reason)}</p>${loginForm(true)}`); }
  async function submitLogin(form) { const button = $('button[type="submit"]',form); const error = $('[data-login-error]',form); button.disabled = true; button.textContent = '正在登录…'; error.textContent = ''; try { await api('/auth/session',{method:'POST',body:{token:form.elements.namedItem('token').value}}); form.elements.namedItem('token').value = ''; await auth(); closeDialog(); const pending = sessionStorage.getItem(pendingKey); if (pending) { sessionStorage.removeItem(pendingKey); navigate('/'); await sendHomeIntent(pending); return; } const next = sessionStorage.getItem(returnKey) || new URLSearchParams(location.search).get('next') || '/'; sessionStorage.removeItem(returnKey); const target = new URL(next, location.origin); navigate(target.origin === location.origin ? target.pathname + target.search : '/'); } catch (failure) { error.textContent = failure.status === 401 ? '登录凭证不正确，请重试。' : '暂时无法登录，请稍后再试。'; } finally { button.disabled = false; button.textContent = '登录'; } }
  function homeCard(title, empty, rows, make, allPath) { return `<section class="summary-list"><div class="section-title"><h2>${esc(title)}</h2>${link(allPath,'查看全部')}</div>${rows.length ? itemList(rows,make) : `<p class="empty">${esc(empty)}</p>`}</section>`; }
  async function renderHome() { let projection = {recent_products:[],active_works:[],attention:[]}; if (state.authenticated) projection = await api('/api/experience/home'); content.innerHTML = `<section class="hero"><p class="eyebrow">你的软件生产入口</p><h1>告诉 Watt，你想继续做什么。</h1><p class="hero-copy">可以继续一个产品、提出新想法，或先问一个问题。Watt 会把需要生产的事带到对应工作区。</p><form class="intent-form" id="home-intent-form"><label for="home-intent">你现在想做什么？</label><textarea id="home-intent" name="intent" placeholder="例如：继续完善易决的小程序分享功能" required></textarea><div class="form-bottom"><span class="form-hint">先从你的话开始，不必填写流程表单。</span><button class="button" type="submit">发送给 Watt <span aria-hidden="true">→</span></button></div></form><div id="intent-result" aria-live="polite"></div></section><div class="home-grid">${homeCard('最近的产品','直接告诉 Watt 你想做什么。',projection.recent_products,p=>`<li>${link(productPath(p.id),p.name,'item-title')}<div class="item-meta">${esc(short(p.description || '持续建设中的产品'))}</div></li>`,'/products')}${homeCard('正在进行','还没有正在进行的具体改变。',projection.active_works,w=>`<li>${link(workspacePath(w.product_id,w.id),w.title,'item-title')}<div class="item-meta">${esc(w.product_name)} · ${esc(humanStatus(w.status))}</div></li>`,'/works')}${homeCard('需要你处理','当前没有需要你处理的事项。',projection.attention,a=>`<li>${link(workspacePath(a.product_id,a.work_id,a.interaction_id),a.work_title,'item-title')}<div class="item-meta">${esc(a.product_name)} · ${esc(short(a.reason))}</div></li>`,'/works')}</div>`; if (state.homeInteraction) await renderHomeConversation(state.homeInteraction); }
  async function sendHomeIntent(text, selectedProductId = null) { const result = $('#intent-result'); if (result) result.innerHTML = '<p class="muted" role="status">Watt 正在理解并保留这句话…</p>'; if (!state.authenticated) { sessionStorage.setItem(pendingKey,text); openLogin(); return; } try { const outcome = await api('/api/experience/intent',{method:'POST',body:{text,...(selectedProductId ? {selected_product_id:selectedProductId} : {})}}); if (outcome.kind === 'CLARIFY') { result.innerHTML = `<div class="detail-panel"><h2>${esc(outcome.question)}</h2><div class="link-row">${outcome.options.map(option=>`<button class="button secondary" type="button" data-choose-product="${esc(option.id)}">${esc(option.name)}</button>`).join('')}</div></div>`; result.dataset.pendingText = text; return; } if (outcome.kind === 'ADVISORY') { state.homeInteraction = outcome.interaction_id; await renderHomeConversation(outcome.interaction_id); return; } state.routeTransition = outcome.transition || `正在继续：${outcome.product.name}`; showNotice(state.routeTransition); setTimeout(()=>navigate(workspacePath(outcome.product.id,null,outcome.interaction_id)),650); } catch (failure) { if (failure.status === 401) { sessionStorage.setItem(pendingKey,text); openLogin(); } else { result.innerHTML = `<p class="notice-error" role="alert">${esc(failure.message)}。这句话仍在输入框中，可以稍后重试。</p>`; $('#home-intent').value = text; } } }
  async function renderHomeConversation(interactionId) { const box = $('#intent-result'); if (!box) return; const data = await api(`/api/experience/interactions/${interactionId}`); box.innerHTML = `<div class="detail-panel"><h2>Watt 的回答</h2>${renderMessages(data.messages)}${data.messages.some(message=>message.actor==='WATT') ? '' : '<p class="muted" role="status">正在根据当前信息回答…</p>'}</div>`; scheduleConversationPoll(interactionId, data, true); }
  function renderMessages(messages) { return `<div class="conversation-list">${messages.length ? messages.map(message=>`<div class="message ${message.actor === 'HUMAN' ? 'human' : 'watt'}"><span class="message-label">${message.actor === 'HUMAN' ? '你' : 'Watt'}</span>${esc(message.content)}</div>`).join('') : '<p class="empty">还没有对话。</p>'}</div>`; }
  function scheduleConversationPoll(interactionId, data, home = false) { if (state.timer) clearTimeout(state.timer); if (data.turns.some(turn=>turn.status === 'RECEIVED' || turn.status === 'PROCESSING')) { const epoch = state.routeEpoch; state.timer = setTimeout(async()=>{ if (epoch !== state.routeEpoch) return; try { if (home) await renderHomeConversation(interactionId); else await renderWorkspace(location.pathname.split('/')[2]); } catch (_) {} },2600); } }
  const collectionInfo = {products:{title:'产品',copy:'长期建设的目标和成果，汇聚在每个产品里。',example:'例如：最近一个月还在开发的产品',empty:'直接告诉 Watt 你想做什么。'},works:{title:'事项',copy:'一次具体改变，从理解到完成都有归属。',example:'例如：易决最近做过什么？',empty:'这个产品还没有开始一次具体的改变。'},deliverables:{title:'交付成果',copy:'完成并验收的软件成果与交付证据。',example:'例如：最近一周发布过的版本',empty:'完成并验收的软件成果会出现在这里。'}};
  function collectionRow(kind,row) { if (kind === 'products') return `<a data-route class="result-row" href="${href(productPath(row.id))}"><div><h2>${esc(row.name)}</h2><p>${esc(short(row.description || '持续建设中的产品'))}</p><p>${esc(row.work_count)} 项事项 · ${esc(row.deliverable_count)} 项交付成果</p></div><span class="status">${esc(humanStatus(row.status))}</span></a>`; if (kind === 'works') return `<a data-route class="result-row" href="${href(workspacePath(row.product_id,row.id))}"><div><h2>${esc(row.title)}</h2><p>${esc(row.product_name)} · ${esc(short(row.requirement))}</p></div><span class="status">${esc(humanStatus(row.status))}</span></a>`; return `<a data-route class="result-row" href="/deliverables/${esc(row.id)}"><div><h2>${esc(row.work_title || row.title)}</h2><p>${esc(row.product_name)} · ${esc(row.created_at?.slice(0,10))}</p></div><span class="status">${row.acceptance === 'ACCEPT' ? '已验收' : row.acceptance ? '需要修改' : '待验收'}</span></a>`; }
  async function renderCollection(kind, queryResult = null) { if (!state.authenticated) return gate(); const info = collectionInfo[kind]; const data = queryResult || await api(`/api/experience/collections/${kind}`); state.lastQuery = {kind, text: queryResult?.text || ''}; content.innerHTML = `${heading('探索',info.title,info.copy)}<form class="query-form" id="collection-query" data-kind="${kind}"><label for="collection-text">用一句话查找${info.title}</label><div class="query-row"><input id="collection-text" name="text" value="${esc(queryResult?.text || '')}" placeholder="${esc(info.example)}"><button class="button" type="submit">查找</button></div><p class="query-help">Watt 将你的问题解释为有边界的查询，结果来自当前产品事实。</p></form><div class="section-title"><h2>${queryResult ? '查询结果' : '全部'}</h2><span class="muted">${data.total} 项</span></div><div class="results">${data.items.length ? data.items.map(row=>collectionRow(kind,row)).join('') : `<p class="empty">${esc(info.empty)}</p>`}</div>`; }
  async function runCollectionQuery(form) { const kind = form.dataset.kind; const text = form.elements.namedItem('text').value.trim(); const button = $('button',form); button.disabled = true; button.textContent = '正在理解…'; try { const data = await api('/api/experience/collections/query',{method:'POST',body:{kind,text}}); await renderCollection(kind,{...data,text}); } catch(failure) { showNotice(failure.message, true); button.disabled=false; button.textContent='查找'; } }
  async function renderProduct(id) { if (!state.authenticated) return gate(); const p = await api(`/api/experience/products/${encodeURIComponent(id)}`); content.innerHTML = `${heading('产品',p.name,p.description || '这个产品承载长期的软件成果。',link(workspacePath(id),'进入工作区','button'))}<div class="detail-grid"><div class="stack"><section class="detail-panel"><h2>当前情况</h2><div class="facts"><div class="fact"><span class="fact-label">产品状态</span><span class="fact-value">${esc(humanStatus(p.status))}</span></div><div class="fact"><span class="fact-label">当前正式版本</span><span class="fact-value">${p.accepted_version == null ? '尚未形成' : `版本 ${esc(p.accepted_version)}`}</span></div><div class="fact"><span class="fact-label">当前事项</span><span class="fact-value">${p.current_work ? link(workspacePath(id,p.current_work.id),p.current_work.title) : '暂无正在进行的事项'}</span></div></div></section><section class="detail-panel"><div class="section-title"><h2>最近的事项</h2>${link('/works','查看全部')}</div>${p.recent_works.length ? itemList(p.recent_works,w=>`<li>${link(workspacePath(id,w.id),w.title,'item-title')}<div class="item-meta">${esc(humanStatus(w.status))}</div></li>`) : '<p class="empty">这个产品还没有开始一次具体的改变。</p>'}</section><section class="detail-panel"><div class="section-title"><h2>最近的交付成果</h2>${link('/deliverables','查看全部')}</div>${p.recent_deliverables.length ? itemList(p.recent_deliverables,d=>`<li>${link(`/deliverables/${d.id}`,d.work_title,'item-title')}<div class="item-meta">${esc(d.created_at?.slice(0,10))}</div></li>`) : '<p class="empty">完成并验收的成果会出现在这里。</p>'}</section></div><div class="stack"><section class="detail-panel"><h2>代码资产</h2><p>${p.accepted_version == null ? '还没有正式来源版本。' : `当前正式版本 ${esc(p.accepted_version)}。`}</p>${link(`${productPath(id)}/code`,'查看代码资产','button secondary')}</section><section class="detail-panel"><h2>产品上下文</h2><p class="muted">这里汇总这个产品长期有效的事实。具体改变在工作区继续。</p><div class="link-row">${link(workspacePath(id),'进入工作区','button secondary')}${link('/works','查看所有事项','button quiet')}${link('/deliverables','查看交付成果','button quiet')}</div></section></div></div>`; }
  function guardianCopy(g) { const status = g?.status || 'NOT_STARTED'; if (status === 'PASS') return `质量检查已通过${g.finding_count ? `；保留 ${g.finding_count} 条历史问题证据` : ''}。`; if (status === 'REPAIR_IN_PROGRESS') return '质量检查发现问题，Watt 正在自动修复。'; if (status === 'REVERIFYING' || status === 'RUNNING') return '质量检查正在重新验证。'; if (status === 'FINDINGS_PRESENT') return `质量检查发现 ${g.finding_count || 1} 个问题，正在处理。`; if (status === 'BLOCKED' || status === 'NON_CONVERGING') return '质量检查暂时受阻，请查看是否需要你提供信息。'; return '尚未开始质量检查。'; }
  function executionCopy(execution) {
    if (!execution) return '尚未进入 Worker 队列';
    return ({QUEUED:'排队中',ASSIGNED:'Worker 已领取',RUNNING:'Worker 正在执行',
      VERIFYING:'正在独立验证',VERIFIED:'独立验证已通过',COMPLETED:'执行和验证已完成',
      RECOVERY_REQUIRED:'正在恢复执行',FAILED:'执行或验证失败',CANCELLED:'执行已取消'})
      [execution.status] || '执行状态待确认';
  }
  function verificationCopy(candidate, execution) {
    const results = candidate?.verification || [];
    if (results.some(item => item.endsWith(': FAIL'))) return '独立验证未通过';
    if (results.length && results.every(item => item.endsWith(': PASS')))
      return `独立验证已通过（${results.length} 项）`;
    if (execution?.recovery_reason === 'VERIFICATION_FAILED') return '独立验证未通过';
    if (execution?.status === 'VERIFYING') return '正在独立验证';
    if (['VERIFIED','COMPLETED'].includes(execution?.status)) return '独立验证已通过';
    return '尚无验证结果';
  }
  function focusCopy(ws) {
    const status=ws.work?.status, guardian=ws.reality.guardian?.status,
      actions=ws.actions.length, execution=ws.reality.execution;
    if(!ws.work)return {now:'等待你描述想做的改变',next:'从对话开始明确当前目标',reason:'这个产品目前没有正在进行的事项。'};
    if(guardian==='REPAIR_IN_PROGRESS'||guardian==='FINDINGS_PRESENT')return {now:'正在修复质量问题',next:'修复后重新验证',reason:guardianCopy(ws.reality.guardian)};
    if(guardian==='REVERIFYING'||guardian==='RUNNING')return {now:'正在验证候选成果',next:'验证完成后更新结果',reason:guardianCopy(ws.reality.guardian)};
    if(actions)return {now:'等待你的决定',next:'请处理「待你处理」中的事项',reason:'当前事项有需要你回答或确认的问题。'};
    if(execution && ['QUEUED','ASSIGNED','RUNNING','VERIFYING','VERIFIED','RECOVERY_REQUIRED','FAILED'].includes(execution.status))
      return {now:executionCopy(execution),next:execution.status==='FAILED'?'查看失败证据并处理阻塞':'Watt 将按当前执行事实继续',reason:execution.recovery_reason || '状态来自当前 Execution 的持久化队列和验证记录。'};
    if(status==='COMPLETED')return {now:'事项已完成',next:ws.reality.deliveries.some(item=>item.current&&!item.acceptance)?'可查看并验收新成果':'成果已记录到产品',reason:'事项已形成可信的生产结果。'};
    if(status==='BLOCKED')return {now:'生产暂时受阻',next:'Watt 将按当前事实继续排查',reason:'当前没有可执行的人工决定。'};
    return {now:humanStatus(status),next:'Watt 将根据当前事项状态继续',reason:'进展来自当前事项的正式生产记录。'};
  }
  function actionText(raw) { return ({APPROVE:'确认',REJECT:'拒绝',REQUEST_REFINEMENT:'要求调整',AUTHORIZE:'授权'})[raw] || '处理'; }
  const attentionLabels = {
    'Admit this governed Work draft?': '确认开始这项工作吗？',
    'Draft generation does not create execution authority.': '确认后 Watt 才能按这项工作继续推进。',
    'Refine this Work before production admission.': '请进一步说明这项工作的范围。',
    'The current Work cannot form a trustworthy single-PWU plan.': '当前信息还不足以形成可靠的执行计划。',
  };
  function renderAttention(a) { const question=a.conversation_prompt||a.decision||a.reason; const detail=a.reason&&a.reason!==question?`<p class="muted">${esc(attentionLabels[a.reason]||a.reason)}</p>`:''; const controls=a.actions.length?a.actions.map(action=>`<button class="button secondary" type="button" data-attention="${esc(a.id)}" data-action="${esc(action)}">${esc(actionText(action))}</button>`).join(''):`<button class="button secondary" type="button" ${a.governed_subject_ref?.startsWith('steering-decision:')?`data-conversation-attention="${esc(a.id)}"`:'data-focus-composer'}>回答这个问题</button>`; return `<div class="action"><h3>${a.actions.length?'需要你决定':'需要你回答'}</h3><p>${esc(attentionLabels[question]||question)}</p>${detail}<div class="link-row">${controls}</div></div>`; }
  const agendaLabels = {
    'Reassess the latest admitted change against existing design and production Reality': '根据最新需求与现有成果重新确认方案',
    'Produce the next exact change admitted from the latest Work Reality': '完成当前确认的产品改动',
    'Assess the new production evidence against the latest Work outcome': '核对新成果是否满足本次目标',
    'Complete the latest admitted Work outcome': '完成本次事项',
    'Prepare the exact design artifact required for the latest admitted change': '补齐本次改动所需的设计成果',
    'Rebuild the exact bounded production direction for the latest admitted Work Reality': '重新明确本次改动的实施方向',
    'Establish the bounded product and solution direction': '明确产品与方案方向',
    'Produce the next exact change admitted from current Reality': '完成当前确认的产品改动',
    'Assess the trusted result against the long-lived outcome': '核对成果是否满足产品目标',
    'Complete the admitted long-lived Work': '完成本次事项',
  };
  function renderWorkspaceAgenda(ws) {
    const outcome = ws.work?.desired_outcome;
    const steps = ws.agenda.map(step => {
      const state = step.state === 'closed' ? '已完成' : step.state === 'current' ? '正在推进' : '待推进';
      const mark = step.state === 'closed' ? '✓' : step.state === 'current' ? '•' : '○';
      return `<li data-agenda-state="${esc(step.state)}"><span class="agenda-dot" aria-hidden="true">${mark}</span><div><span class="agenda-state">${state}</span><p>${esc(agendaLabels[step.title] || step.title)}</p></div></li>`;
    }).join('');
    return `<section class="workspace-quadrant" data-workspace-quadrant="agenda" aria-labelledby="workspace-agenda-title"><div class="quadrant-heading"><p class="eyebrow">01 / 方向</p><h2 id="workspace-agenda-title">计划</h2><p>接下来准备怎么推进？</p></div>${outcome ? `<p class="agenda-outcome"><span>本次目标</span>${esc(outcome)}</p>` : ''}${steps ? `<ol class="workspace-agenda-list">${steps}</ol>` : '<p class="quadrant-empty">Watt 尚未形成可展示的正式计划；确认后会在这里呈现下一步。</p>'}</section>`;
  }
  function renderWorkspaceReality(ws, reviewable, acceptance, workId) {
    const p = ws.product, r = ws.reality, w = ws.work;
    const facts = [
      ['当前事项', w ? humanStatus(w.status) : '尚无具体事项'],
      ['正式版本', p.accepted_version == null ? '尚未形成' : `版本 ${p.accepted_version}`],
      ['执行', w ? executionCopy(r.execution) : '尚无执行'],
      ['验证', verificationCopy(r.candidate, r.execution)],
      ['候选成果', reviewable ? (acceptance ? '已验收' : r.candidate.authorization_pending ? '已形成，等待你授权' : '已形成，可查看') : '尚未形成'],
      ['质量检查', guardianCopy(r.guardian)],
      ['交付成果', r.deliveries.length ? `${r.deliveries.length} 项` : '尚无交付成果'],
    ];
    if (r.cloud_deliverable_id) facts.push(['阿里云部署', r.cloud_deployment ?
      ({SUCCEEDED:'部署成功',FAILED:'部署失败',ROLLED_BACK:'已回滚',NEEDS_HUMAN_ATTENTION:'需要你处理',
        PRECHECK:'检查环境',STAGING:'传送成果',PREPARING:'正在部署',VERIFYING:'正在验证'}[r.cloud_deployment.state] || '等待授权') : '未部署']);
    return `<section class="workspace-quadrant" data-workspace-quadrant="reality" aria-labelledby="workspace-reality-title"><div class="quadrant-heading"><p class="eyebrow">02 / 事实</p><h2 id="workspace-reality-title">现状</h2><p>现在已经成立的事实是什么？</p></div><dl class="workspace-reality-list">${facts.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl><details class="advanced-disclosure workspace-evidence"><summary>查看生产细节与历史证据</summary>${link(`/advanced${workId ? `?work=${workId}` : ''}`,'打开高级信息','button quiet')}</details></section>`;
  }
  function renderWorkspaceActions(ws, candidate, manifest, acceptance, workId, readOnly) {
    const attention = ws.actions.length ? `<div class="action-list">${ws.actions.map(renderAttention).join('')}</div>` : '';
    const review = candidate?.candidate_fingerprint ? `<div class="workspace-review"><h3>${acceptance ? '当前成果已验收' : '查看新版本'}</h3><p>${acceptance ? '可继续查看运行效果与改动。' : '先核对运行效果与改动，再决定是否验收。'}</p><div class="candidate-actions"><button class="button" data-preview="${esc(workId)}" data-preview-manifest="${esc(manifest?.id || '')}" type="button">打开预览</button><button class="button secondary" data-diff="${esc(workId)}" data-fingerprint="${esc(candidate.candidate_fingerprint)}" type="button">查看改动</button>${manifest && !acceptance && !readOnly ? `<button class="button secondary" data-accept="${esc(workId)}" data-manifest="${esc(manifest.id)}" data-manifest-fingerprint="${esc(manifest.fingerprint)}" type="button">验收结果</button>` : ''}${readOnly ? '' : '<button class="button quiet" data-focus-composer type="button">继续修改</button>'}</div>${!manifest && !acceptance ? '<p class="muted">交付物形成后可做正式验收。</p>' : ''}</div>` : '';
    const needsReview = Boolean(candidate?.candidate_fingerprint && !acceptance && !readOnly);
    const cloudAction = ws.reality.cloud_deliverable_id && acceptance?.decision === 'ACCEPT' &&
      ws.reality.cloud_deployment?.state !== 'SUCCEEDED' ?
      `<div class="workspace-review"><h3>阿里云部署</h3><p>${ws.reality.cloud_deployment?.blocker ? esc(window.WattCloudDelivery?.blockerCopy(ws.reality.cloud_deployment) || ws.reality.cloud_deployment.blocker) : '可查看当前部署事实，或为这个已验收版本选择目标 ECS。'}</p>${link(`/deliverables/${ws.reality.cloud_deliverable_id}`,'查看部署','button secondary')}</div>` : '';
    return `<section class="workspace-quadrant" data-workspace-quadrant="actions" aria-labelledby="workspace-actions-title"><div class="quadrant-heading"><p class="eyebrow">03 / 决定</p><h2 id="workspace-actions-title">待你处理</h2><p>Watt 现在真正需要我做什么？</p></div>${attention}${!attention && !needsReview && !cloudAction ? '<p class="quadrant-empty">当前无需你操作</p>' : ''}${review}${cloudAction}</section>`;
  }
  function renderWorkspaceProduction(ws, focus, reviewable, acceptance) {
    const guardian = ws.reality.guardian?.status;
    const repairing = ['FINDINGS_PRESENT','REPAIR_IN_PROGRESS','REVERIFYING'].includes(guardian);
    const result = reviewable ? `<p class="production-result">${esc(acceptance ? '当前成果已验收' : repairing ? 'Watt 正在修复这个版本' : '新版本已经准备好，可以查看。')}</p>` : '';
    return `<section class="workspace-quadrant" data-workspace-quadrant="production" aria-labelledby="workspace-production-title"><div class="quadrant-heading"><p class="eyebrow">04 / 推进</p><h2 id="workspace-production-title">Watt 正在做</h2><p>Watt 当前正在做什么？</p></div><p class="production-current">${esc(focus.now)}</p><p class="production-explanation">${esc(focus.reason)}</p>${result}<div class="production-next"><span>接下来</span><strong>${esc(focus.next)}</strong></div></section>`;
  }
  async function renderWorkspace(id) {
    if (!state.authenticated) return gate();
    const previousComposer = $('#workspace-turn');
    const draft = previousComposer?.value || '';
    const composerFocused = document.activeElement === previousComposer;
    const cursor = composerFocused ? previousComposer.selectionStart : null;
    const params = new URLSearchParams(location.search);
    const workId = params.get('work'), interaction = params.get('interaction');
    const query = new URLSearchParams({...(workId ? {work:workId} : {}),...(interaction ? {interaction} : {})});
    const ws = await api(`/api/experience/products/${encodeURIComponent(id)}/workspace${query.size ? `?${query}` : ''}`);
    const p = ws.product, w = ws.work, r = ws.reality;
    const delivery = r.deliveries.find(entry => entry.current) || r.deliveries[0];
    const manifest = delivery?.manifest, acceptance = delivery?.acceptance, candidate = r.candidate;
    const reviewable = Boolean(candidate?.candidate_fingerprint);
    const readOnly = Boolean(ws.historical && ['COMPLETED','DISCARDED'].includes(w?.status));
    const focus = focusCopy(ws);
    const currentWorkId = w?.work_id;
    content.innerHTML = `<div class="workspace-banner"><p class="eyebrow">产品工作区 ${ws.historical ? '· 历史事项' : ''}</p><h1>${esc(p.name)}</h1><p>${esc(p.description || '持续建设的软件成果。')}${w ? ` · 当前事项：${esc(w.title || w.raw_user_requirement)}` : ''}</p><div class="link-row">${link(productPath(id),'产品概览','button quiet')}${link(`${productPath(id)}/code`,'代码资产','button quiet')}</div></div><div class="workspace-focus-strip"><span>当前焦点</span><strong>${esc(ws.focus?.title || '从你的想法开始')}</strong><span>${esc(focus.now)}</span></div><section class="workspace-quadrants" data-workspace-four-quadrant aria-label="产品工作区四象限">${renderWorkspaceAgenda(ws)}${renderWorkspaceReality(ws,reviewable,acceptance,currentWorkId)}${renderWorkspaceActions(ws,candidate,manifest,acceptance,currentWorkId,readOnly)}${renderWorkspaceProduction(ws,focus,reviewable,acceptance)}</section><section class="workspace-conversation" id="workspace-conversation"><div class="section-title"><h2>和 Watt 一起推进</h2><span class="muted">对话会结合当前产品事实</span></div><div id="workspace-messages" class="conversation-list"><p class="empty">${ws.interaction_id ? '正在读取对话…' : '告诉 Watt 你希望改变什么，或询问当前状态。'}</p></div>${readOnly ? `<p class="quadrant-empty">这是已结束事项的历史记录。${link(workspacePath(id),'回到当前产品工作区继续','button quiet')}</p>` : `<form class="composer" id="workspace-turn-form" data-product="${esc(id)}" data-interaction="${esc(ws.interaction_id || '')}"><label for="workspace-turn">下一句话</label><textarea id="workspace-turn" name="text" placeholder="例如：把客户资料保存问题修好" required></textarea><div class="form-bottom"><span class="form-hint">Watt 会根据产品与事项的真实状态继续。</span><button class="button" type="submit">发送</button></div></form>`}</section>`;
    if (draft && $('#workspace-turn')) {
      $('#workspace-turn').value = draft;
      if (composerFocused) {
        $('#workspace-turn').focus();
        $('#workspace-turn').setSelectionRange(cursor, cursor);
      }
    }
    const conversation = ws.interaction_id ? await renderWorkspaceConversation(ws.interaction_id) : null;
    if (!conversation?.turns.some(turn => turn.status === 'RECEIVED' || turn.status === 'PROCESSING') &&
        !ws.actions.length && ['READY','RUNNING'].includes(w?.status)) {
      const epoch = state.routeEpoch, route = `${location.pathname}${location.search}`;
      state.timer = setTimeout(() => {
        if (epoch === state.routeEpoch && route === `${location.pathname}${location.search}`)
          renderWorkspace(id).catch(failure => showNotice(failure.message, true));
      }, 5000);
    }
  }
  async function renderWorkspaceConversation(id) { const box=$('#workspace-messages'); if(!box)return null; const data=await api(`/api/experience/interactions/${id}`); box.innerHTML = data.messages.length ? data.messages.map(m=>`<div class="message ${m.actor==='HUMAN'?'human':'watt'}"><span class="message-label">${m.actor==='HUMAN'?'你':'Watt'}</span>${esc(m.content)}</div>`).join('') : '<p class="empty">告诉 Watt 你希望改变什么。</p>'; if(data.turns.some(t=>t.status==='RECEIVED'||t.status==='PROCESSING')) box.innerHTML+='<p class="muted" role="status">Watt 正在回应…</p>'; scheduleConversationPoll(id,data); return data; }
  async function submitWorkspaceTurn(form) { const text=form.elements.namedItem('text').value.trim(); if(!text)return; const button=$('button',form); button.disabled=true; button.textContent='正在发送…'; try{const result=await api(`/api/experience/products/${form.dataset.product}/turns`,{method:'POST',body:{text,interaction_id:form.dataset.interaction||null,...(form.dataset.attentionId?{attention_id:form.dataset.attentionId}:{})}}); form.elements.namedItem('text').value=''; if(form.dataset.interaction!==result.interaction_id) navigate(workspacePath(form.dataset.product,null,result.interaction_id),true); else await renderWorkspace(form.dataset.product);}catch(failure){showNotice(failure.message,true);button.disabled=false;button.textContent='发送';} }
  async function renderDeliverable(id) { if(!state.authenticated)return gate();const d=await api(`/api/experience/deliverables/${encodeURIComponent(id)}`);const m=d.manifest,a=d.acceptance,s=d.summary;content.innerHTML=`${heading('交付成果',s.work_title,`${s.product_name} · ${s.created_at?.slice(0,10)}`,link(workspacePath(s.product_id,s.work_id),'回到工作区','button secondary'))}<div class="detail-grid"><div class="stack"><section class="detail-panel"><h2>成果与来源</h2><div class="facts"><div class="fact"><span class="fact-label">产品</span>${link(productPath(s.product_id),s.product_name)}</div><div class="fact"><span class="fact-label">源事项</span>${link(workspacePath(s.product_id,s.work_id),s.work_title)}</div><div class="fact"><span class="fact-label">来源版本</span><span class="fact-value">${esc(short(m.repository_revision,18))}</span></div></div><div class="link-row"><a class="button" href="/api/works/${esc(s.work_id)}/deliveries/${esc(id)}/download">下载交付包</a></div></section><section class="detail-panel"><h2>包含的成果</h2>${m.artifacts?.length ? itemList(m.artifacts,item=>`<li><span class="item-title">${esc(item.path)}</span><span class="item-meta">${esc(item.media_type)} · ${esc(item.size_bytes)} 字节</span></li>`) : '<p class="empty">没有可列出的成果文件。</p>'}</section></div><div class="stack"><section class="detail-panel"><h2>验证与验收</h2><div class="facts"><div class="fact"><span class="fact-label">机器验证</span><span class="fact-value">${m.verification_record_ids?.length ? `${m.verification_record_ids.length} 条验证记录` : '尚无可显示的验证记录'}</span></div><div class="fact"><span class="fact-label">质量检查</span><span class="fact-value">${esc(guardianCopy(d.guardian))}</span></div><div class="fact"><span class="fact-label">人工验收</span><span class="fact-value">${a ? (a.decision==='ACCEPT'?'已接受':'要求修改') : '尚待决定'}</span></div><div class="fact"><span class="fact-label">部署</span><span class="fact-value">${s.deployed||d.cloud_deployments?.some(item=>item.state==='SUCCEEDED')?'已有运行记录':'没有部署记录'}</span></div></div>${!a ? `<div class="link-row"><button class="button" type="button" data-accept="${esc(s.work_id)}" data-manifest="${esc(id)}" data-manifest-fingerprint="${esc(m.fingerprint)}">验收成果</button></div>` : ''}</section><details class="detail-panel advanced-disclosure"><summary>查看精确证据</summary><p>来源身份：${esc(m.repository_identity)}</p><p>版本：${esc(m.repository_revision)}</p><p>交付指纹：${esc(m.fingerprint)}</p><p>验证记录：${esc(m.verification_record_ids?.join(', ') || '无')}</p></details></div></div>`; window.WattCloudDelivery?.render(d); }
  async function renderCode(id) { if(!state.authenticated)return gate();const product=await api(`/api/experience/products/${encodeURIComponent(id)}`);const revision=new URLSearchParams(location.search).get('revision');let source=null,files=null,error=null;try{source=await api(`/api/products/${encodeURIComponent(id)}/code-assets`);files=await api(`/api/products/${encodeURIComponent(id)}/code-assets/files${revision ? `?${new URLSearchParams({revision})}` : ''}`);}catch(failure){error=failure.message;}content.innerHTML=`${heading('代码资产',product.name,'正式来源、候选改动和版本历史都属于这个产品。',link(productPath(id),'回到产品','button secondary'))}${error?`<section class="detail-panel"><p class="empty">${esc(error)}。这个产品还没有可查看的托管代码资产。</p></section>`:`<div class="detail-grid"><div class="stack"><section class="detail-panel"><h2>版本</h2><div class="facts"><div class="fact"><span class="fact-label">当前正式版本</span><span class="fact-value">版本 ${esc(source.accepted.version)}</span></div><div class="fact"><span class="fact-label">正在查看</span><span class="fact-value">${esc(source.versions.find(v=>v.revision===files.revision)?.version ?? '候选版本')}</span></div><div class="fact"><span class="fact-label">待查看版本</span><span class="fact-value">${source.current_candidate ? '有新的候选改动' : '暂无新的候选改动'}</span></div></div><div class="link-row"><a class="button" href="/api/products/${esc(id)}/code-assets/export${revision ? `?${new URLSearchParams({revision})}` : ''}">导出所看版本</a></div></section><section class="detail-panel"><h2>文件</h2><div class="code-files">${files.files.length?files.files.map(path=>`<button type="button" data-code-file="${esc(path)}" data-product="${esc(id)}">${esc(path)}</button>`).join(''):'<p class="empty">此版本暂无文件。</p>'}</div></section><section class="detail-panel"><h2>版本历史</h2>${itemList(source.versions.slice().reverse().slice(0,20),v=>`<li><button class="button quiet" type="button" data-code-version="${esc(v.revision)}" data-product="${esc(id)}" ${v.revision===files.revision?'aria-current="true"':''}>版本 ${esc(v.version)}</button>${v.work_id?`<div class="item-meta">源事项：${link(workspacePath(id,v.work_id),'查看工作区')}</div>`:''}</li>`)}</section></div><div class="stack"><section class="detail-panel"><h2>文件内容</h2><pre id="code-content" class="code-view">选择一个文件查看内容。</pre></section><section class="detail-panel"><h2>此版本改动</h2>${files.changed_files.length?itemList(files.changed_files.map(path=>({path})),item=>`<li>${esc(item.path)}</li>`):'<p class="empty">当前版本没有相对上一版本的改动。</p>'}<details class="advanced-disclosure"><summary>查看精确差异</summary><pre class="code-view">${esc(files.diff || '没有差异。')}</pre></details></section><details class="detail-panel advanced-disclosure"><summary>外部来源与技术信息</summary><p>提供方：${esc(source.provider_kind)}</p><p>来源：${esc(JSON.stringify(source.origin || {}))}</p><p>正式提交：${esc(source.accepted.revision)}</p><p>树：${esc(source.accepted.tree)}</p><p>访问入口：${esc(source.access?.url || '未提供')}</p></details></div></div>`}`; }
  async function renderUser() { if(!state.authenticated)return gate();content.innerHTML=`${heading('账户','我的账户','当前 Watt 使用单一拥有者身份边界。')}<section class="detail-panel" style="max-width:660px"><div class="facts"><div class="fact"><span class="fact-label">当前身份</span><span class="fact-value">${esc(state.actor?.actor_id || '未登录')}</span></div><div class="fact"><span class="fact-label">所属上下文</span><span class="fact-value">${esc(state.actor?.organization_id || '未提供')}</span></div><div class="fact"><span class="fact-label">会话</span><span class="fact-value">已通过 Watt 的真实登录会话验证</span></div></div><div class="link-row"><button class="button secondary" type="button" data-logout>退出登录</button></div></section>`; }
  function renderSettings() { const theme=document.documentElement.dataset.theme||'light';content.innerHTML=`${heading('设置','偏好设置','这里只提供当前真正生效的个人设置。')}<section class="detail-panel" style="max-width:660px"><h2>外观</h2><div class="field"><label for="theme-setting">界面主题</label><select id="theme-setting"><option value="light" ${theme==='light'?'selected':''}>浅色</option><option value="dark" ${theme==='dark'?'selected':''}>深色</option></select></div><p class="muted">仅保存在这台浏览器。账户与安全信息在${link('/user','我的账户')}中查看。</p></section>`; }
  function renderLogin() { const next=new URLSearchParams(location.search).get('next');content.innerHTML=`<section class="auth-wrap"><p class="eyebrow">欢迎回来</p><h1>登录 Watt</h1><p class="muted">回到你正在进行的产品与事项。</p>${loginForm(false)}${next?`<p class="muted">登录后返回此前打开的页面。</p>`:''}</section>`; }
  function renderRegister() { content.innerHTML=`<section class="auth-wrap"><p class="eyebrow">账户</p><h1>注册 Watt</h1><div class="auth-card"><p class="prose">当前部署面向单一拥有者，尚未开放自助注册。已有访问凭证的拥有者可以直接登录。</p>${link('/login','前往登录','button')}</div></section>`; }
  async function render() { if(state.timer){clearTimeout(state.timer);state.timer=null;} const epoch=++state.routeEpoch,path=location.pathname;navMark(path);clearNotice();busy();try{await auth();if(epoch!==state.routeEpoch)return;$('#connection-status').textContent=state.authenticated?'已连接当前账户':'未登录';if(path==='/'||path==='/app')await renderHome();else if(path==='/products')await renderCollection('products');else if(path==='/works')await renderCollection('works');else if(path==='/deliverables')await renderCollection('deliverables');else if(/^\/products\/[^/]+\/workspace$/.test(path))await renderWorkspace(path.split('/')[2]);else if(/^\/products\/[^/]+\/code$/.test(path))await renderCode(path.split('/')[2]);else if(/^\/products\/[^/]+$/.test(path))await renderProduct(path.split('/')[2]);else if(/^\/deliverables\/[^/]+$/.test(path))await renderDeliverable(path.split('/')[2]);else if(path==='/user')await renderUser();else if(path==='/settings')renderSettings();else if(path==='/login')renderLogin();else if(path==='/register')renderRegister();else errorView('这个页面不存在。');if(state.routeTransition && path.includes('/workspace')){showNotice(state.routeTransition);state.routeTransition=null;}}catch(failure){if(failure.status===401){state.authenticated=false;gate();}else errorView(failure.message);} }
  async function openPreview(workId,manifestId) { try { const info=manifestId?await api(`/api/works/${workId}/deliveries/${manifestId}/runtime`,{method:'POST'}):await api(`/api/works/${workId}/candidate-preview`,{method:'POST'});if(info.url){window.open(info.url,'_blank','noopener');}else showNotice(info.reason||'当前版本尚无可打开的预览。',true);}catch(failure){showNotice(failure.message,true);} }
  async function openDiff(workId,fingerprint) { try { const response=await fetch(`/api/works/${workId}/candidate-code-diff/${fingerprint}`,{credentials:'same-origin'});if(!response.ok)throw new Error('暂时无法读取改动。');const diff=await response.text();openDialog(`<h2 id="dialog-title">这次改动</h2><pre class="code-view">${esc(short(diff,500000))}</pre>`);}catch(failure){showNotice(failure.message,true);} }
  function openAcceptance(workId,manifestId,fingerprint) { openDialog(`<h2 id="dialog-title">验收这个成果</h2><p class="muted">人工验收独立于机器质量检查。请先查看预览与改动。</p><form id="acceptance-form" data-work="${esc(workId)}" data-manifest="${esc(manifestId)}" data-fingerprint="${esc(fingerprint)}"><div class="field"><label for="acceptance-rationale">决定依据</label><input id="acceptance-rationale" name="rationale" required placeholder="例如：功能满足本次目标"></div><div class="link-row"><button class="button" type="submit" value="ACCEPT">接受</button><button class="button secondary" type="submit" value="REQUEST_CHANGES">继续修改</button></div><p class="form-error" role="alert"></p></form>`); }
  async function accept(form, decision) { const button=form.querySelector(`button[value="${decision}"]`);button.disabled=true;try{await api(`/api/works/${form.dataset.work}/deliveries/${form.dataset.manifest}/acceptance`,{method:'POST',body:{manifest_fingerprint:form.dataset.fingerprint,decision,authority_identity:'human:owner',rationale:form.elements.namedItem('rationale').value.trim()}});closeDialog();showNotice(decision==='ACCEPT'?'已记录你的验收决定。':'已记录你的修改要求。');await render();}catch(failure){$('.form-error',form).textContent=failure.message;}finally{button.disabled=false;} }
  async function showCodeFile(productId,path) { const box=$('#code-content');if(!box)return;box.textContent='正在读取文件…';try{const data=await api(`/api/products/${productId}/code-assets/file?${new URLSearchParams({path,...(new URLSearchParams(location.search).get('revision') ? {revision:new URLSearchParams(location.search).get('revision')} : {})})}`);box.textContent=data.content??'此文件不是可安全展示的文本。';document.querySelectorAll('[data-code-file]').forEach(button=>button.setAttribute('aria-current',String(button.dataset.codeFile===path)));}catch(failure){box.textContent=failure.message;} }
  document.addEventListener('click',async event=>{const route=event.target.closest('a[data-route]');if(route&&route.origin===location.origin){event.preventDefault();navigate(route.pathname+route.search);return;}if(event.target.closest('[data-close-dialog]')){closeDialog();return;}const target=event.target.closest('button');if(!target)return;if(target.id==='account-button'){const menu=$('#account-menu');menu.hidden=!menu.hidden;target.setAttribute('aria-expanded',String(!menu.hidden));return;}if(target.id==='account-session-action'){ $('#account-menu').hidden=true; if(state.authenticated){await api('/auth/logout',{method:'POST'});await auth();navigate('/');}else navigate('/login');return;}if(target.hasAttribute('data-refresh')){render();return;}if(target.dataset.chooseProduct){const pending=$('#intent-result')?.dataset.pendingText||$('#home-intent')?.value||'';await sendHomeIntent(pending,target.dataset.chooseProduct);return;}if(target.dataset.preview){await openPreview(target.dataset.preview,target.dataset.previewManifest||null);return;}if(target.dataset.diff){await openDiff(target.dataset.diff,target.dataset.fingerprint);return;}if(target.dataset.accept){openAcceptance(target.dataset.accept,target.dataset.manifest,target.dataset.manifestFingerprint);return;}if(target.dataset.conversationAttention){const form=$('#workspace-turn-form');form.dataset.attentionId=target.dataset.conversationAttention;$('#workspace-turn')?.focus();return;}if(target.hasAttribute('data-focus-composer')){const form=$('#workspace-turn-form');if(form)delete form.dataset.attentionId;$('#workspace-turn')?.focus();return;}if(target.dataset.attention){try{await api(`/api/attention/${target.dataset.attention}/resolve`,{method:'POST',body:{action:target.dataset.action,authority_identity:'human:owner'}});showNotice('已记录你的决定。');await render();}catch(failure){showNotice(failure.message,true);}return;}if(target.dataset.codeFile){await showCodeFile(target.dataset.product,target.dataset.codeFile);return;}if(target.dataset.codeVersion){navigate(`${productPath(target.dataset.product)}/code?revision=${encodeURIComponent(target.dataset.codeVersion)}`);return;}if(target.hasAttribute('data-logout')){await api('/auth/logout',{method:'POST'});await auth();navigate('/');return;} });
  document.addEventListener('submit',async event=>{const form=event.target;if(form.matches('[data-login-form]')){event.preventDefault();await submitLogin(form);}else if(form.id==='home-intent-form'){event.preventDefault();await sendHomeIntent(form.elements.namedItem('intent').value.trim());}else if(form.id==='collection-query'){event.preventDefault();await runCollectionQuery(form);}else if(form.id==='workspace-turn-form'){event.preventDefault();await submitWorkspaceTurn(form);}else if(form.id==='acceptance-form'){event.preventDefault();await accept(form,event.submitter?.value||'ACCEPT');}});
  document.addEventListener('change',event=>{if(event.target.id==='theme-setting'){const theme=event.target.value;document.documentElement.dataset.theme=theme;localStorage.setItem('watt:theme',theme);}});
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!dialog.hidden)closeDialog();if(event.key==='Tab'&&!dialog.hidden){const focusable=[...dialogContent.querySelectorAll('a,button,input,textarea,select')].filter(item=>!item.disabled);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
  window.addEventListener('popstate',render);
  window.addEventListener('focus',()=>{if(state.authenticated&&dialog.hidden)render();});
  try{document.documentElement.dataset.theme=localStorage.getItem('watt:theme')==='dark'?'dark':'light';}catch(_){document.documentElement.dataset.theme='light';}
  render();
})();
