import { FormEvent, ReactNode, useEffect, useLayoutEffect, useMemo, useReducer, useRef, useState } from "react";
import { getPack, getScene, scenarioPacks } from "./scenarios";
import { initialInteraction, interactionReducer, transitionMotion, type CurrentInteraction } from "./interactionModel";
import { DEFAULT_WORKS, WORKSPACE_LABELS, WORKSPACE_SURFACE_IDS, assignHumanGroup, assignSemanticGroup, projectWorkspace, splitWorkHistory, togglePinned, workspaceMode, workspacePlacements, workspaceSummary, type WorkNavItem, type WorkspaceFunction } from "./workspaceModel";
import type { Message, Milestone, ResultFact, ScenarioPack, Scene, Surface, Transition } from "./types";

type IconName = "home" | "work" | "delivery" | "spark" | "check" | "clock" | "arrow" | "chevron" | "close" | "sliders" | "layers" | "shield" | "asset" | "message" | "play" | "refresh" | "info" | "pause" | "search" | "pin" | "history" | "focus" | "settings" | "user";
const icons: Record<IconName, ReactNode> = {
  home:<><path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10v10h13V10"/></>, work:<><rect x="3" y="5" width="18" height="15" rx="3"/><path d="M8 5V3h8v2M3 11h18"/></>, delivery:<><path d="M5 8h14l1 12H4L5 8Z"/><path d="M9 8V5a3 3 0 0 1 6 0v3"/></>,
  spark:<><path d="m12 3 1.5 5.5L19 10l-5.5 1.5L12 17l-1.5-5.5L5 10l5.5-1.5L12 3Z"/><path d="m19 16 .7 2.3L22 19l-2.3.7L19 22l-.7-2.3L16 19l2.3-.7L19 16Z"/></>, check:<path d="m5 12 4 4L19 6"/>, clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>, arrow:<><path d="M5 12h14"/><path d="m14 7 5 5-5 5"/></>, chevron:<path d="m9 18 6-6-6-6"/>, close:<><path d="m6 6 12 12M18 6 6 18"/></>,
  sliders:<><path d="M4 7h10M18 7h2M4 17h2M10 17h10"/><circle cx="16" cy="7" r="2"/><circle cx="8" cy="17" r="2"/></>, layers:<><path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 16l9 5 9-5"/></>, shield:<><path d="M12 3 5 6v5c0 4.6 2.8 8.2 7 10 4.2-1.8 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></>, asset:<><path d="M4 4h6l2 3h8v13H4V4Z"/><path d="M4 9h16"/></>, message:<path d="M4 5h16v11H9l-5 4V5Z"/>, play:<path d="m9 6 9 6-9 6V6Z"/>,
  refresh:<><path d="M20 7v5h-5M4 17v-5h5"/><path d="M18 12a6 6 0 0 0-10.3-4.2L4 12M6 12a6 6 0 0 0 10.3 4.2L20 12"/></>, info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></>, pause:<path d="M9 7v10M15 7v10"/>, search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, pin:<><path d="m9 4h6l1 6 3 3H5l3-3 1-6ZM12 13v8"/></>, history:<><path d="M3 12a9 9 0 1 0 3-6.7L3 8M3 3v5h5M12 7v5l3 2"/></>, focus:<path d="M8 3H3v5M16 3h5v5M8 21H3v-5M16 21h5v-5"/>, settings:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></>, user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>
};
function Icon({name,size=18}:{name:IconName;size?:number}){return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{icons[name]}</svg>}

const nav:Record<Surface,{label:string;icon:IconName}>={home:{label:"首页",icon:"home"},work:{label:"Work",icon:"work"},deliveries:{label:"交付",icon:"delivery"}};
const phase:Record<Scene["phase"],string>={PRE_WORK:"尚未形成 Work",REFINING:"正在理解",READY_FOR_WORK:"目标待确认",DESIGNING:"正在形成方案",PLANNING:"准备生产",QUEUED:"已就绪",WAITING_FOR_CAPACITY:"等待生产容量",RUNNING:"正在生产",CHECKPOINTED:"进展已保存",PAUSED:"已暂停",RECOVERING:"正在恢复",WAITING_FOR_HUMAN:"需要你的决定",VERIFYING:"正在验证",RESULT_READY:"结果已就绪",READY_FOR_AUTHORIZATION:"结果待审阅",AUTHORIZED:"已授权",DELIVERED:"已交付",COMPLETED:"当前目标已完成",REOPENED:"继续细化"};

interface State{packId:string;sceneId:string;surface:Surface;reviewer:boolean;drawer:"production"|"evidence"|null;preview:boolean;focus:WorkspaceFunction|null;historyCollapsed:boolean;composerExpanded:boolean}
type Action={type:"pack";pack:ScenarioPack}|{type:"scene";pack:ScenarioPack;scene:Scene}|{type:"move";pack:ScenarioPack;to:string}|{type:"surface";surface:Surface}|{type:"reset";pack:ScenarioPack}|{type:"reviewer"|"history"|"composer"|"preview"}|{type:"drawer";value:State["drawer"]}|{type:"focus";value:WorkspaceFunction|null};
function readHash(){const p=new URLSearchParams(location.hash.slice(1));return{pack:p.get("pack")??"P01",scene:p.get("scene")}}
function initialState():State{const h=readHash(),p=getPack(h.pack),s=getScene(p,h.scene??p.seed);return{packId:p.id,sceneId:s.id,surface:s.surface,reviewer:false,drawer:null,preview:s.id.endsWith("preview"),focus:null,historyCollapsed:false,composerExpanded:s.id==="p01-home"}}
function reducer(s:State,a:Action):State{switch(a.type){case"pack":{const x=getScene(a.pack,a.pack.seed);return{...s,packId:a.pack.id,sceneId:x.id,surface:x.surface,focus:null,drawer:null,preview:false,composerExpanded:x.id==="p01-home"}}case"scene":return{...s,packId:a.pack.id,sceneId:a.scene.id,surface:a.scene.surface,focus:null,drawer:null,preview:a.scene.id.endsWith("preview"),composerExpanded:a.scene.id==="p01-home"};case"move":{const x=getScene(a.pack,a.to);return{...s,sceneId:x.id,surface:x.surface,drawer:null,preview:x.id.endsWith("preview")}}case"surface":return{...s,surface:a.surface};case"reset":{const x=getScene(a.pack,a.pack.seed);return{...s,sceneId:x.id,surface:x.surface,focus:null,drawer:null,preview:false,composerExpanded:x.id==="p01-home"}}case"reviewer":return{...s,reviewer:!s.reviewer};case"history":return{...s,historyCollapsed:!s.historyCollapsed};case"composer":return{...s,composerExpanded:!s.composerExpanded};case"preview":return{...s,preview:!s.preview};case"drawer":return{...s,drawer:a.value};case"focus":return{...s,focus:a.value}}}

function sceneInteraction(s:Scene):{history:Message[];seed?:Partial<CurrentInteraction>}{
  if(s.id==="p07-running")return{history:[],seed:{id:1,phase:"complete",humanTurn:s.messages?.[0]?.text,wattReply:s.messages?.[1]?.text,visibleReply:s.messages?.[1]?.text??"",realityEffect:"当前活动模板正在停在安全位置；新的后台目标等待治理。"}};
  if(s.id==="p14-stream")return{history:s.messages?.slice(0,2)??[],seed:{id:1,phase:"streaming",humanTurn:s.messages?.[2]?.text,wattReply:"会纳入。直播回放应作为核心内容资产，短视频切片和图文摘要作为衍生版本，这样复用和归因都更清楚。",visibleReply:"我正在把这项补充放回当前内容模型里…",realityEffect:"Agenda 已加入直播回放二次剪辑。"}};
  return{history:s.messages??[]}
}
function responseFor(text:string,s:Scene){if(/暂停|停一下/.test(text))return{reply:"已收到暂停请求。当前生产还没有被立即中断；Watt 正在让进行中的操作到达安全位置，确认后会把状态更新为“已暂停”。",effect:"生产正在前往安全暂停点，当前仍保持可恢复。"};if(/登录|跳转/.test(text))return{reply:"已收到。我理解为你正在修改当前 Work 的登录后导航约束。我已把它加入当前情况，并调整接下来的设计检查；如果生产已覆盖这部分，我会先在安全位置停下再应用。",effect:"新增约束：登录后保留当前位置，不自动跳转。"};if(/不对|纠正|不是/.test(text))return{reply:"明白，我会采用你的新表述，不为之前的理解辩解。相关事实已经更新；正在进行的工作会先停在安全位置，再按修订后的目标继续。",effect:"目标理解已按最新纠正更新，旧方向停止扩展。"};if(s.attention?.contract==="decision")return{reply:`已收到。这个输入涉及“${s.attention.title}”。我会保留你的原话并核对影响，在需要你授权之前不会替你作决定。`,effect:"新的输入已进入影响核对，原决定边界保持不变。"};return{reply:"已收到。我会把这项补充和当前 Work 的目标、约束与进展一起判断。它会先进入当前情况和接下来；如果影响生产或权限边界，我会明确告诉你何时生效。",effect:"当前情况已记录这项补充，接下来会据此调整。"}}

export function App(){
  const[state,dispatch]=useReducer(reducer,undefined,initialState),pack=useMemo(()=>getPack(state.packId),[state.packId]),scene=useMemo(()=>getScene(pack,state.sceneId),[pack,state.sceneId]),projection=projectWorkspace(scene,state.focus);
  const[works,setWorks]=useState<WorkNavItem[]>(()=>{const saved=localStorage.getItem("watt-prototype-v2-work-nav");return saved?JSON.parse(saved):DEFAULT_WORKS.map(assignSemanticGroup)}),[interaction,interact]=useReducer(interactionReducer,undefined,()=>initialInteraction(sceneInteraction(scene).history)),[realityNote,setRealityNote]=useState(""),[archiving,setArchiving]=useState(false),[toast,setToast]=useState("");
  const timer=useRef<number|undefined>(undefined),reduceMotion=matchMedia("(prefers-reduced-motion: reduce)").matches;
  useEffect(()=>{const h=`pack=${pack.id}&scene=${scene.id}`;if(location.hash.slice(1)!==h)history.replaceState(null,"",`#${h}`)},[pack.id,scene.id]);
  useEffect(()=>{const fn=()=>{const h=readHash(),p=getPack(h.pack);dispatch({type:"scene",pack:p,scene:getScene(p,h.scene??p.seed)})};addEventListener("hashchange",fn);return()=>removeEventListener("hashchange",fn)},[]);
  useEffect(()=>{const x=sceneInteraction(scene);interact({type:"reset",history:x.history,seed:x.seed});setRealityNote("");setArchiving(false)},[scene.id]);
  useEffect(()=>localStorage.setItem("watt-prototype-v2-work-nav",JSON.stringify(works)),[works]);
  useEffect(()=>{if(interaction.phase==="received"){const id=setTimeout(()=>interact({type:"start"}),240);return()=>clearTimeout(id)}if(interaction.phase!=="streaming"||!interaction.wattReply)return;let n=interaction.visibleReply.length;timer.current=setInterval(()=>{n+=3;if(n>=interaction.wattReply!.length){clearInterval(timer.current);interact({type:"complete"})}else interact({type:"reveal",length:n})},reduceMotion?1:32);return()=>clearInterval(timer.current)},[interaction.id,interaction.phase,interaction.wattReply,reduceMotion]);
  useEffect(()=>{if(interaction.phase==="complete"&&interaction.realityEffect)setRealityNote(interaction.realityEffect)},[interaction.phase,interaction.realityEffect]);
  useEffect(()=>{if(interaction.phase!=="complete"||interaction.readingProtected){setArchiving(false);return}const id=setTimeout(()=>{if(reduceMotion)interact({type:"archive"});else{setArchiving(true);setTimeout(()=>{interact({type:"archive"});setArchiving(false)},320)}},5200);return()=>clearTimeout(id)},[interaction.phase,interaction.readingProtected,reduceMotion]);
  const move=(t:Transition)=>{dispatch({type:"move",pack,to:t.to});setToast(t.hint??"模拟状态已推进");setTimeout(()=>setToast(""),1600)},submit=(text:string)=>{const r=responseFor(text,scene);interact({type:"submit",text,reply:r.reply,realityEffect:r.effect});if(!state.composerExpanded)dispatch({type:"composer"})};
  const selectWork=(w:WorkNavItem)=>{const target=w.id==="feedback"?["P05","p05-wait"]:w.id==="invite"?["P12","p12-context"]:w.historical?["P11","p11-delivery"]:[pack.id,scene.workName?scene.id:"p01-admitted"],p=getPack(target[0]);dispatch({type:"scene",pack:p,scene:getScene(p,target[1])})};
  const dockOpen=state.composerExpanded||Boolean(interaction.humanTurn);
  return <div className={`app v2-app ${state.historyCollapsed?"history-collapsed":""}`}><Topbar surface={state.surface} onSurface={surface=>dispatch({type:"surface",surface})} onReview={()=>dispatch({type:"reviewer"})}/><main className="v2-shell"><WorkNavigator works={works} selected={scene.workName??""} onSelect={selectWork} onPin={id=>setWorks(xs=>xs.map(x=>x.id===id?togglePinned(x):x))} onGroup={(id,label)=>setWorks(xs=>xs.map(x=>x.id===id?assignHumanGroup(x,label):x))}/><section className="workspace-stage">{state.surface==="home"&&<HomeView scene={scene} pack={pack} onMove={move} onWork={()=>dispatch({type:"surface",surface:"work"})}/>} {state.surface==="work"&&<AdaptiveWorkView scene={scene} pack={pack} projection={projection} realityNote={realityNote} onFocus={value=>dispatch({type:"focus",value})} onMove={move} onPreview={()=>dispatch({type:"preview"})} onEvidence={()=>dispatch({type:"drawer",value:"evidence"})} onProduction={()=>dispatch({type:"drawer",value:"production"})}/>} {state.surface==="deliveries"&&<DeliveryView scene={scene} onMove={move} onWork={()=>dispatch({type:"surface",surface:"work"})}/>} {dockOpen&&<div className="interaction-dock"><CurrentInteractionSurface value={interaction} archiving={archiving} reducedMotion={reduceMotion} onProtect={value=>interact({type:"protect-reading",value})} onExpand={()=>interact({type:"toggle-expanded"})}/><Composer expanded onSend={submit} onCollapse={state.composerExpanded?()=>dispatch({type:"composer"}):undefined}/></div>}</section><ConversationHistory value={interaction} collapsed={state.historyCollapsed} composerExpanded={dockOpen} onToggle={()=>dispatch({type:"history"})} onExpandComposer={()=>dispatch({type:"composer"})} onSend={submit}/></main><span className="simulation-badge"><span/>Watt Experience Prototype v2.1 — simulated data</span>
  {state.drawer==="production"&&<InfoDrawer title="生产详情" onClose={()=>dispatch({type:"drawer",value:null})}><ProductionContent scene={scene}/></InfoDrawer>}{state.drawer==="evidence"&&<InfoDrawer title="事实来源与工程详情" onClose={()=>dispatch({type:"drawer",value:null})}><div className="owner-list">{Object.entries(scene.ownerFacts).map(([k,v])=><div key={k}><strong>{k}</strong><p>{v}</p></div>)}</div><p className="simulation-note">这些是体验验证用的 owner-specific mock facts，不代表生产能力。</p></InfoDrawer>}{state.preview&&scene.result&&<PreviewOverlay result={scene.result} onClose={()=>dispatch({type:"preview"})}/>} {state.reviewer&&<ReviewerPanel pack={pack} scene={scene} projection={projection} focus={projection.focused} interaction={interaction} selectedWork={works.find(w=>scene.workName?.includes(w.name))??works[0]} onClose={()=>dispatch({type:"reviewer"})} onPack={p=>dispatch({type:"pack",pack:p})} onScene={s=>dispatch({type:"scene",pack,scene:s})} onReset={()=>dispatch({type:"reset",pack})} onAdvance={()=>scene.transitions[0]&&move(scene.transitions[0])}/>} {toast&&<div className="toast"><Icon name="check" size={14}/>{toast}</div>}</div>
}

function Topbar({surface,onSurface,onReview}:{surface:Surface;onSurface:(s:Surface)=>void;onReview:()=>void}){return <header className="topbar"><button className="brand" onClick={()=>onSurface("home")}><span className="brand-mark"><Icon name="spark" size={17}/></span><span>Watt</span></button><nav className="primary-nav" aria-label="主导航">{(Object.keys(nav)as Surface[]).map(s=><button key={s} className={surface===s?"active":""} onClick={()=>onSurface(s)}><Icon name={nav[s].icon} size={15}/>{nav[s].label}</button>)}</nav><div className="top-actions"><button className="icon-button" onClick={onReview} aria-label="打开评审模式"><Icon name="sliders"/></button></div></header>}

function WorkNavigator({works,selected,onSelect,onPin,onGroup}:{works:WorkNavItem[];selected:string;onSelect:(w:WorkNavItem)=>void;onPin:(id:string)=>void;onGroup:(id:string,label:string)=>void}){const[q,setQ]=useState(""),[past,setPast]=useState(false),[closed,setClosed]=useState<string[]>([]),split=splitWorkHistory(works),filtered=(past?split.historical:split.active).filter(w=>(w.name+w.outcome).toLowerCase().includes(q.toLowerCase())),pinned=filtered.filter(w=>w.pinned),groups=filtered.filter(w=>!w.pinned).reduce<Record<string,WorkNavItem[]>>((a,w)=>{(a[w.groupLabel||"其他"]??=[]).push(w);return a},{});const card=(w:WorkNavItem)=><article draggable onDragStart={e=>e.dataTransfer.setData("text/work-id",w.id)} key={w.id} className={`work-nav-item ${selected.includes(w.name)?"selected":""}`} onClick={()=>onSelect(w)}><div><strong>{w.name}</strong><span>{w.status}</span></div><button onClick={e=>{e.stopPropagation();onPin(w.id)}} aria-label={`${w.pinned?"取消置顶":"置顶"}${w.name}`}><Icon name="pin" size={12}/></button>{selected.includes(w.name)&&<label onClick={e=>e.stopPropagation()}>分组<select value={w.groupLabel} onChange={e=>onGroup(w.id,e.target.value)}><option>推广与增长</option><option>产品体验</option><option>团队能力</option><option>我关心的工作</option><option>其他</option></select></label>}</article>;return <aside className="work-nav"><div className="work-nav-head"><span>我的 Work</span><strong>让结果持续向前</strong></div><label className="work-search"><Icon name="search" size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索 Work" aria-label="搜索 Work"/></label><div className="work-tabs"><button className={!past?"active":""} onClick={()=>setPast(false)}>当前</button><button className={past?"active":""} onClick={()=>setPast(true)}>历史工作项</button></div><div className="work-groups">{pinned.length>0&&<WorkGroup label="置顶" closed={closed.includes("置顶")} onToggle={()=>setClosed(xs=>xs.includes("置顶")?xs.filter(x=>x!=="置顶"):[...xs,"置顶"])} onDrop={onPin}>{pinned.map(card)}</WorkGroup>}{Object.entries(groups).map(([label,items])=><WorkGroup key={label} label={label} badge={items[0]?.groupSource==="human"?"我的分组":items[0]?.groupSource==="ai"?"Watt 归类":""} closed={closed.includes(label)} onToggle={()=>setClosed(xs=>xs.includes(label)?xs.filter(x=>x!==label):[...xs,label])} onDrop={id=>onGroup(id,label)}>{items.map(card)}</WorkGroup>)}</div><div className="nav-global"><button><Icon name="user" size={14}/>账户</button><button><Icon name="settings" size={14}/>设置</button></div></aside>}
function WorkGroup({label,badge,closed,onToggle,onDrop,children}:{label:string;badge?:string;closed:boolean;onToggle:()=>void;onDrop:(id:string)=>void;children:ReactNode}){return <section className="work-group" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData("text/work-id");if(id)onDrop(id)}}><button className="work-group-title" onClick={onToggle}><Icon name="chevron" size={11}/><strong>{label}</strong>{badge&&<span>{badge}</span>}</button>{!closed&&<div>{children}</div>}</section>}
function PageHeader({scene,actions}:{scene:Scene;actions?:ReactNode}){return <header className="page-header"><div><span>{scene.eyebrow}</span><h1>{scene.title}</h1><p>{scene.summary}</p></div>{actions}</header>}

function HomeView({scene,pack,onMove,onWork}:{scene:Scene;pack:ScenarioPack;onMove:(t:Transition)=>void;onWork:()=>void}){return <div className="page-view home-view"><PageHeader scene={scene}/><div className="home-focus"><section className="welcome-card"><span className="workspace-kicker">{scene.phase==="PRE_WORK"?"从一次自然表达开始":"Watt 持续照看的 Reality"}</span><h2>{scene.phase==="PRE_WORK"?"把想法告诉 Watt，当前情况会逐渐变得清楚。":scene.workName??"Watt 运营后台"}</h2><p>{scene.workOutcome??"不必先配置项目、队列或代码库。当前交流会在这里发生，稳定事实会留在 Work。"}</p>{scene.changedSince&&<ul>{scene.changedSince.map(x=><li key={x}><Icon name="check" size={13}/>{x}</li>)}</ul>}<button className="primary-button" onClick={scene.transitions[0]?()=>onMove(scene.transitions[0]):onWork}>{scene.phase==="PRE_WORK"?"开始一次模拟交流":"进入当前 Work"}<Icon name="arrow" size={14}/></button></section>{scene.attention&&<AttentionBlock scene={scene} onMove={onMove}/>}</div><div className="page-foot">{pack.id} · {pack.reviewReason}</div></div>}
function useSurfaceMorph(container: React.RefObject<HTMLDivElement | null>, layoutKey: string, reducedMotion: boolean){
  const settledRects=useRef(new Map<string,DOMRect>());
  useLayoutEffect(()=>{
    const panels=Array.from(container.current?.querySelectorAll<HTMLElement>("[data-surface-id]")??[]);
    panels.forEach(panel=>{
      const id=panel.dataset.surfaceId!;
      const running=panel.getAnimations();
      const visual=running.length?panel.getBoundingClientRect():settledRects.current.get(id);
      running.forEach(animation=>animation.cancel());
      const target=panel.getBoundingClientRect();
      if(!reducedMotion&&visual&&target.width&&target.height){
        const dx=visual.left-target.left,dy=visual.top-target.top,sx=visual.width/target.width,sy=visual.height/target.height;
        if(Math.abs(dx)+Math.abs(dy)+Math.abs(1-sx)+Math.abs(1-sy)>.01)panel.animate([{transformOrigin:"top left",transform:`translate(${dx}px, ${dy}px) scale(${sx}, ${sy})`},{transformOrigin:"top left",transform:"none"}],{duration:360,easing:"cubic-bezier(.2,.72,.2,1)",fill:"both"});
      }
      settledRects.current.set(id,target);
    });
  },[container,layoutKey,reducedMotion]);
}
function AdaptiveWorkView({scene,pack,projection,realityNote,onFocus,onMove,onPreview,onEvidence,onProduction}:{scene:Scene;pack:ScenarioPack;projection:ReturnType<typeof projectWorkspace>;realityNote:string;onFocus:(x:WorkspaceFunction|null)=>void;onMove:(t:Transition)=>void;onPreview:()=>void;onEvidence:()=>void;onProduction:()=>void}){const content:Record<WorkspaceFunction,ReactNode>={reality:<RealityContent scene={scene} note={realityNote} onPreview={onPreview}/>,agenda:<AgendaContent scene={scene} onMove={onMove}/>,production:<ProductionContent scene={scene} onOpen={onProduction}/>,actions:<ActionsContent scene={scene} onMove={onMove} onPreview={onPreview}/>},mode=workspaceMode(projection.focused),placements=workspacePlacements(projection.visible,projection.focused),workspaceRef=useRef<HTMLDivElement>(null),reducedMotion=matchMedia("(prefers-reduced-motion: reduce)").matches;useSurfaceMorph(workspaceRef,`${mode}:${projection.visible.join("|")}`,reducedMotion);return <div className={`page-view work-view ${projection.focused?"focus-active":""}`}><PageHeader scene={scene} actions={<div className="header-actions"><span className={`phase-pill ${scene.tone}`}><i/>{phase[scene.phase]}</span><button className="quiet-button" onClick={onEvidence}><Icon name="shield" size={14}/>事实来源</button></div>}/><div className="outcome-line"><span>当前结果目标</span><strong>{scene.workOutcome??scene.summary}</strong></div><div className="adaptive-workspace" ref={workspaceRef} data-workspace-mode={mode} data-visible-count={projection.visible.length}>{projection.visible.map(name=>{const placement=placements[name]!;return <WorkspacePanel key={name} name={name} focused={projection.focused===name} compact={placement.compact} emphasized={!projection.focused&&projection.emphasized===name} important={name==="actions"&&scene.attention?.contract==="decision"} summary={workspaceSummary(scene,name)} placement={placement} onFocus={()=>onFocus(projection.focused===name?null:name)}>{content[name]}</WorkspacePanel>})}</div><div className="page-foot">Prototype v2.1 · {pack.id}/{scene.id} · 同一工作空间在概览与聚焦间连续重组</div></div>}
function WorkspacePanel({name,focused,compact,emphasized,important,summary,placement,onFocus,children}:{name:WorkspaceFunction;focused:boolean;compact:boolean;emphasized:boolean;important:boolean;summary:string;placement:{gridColumn:string;gridRow:number;dominant:boolean};onFocus:()=>void;children:ReactNode}){return <section data-surface-id={WORKSPACE_SURFACE_IDS[name]} style={{gridColumn:placement.gridColumn,gridRow:placement.gridRow}} className={`workspace-panel panel-${name} ${focused?"focused":""} ${compact?"compact":""} ${placement.dominant?"dominant":""} ${emphasized?"emphasized":""}`}><header><div><span className="panel-icon"><Icon name={name==="reality"?"shield":name==="agenda"?"layers":name==="production"?"play":"spark"} size={14}/></span><strong>{WORKSPACE_LABELS[name]}</strong>{important&&<em aria-label="一项决定等待处理">1</em>}</div><button onClick={onFocus} aria-label={`${focused?"返回概览":"聚焦"}${WORKSPACE_LABELS[name]}`} aria-pressed={focused}><Icon name={focused?"close":"focus"} size={13}/>{focused?"返回概览":"聚焦"}</button></header><button className="compact-summary" onClick={onFocus} tabIndex={compact?0:-1} aria-hidden={!compact}><span>{summary}</span><span>{important?"需要你的决定":"切换到这里"}<Icon name="chevron" size={13}/></span></button><div className="panel-body" aria-hidden={compact} inert={compact}>{children}</div></section>}

function RealityContent({scene,note,onPreview}:{scene:Scene;note:string;onPreview:()=>void}){return <div className="reality-content">{note&&<div className="reality-change"><span>刚刚更新</span><strong>{note}</strong><p>当前交流归入历史后，这项事实仍会保留。</p></div>}<div className="reality-summary"><span>现在可以确定</span><h2>{scene.workName??scene.title}</h2><p>{scene.summary}</p></div>{scene.understanding&&<><FactList title="已确认范围" items={scene.understanding.scope}/><FactList title="重要约束" items={scene.understanding.constraints}/></>}{scene.assets&&<div className="asset-grid">{scene.assets.map(a=><div key={a.name}><Icon name="asset" size={14}/><span><strong>{a.name}</strong><small>{a.role} · {a.state}</small></span></div>)}</div>}{scene.result&&<div className="result-inline"><MockPreview variant={scene.result.previewVariant??"dashboard"}/><div><span>当前结果</span><strong>{scene.result.title}</strong><p>{scene.result.summary}</p><button onClick={onPreview}>打开完整预览</button></div></div>}{scene.deliveries&&<TrustLines deliveries={scene.deliveries}/>}</div>}
function AgendaContent({scene,onMove}:{scene:Scene;onMove:(t:Transition)=>void}){return <div className="agenda-content">{scene.recommendation&&<div className="recommendation"><span><Icon name="spark" size={13}/>Watt 的建议</span><h2>{scene.recommendation.title}</h2><p>{scene.recommendation.body}</p><aside><strong>判断依据</strong>{scene.recommendation.rationale}</aside></div>}{scene.milestones&&<Milestones items={scene.milestones}/>} {!scene.recommendation&&!scene.milestones&&scene.understanding&&<FactList title="形成 Work 前还可以修正" items={[scene.understanding.deliverable,scene.understanding.boundary]}/>}<SceneActions transitions={scene.transitions.filter(t=>t.label!==scene.attention?.action)} onMove={onMove}/></div>}
function ProductionContent({scene,onOpen}:{scene:Scene;onOpen?:()=>void}){if(!scene.production)return <div className="empty-function"><Icon name="pause"/><strong>当前没有生产活动</strong><p>只有事实支持时，生产信息才会出现在主工作区。</p></div>;return <div className="production-content"><div className="production-now"><span className="production-pulse"><i/><i/><i/></span><div><small>{scene.production.label}</small><strong>{scene.production.activity}</strong><p>{scene.production.reason??"Watt 正在按当前目标继续。"}</p></div></div>{scene.production.queueDetail&&<FactList title="更多上下文" items={scene.production.queueDetail}/>} {scene.milestones&&<Milestones items={scene.milestones}/>} {onOpen&&<button className="text-button" onClick={onOpen}>查看生产与恢复详情<Icon name="chevron" size={13}/></button>}</div>}
function ActionsContent({scene,onMove,onPreview}:{scene:Scene;onMove:(t:Transition)=>void;onPreview:()=>void}){return <div className="actions-content">{scene.attention&&<AttentionBlock scene={scene} onMove={onMove}/>} {scene.result&&<div className="result-action"><span>审阅后再决定</span><strong>{scene.result.title}</strong><p>{scene.result.checks.join(" · ")}</p><button onClick={onPreview}>体验精确结果<Icon name="play" size={13}/></button></div>}</div>}
function AttentionBlock({scene,onMove}:{scene:Scene;onMove:(t:Transition)=>void}){const a=scene.attention!,t=scene.transitions.find(x=>x.label===a.action)??scene.transitions[0];return <div className={`attention-block ${a.contract}`}><span>{a.contract==="decision"?"需要你的决定":a.contract==="handling"?"Watt 正在处理":"值得知道"}</span><h2>{a.title}</h2><p>{a.body}</p>{a.consequence&&<aside><strong>接下来</strong>{a.consequence}</aside>}{a.action&&t&&<button onClick={()=>onMove(t)}>{a.action}<Icon name="arrow" size={13}/></button>}</div>}

function DeliveryView({scene,onMove,onWork}:{scene:Scene;onMove:(t:Transition)=>void;onWork:()=>void}){const ds=scene.deliveries??[{title:"Watt 运营工作台",form:"Web 应用",detail:"最近交付 · 模拟数据",action:"打开交付",trust:"检查通过 · 已授权",runtimeState:"aligned" as const}],primary=scene.transitions[0];return <div className="page-view delivery-view"><PageHeader scene={{...scene,eyebrow:"按 Work 查看可用成果",title:scene.workName??scene.title,summary:scene.workOutcome??scene.summary}} actions={<button className="quiet-button" onClick={onWork}><Icon name="work" size={14}/>返回 Work</button>}/><section className="delivery-work"><header><div><span>Work 的交付</span><h2>{scene.workName??"Watt 运营后台"}</h2></div><span className="delivery-revision">最新修订 · v2</span></header><article><span>最新交付</span>{ds.map(d=><div className="delivery-item" key={d.title}><span className="delivery-type"><Icon name="delivery"/></span><div><strong>{d.title}</strong><p>{d.form} · {d.detail}</p><em className={d.runtimeState==="different"?"warning":""}>{d.trust}</em></div><button onClick={()=>primary?onMove(primary):onWork()}>{d.action}<Icon name="arrow" size={13}/></button></div>)}</article><details><summary>历史交付修订</summary><div className="historical-delivery">v1 · 保留当时的结果、检查与运行关系</div></details></section>{scene.attention&&<AttentionBlock scene={scene} onMove={onMove}/>}<SceneActions transitions={scene.transitions.filter(t=>t.label!==scene.attention?.action)} onMove={onMove}/></div>}

function ConversationHistory({value,collapsed,composerExpanded,onToggle,onExpandComposer,onSend}:{value:CurrentInteraction;collapsed:boolean;composerExpanded:boolean;onToggle:()=>void;onExpandComposer:()=>void;onSend:(x:string)=>void}){if(collapsed)return <aside className="conversation-history collapsed"><button onClick={onToggle} aria-label="展开对话历史"><Icon name="message"/><span>{value.history.length}</span></button></aside>;return <aside className={`conversation-history ${value.phase==="archived"?"fresh-history":""}`}><header><div><span>Conversation</span><strong>对话历史</strong></div><button onClick={onToggle} aria-label="收起对话历史"><Icon name="chevron"/></button></header><div className="history-list">{value.history.length?value.history.map((m,i)=><div className={`history-message ${m.actor}`} key={`${i}-${m.text}`}><span>{m.actor==="human"?"你":"Watt"}</span><p>{m.text}</p></div>):<div className="history-empty"><Icon name="message"/><p>当前交流完成后，会在这里留下可追溯的对话历史。</p></div>}</div>{composerExpanded?<button className="composer-return" onClick={onExpandComposer}><Icon name="arrow" size={13}/>输入区正在 Work 下方展开</button>:<Composer compact onSend={onSend} onExpand={onExpandComposer}/>}</aside>}
function CurrentInteractionSurface({value,archiving,reducedMotion,onProtect,onExpand}:{value:CurrentInteraction;archiving:boolean;reducedMotion:boolean;onProtect:(x:boolean)=>void;onExpand:()=>void}){if(!value.humanTurn&&value.phase!=="archived")return <div className="current-interaction idle"><span><Icon name="spark" size={13}/>当前交流会在这里出现</span><p>语言会归入历史，形成的事实会留在上方 Work。</p></div>;if(value.phase==="archived")return <div className="current-interaction archived"><Icon name="check" size={13}/>刚才的交流已归入右侧历史；Work Reality 保持更新。</div>;return <section className={`current-interaction active phase-${value.phase} ${archiving?"archiving":""} ${transitionMotion(reducedMotion)}`} onMouseEnter={()=>onProtect(true)} onMouseLeave={()=>onProtect(false)} onFocus={()=>onProtect(true)} onBlur={()=>onProtect(false)} onMouseUp={()=>{if(getSelection()?.toString())onProtect(true)}} tabIndex={0}><header><div><span className="watt-presence"><Icon name="spark" size={13}/></span><span><small>Watt · 当前回应</small><strong>{value.phase==="received"?"已收到，正在理解影响":value.phase==="streaming"?"正在结合 Work Reality 回应":"回应完成 · 为你保留阅读时间"}</strong></span></div><button onClick={onExpand}>{value.expanded?"恢复":"展开阅读"}</button></header><div className={`live-reply ${value.expanded?"expanded":""}`}>{value.visibleReply||<span className="thinking"><i/><i/><i/></span>}</div>{value.realityEffect&&<div className="mediation-line"><span>对 Work 的影响</span>{value.phase==="complete"?value.realityEffect:"正在确认何时生效"}</div>}<div className="submitted-turn"><span>你刚刚说</span><p>{value.humanTurn}</p></div></section>}
function Composer({compact=false,expanded=false,onSend,onExpand,onCollapse}:{compact?:boolean;expanded?:boolean;onSend:(x:string)=>void;onExpand?:()=>void;onCollapse?:()=>void}){const[text,setText]=useState("");const submit=(e:FormEvent)=>{e.preventDefault();if(!text.trim())return;onSend(text.trim());setText("")};return <form className={`v2-composer ${compact?"compact":""} ${expanded?"expanded":""}`} onSubmit={submit}><textarea aria-label="给 Watt 发消息" rows={expanded?3:2} value={text} onChange={e=>setText(e.target.value)} onFocus={()=>compact&&onExpand?.()} placeholder="补充、纠正，或直接问 Watt…"/><div><span>{expanded?"当前 Work Reality 就在上方":"输入时可在 Work 下方展开"}</span>{expanded&&onCollapse&&<button type="button" onClick={onCollapse}>收回</button>}<button type="submit" disabled={!text.trim()} aria-label="发送消息"><Icon name="arrow" size={14}/></button></div></form>}

function FactList({title,items}:{title:string;items:string[]}){return <div className="fact-list"><span>{title}</span>{items.map(x=><p key={x}><Icon name="check" size={12}/>{x}</p>)}</div>}
function Milestones({items}:{items:Milestone[]}){return <div className="v2-milestones">{items.map((x,i)=><div className={x.state} key={x.label}><span>{x.state==="done"?<Icon name="check" size={11}/>:i+1}</span><p><strong>{x.label}</strong><small>{x.detail}</small></p><em>{x.state==="done"?"已完成":x.state==="current"?"当前":x.state==="blocked"?"等待决定":"随后"}</em></div>)}</div>}
function SceneActions({transitions,onMove}:{transitions:Transition[];onMove:(t:Transition)=>void}){if(!transitions.length)return <div className="path-end"><Icon name="check" size={13}/>当前模拟路径已走完，可从 Reviewer Mode 重置或换场景。</div>;return <div className="scene-actions">{transitions.map(t=><button key={`${t.label}-${t.to}`} className={t.kind??"primary"} onClick={()=>onMove(t)}>{t.label}<Icon name="arrow" size={13}/></button>)}</div>}
function TrustLines({deliveries}:{deliveries:NonNullable<Scene["deliveries"]>}){return <div className="trust-lines">{deliveries.map(d=><p className={d.runtimeState==="different"?"warning":""} key={d.title}><Icon name={d.runtimeState==="different"?"info":"shield"} size={13}/><span><strong>{d.title}</strong><small>{d.trust}</small></span></p>)}</div>}
function MockPreview({variant}:{variant:NonNullable<ResultFact["previewVariant"]>}){return <div className={`mock-preview ${variant}`}><header><i/><i/><i/><span>运营工作台</span></header><div><aside><b/><i/><i/><i/></aside><main><strong>今天值得关注</strong><div className="mock-stats"><i/><i/><i/></div><div className="mock-chart"><i/><i/><i/><i/><i/></div><p/><p/></main></div></div>}
function PreviewOverlay({result,onClose}:{result:ResultFact;onClose:()=>void}){return <div className="preview-overlay"><header><div><span/><strong>隔离结果预览</strong><em>模拟数据 · 不影响真实环境</em></div><button onClick={onClose} aria-label="关闭结果预览"><Icon name="close"/></button></header><div className="preview-stage"><div className="preview-canvas"><MockPreview variant={result.previewVariant??"dashboard"}/></div><aside><span>正在预览</span><h2>{result.title}</h2><p>{result.summary}</p><FactList title="关键变化" items={result.highlights}/><FactList title="检查通过" items={result.checks}/>{result.limitations&&<FactList title="已知限制" items={result.limitations}/>}<button className="primary-button" onClick={onClose}>返回 Work 审阅</button></aside></div></div>}
function InfoDrawer({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="drawer-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside><header><div><span>渐进详情</span><h2>{title}</h2></div><button onClick={onClose} aria-label={`关闭${title}`}><Icon name="close"/></button></header><div className="drawer-content">{children}</div></aside></div>}

function ReviewerPanel({pack,scene,projection,focus,interaction,selectedWork,onClose,onPack,onScene,onReset,onAdvance}:{pack:ScenarioPack;scene:Scene;projection:ReturnType<typeof projectWorkspace>;focus:WorkspaceFunction|null;interaction:CurrentInteraction;selectedWork:WorkNavItem;onClose:()=>void;onPack:(p:ScenarioPack)=>void;onScene:(s:Scene)=>void;onReset:()=>void;onAdvance:()=>void}){const key=`watt-prototype-v2-note:${pack.id}:${scene.id}`,[note,setNote]=useState(()=>localStorage.getItem(key)??"");useEffect(()=>setNote(localStorage.getItem(key)??""),[key]);return <div className="reviewer-overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><aside className="reviewer-panel"><header><div><span>独立评审工具</span><h2>Prototype v2.1 Reviewer</h2></div><button onClick={onClose} aria-label="关闭体验评审模式"><Icon name="close"/></button></header><div className="reviewer-content"><label>场景包<select value={pack.id} onChange={e=>onPack(getPack(e.target.value))}>{scenarioPacks.map(p=><option value={p.id} key={p.id}>{p.id} · {p.shortTitle}</option>)}</select></label><p className="reviewer-summary"><strong>{pack.title}</strong>{pack.reviewReason}</p><label>当前场景<select value={scene.id} onChange={e=>onScene(getScene(pack,e.target.value))}>{pack.scenes.map((s,i)=><option value={s.id} key={s.id}>{i+1}. {s.label}</option>)}</select></label><div className="reviewer-controls"><button onClick={onReset}><Icon name="refresh" size={13}/>重置</button><button onClick={onAdvance} disabled={!scene.transitions.length}><Icon name="play" size={13}/>推进模拟</button></div><div className="reviewer-facts"><p><span>工作空间模式</span>{workspaceMode(projection.focused)}</p><p><span>可见表面</span>{projection.visible.map(x=>`${WORKSPACE_SURFACE_IDS[x]} ${WORKSPACE_LABELS[x]}`).join(" · ")}</p><p><span>聚焦表面</span>{focus?`${WORKSPACE_SURFACE_IDS[focus]} ${WORKSPACE_LABELS[focus]}`:"无 · 全局概览"}</p><p><span>当前交流</span>{interaction.phase}</p><p><span>Work 分组</span>{selectedWork.groupLabel} · {selectedWork.groupSource==="human"?"Human-defined":"AI-assigned"}</p><p><span>Scenario / Tension</span>{[...scene.scenarioIds,...scene.tensionIds].join(" · ")||"—"}</p><p><span>验收重点</span>{scene.acceptanceFocus}</p><p><span>设计记录</span>Core Workspace §19 · Adaptive Workspace Morphing</p></div><label>本地评审笔记<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="记录注意力、理解或交互问题…"/></label><button className="save-note" onClick={()=>localStorage.setItem(key,note)}>保存在此浏览器</button><p className="reviewer-boundary">仅模拟数据；记录不会写入产品或生产系统。</p></div></aside></div>}
