const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('src/spg/web/admin.js','utf8');
function surface(route='/admin',authorization=true){
 const nodes={'#admin-content':{innerHTML:''},'#admin-notice':{textContent:'',hidden:true}};const listeners={};const calls=[];
 const worker={name:'cloud-worker-1',status:'READY',capacity:{max_concurrency:1},active_execution_count:0,available_slots:1};
 const overview={watt_revision:'d'.repeat(40),quality:{campaigns:[],runs:[],cases:[],clusters:[]},assurance:{mode:'REQUIRED',store_observed:true,results:[],quality_evaluations:[]},operations:{state:'CURRENT',node:{node_id:'i-exact',hostname:'host',region:'cn-wulanchabu',observed_at:new Date().toISOString(),cpu_percent:5,cpu_count:4,memory:{used_bytes:1000,total_bytes:2000},disk:{used_bytes:1000,total_bytes:10000,free_bytes:9000},network:{eth0:{rx_bytes:100,tx_bytes:200}},uptime_seconds:3600},production:{workers:[worker],queue:[],queue_depth:0,active_executions:0,available_slots:1},services:[{service:'api',state:'running',health:'healthy',node_id:'i-exact'}],storage:{docker:{categories:[]},note:'scopes'},topology:{nodes:[{id:'i-exact',hostname:'host',region:'cn-wulanchabu'}],service_placements:[{service:'api',health:'healthy',node_id:'i-exact'}]}}};
 const context={document:{querySelector:s=>nodes[s],querySelectorAll:()=>[],addEventListener:(k,f)=>listeners[k]=f},window:{addEventListener(){}},location:{pathname:route},history:{pushState(){}},setTimeout(){},console,HTMLFormElement:class {},FormData:class {},async fetch(url,opts){calls.push([url,opts]);const data=url==='/api/admin/overview'?overview:url==='/api/admin/arena'?{experiments:[],preferences:[],learning_signals:[],promotion_decisions:[]}:url==='/api/admin/operations/history'?[]:{};return{ok:authorization,status:authorization?200:401,json:async()=>data};}};
 vm.runInNewContext(source,context);return{nodes,listeners,calls,overview,ready:()=>new Promise(r=>setImmediate(r))};
}
test('Admin uses existing authenticated session and dedicated navigation',async()=>{const s=surface();await s.ready();assert.equal(s.calls[0][0],'/auth/session');assert.match(s.nodes['#admin-content'].innerHTML,/总览|概览/);assert.doesNotMatch(s.nodes['#admin-content'].innerHTML,/data-quadrant/);});
test('Unauthenticated Admin does not load owner data',async()=>{const s=surface('/admin',false);await s.ready();assert.match(s.nodes['#admin-content'].innerHTML,/登录 Watt Admin/);assert.equal(s.calls.length,1);});
test('Quality offers sealed holdout and separates canonical cohorts',async()=>{const s=surface('/admin/quality');await s.ready();assert.match(s.nodes['#admin-content'].innerHTML,/生成封存未见场景/);assert.match(s.nodes['#admin-content'].innerHTML,/同一个 Case 身份/);});
test('Operations preserves actual finite Worker capacity',async()=>{const s=surface('/admin/operations');await s.ready();assert.match(s.nodes['#admin-content'].innerHTML,/cloud-worker-1/);assert.match(s.nodes['#admin-content'].innerHTML,/可接任务/);assert.match(s.nodes['#admin-content'].innerHTML,/等待与执行队列/);assert.doesNotMatch(s.nodes['#admin-content'].innerHTML,/提高并发/);});
test('Infrastructure renders exact node placement and unknown health separately',async()=>{const s=surface('/admin/infrastructure');await s.ready();const html=s.nodes['#admin-content'].innerHTML;assert.match(html,/i-exact/);assert.match(html,/cn-wulanchabu/);assert.match(html,/CPU/);assert.match(html,/网络观测/);assert.match(html,/需连续采样/);assert.match(html,/服务健康/);});
test('Assurance explicitly needs independent oracle',async()=>{const s=surface('/admin/assurance');await s.ready();assert.match(s.nodes['#admin-content'].innerHTML,/独立确定性判据/);assert.match(s.nodes['#admin-content'].innerHTML,/独立质量评价/);});
test('Arena differences and approval require explicit Human submission',async()=>{const s=surface('/admin/arena');await s.ready();assert.match(s.nodes['#admin-content'].innerHTML,/版本化实验/);assert.match(source,/data-promotion-form/);assert.match(source,/rationale:data.get\('rationale'\)/);assert.doesNotMatch(source,/rationale:'Human 在 Admin/);});
