const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync('src/spg/web/admin.js','utf8');
function surface(route='/admin',authorization=true,run=null,trace=null){
 const nodes={'#admin-content':{innerHTML:''},'#admin-notice':{textContent:'',hidden:true}};const listeners={};const calls=[];
 const worker={name:'cloud-worker-1',status:'READY',capacity:{max_concurrency:1},active_execution_count:0,available_slots:1};
 const overview={watt_revision:'d'.repeat(40),quality:{campaigns:[],runs:[],cases:[],clusters:[]},assurance:{mode:'REQUIRED',store_observed:true,results:[],quality_evaluations:[]},operations:{state:'CURRENT',node:{node_id:'i-exact',hostname:'host',region:'cn-wulanchabu',observed_at:new Date().toISOString(),cpu_percent:5,cpu_count:4,memory:{used_bytes:1000,total_bytes:2000},disk:{used_bytes:1000,total_bytes:10000,free_bytes:9000},network:{eth0:{rx_bytes:100,tx_bytes:200}},uptime_seconds:3600},production:{workers:[worker],queue:[],queue_depth:0,active_executions:0,available_slots:1},services:[{service:'api',state:'running',health:'healthy',node_id:'i-exact'}],storage:{docker:{categories:[]},note:'scopes'},topology:{nodes:[{id:'i-exact',hostname:'host',region:'cn-wulanchabu'}],service_placements:[{service:'api',health:'healthy',node_id:'i-exact'}]}}};
 const context={URLSearchParams,document:{querySelector:s=>nodes[s],querySelectorAll:()=>[],addEventListener:(k,f)=>listeners[k]=f},window:{addEventListener(){}},location:{pathname:route,search:trace?'?case=historical-case':run?'?run='+run.id:''},history:{pushState(){}},setTimeout(){},console,HTMLFormElement:class {},FormData:class {},async fetch(url,opts){calls.push([url,opts]);const data=trace && url.includes('/trace')?trace:run && url.startsWith('/api/admin/runs/') ? run : url==='/api/admin/overview'?overview:url==='/api/admin/arena'?{experiments:[],preferences:[],learning_signals:[],promotion_decisions:[]}:url==='/api/admin/operations/history'?[]:{};return{ok:authorization,status:authorization?200:401,json:async()=>data};}};
 vm.runInNewContext(source,context);return{nodes,listeners,calls,overview,ready:()=>new Promise(r=>setImmediate(r))};
}
test('Admin uses existing authenticated session and dedicated navigation',async()=>{const s=surface();await s.ready();assert.equal(s.calls[0][0],'/auth/session');assert.match(s.nodes['#admin-content'].innerHTML,/总览|概览/);assert.doesNotMatch(s.nodes['#admin-content'].innerHTML,/data-quadrant/);});
test('Unauthenticated Admin does not load owner data',async()=>{const s=surface('/admin',false);await s.ready();assert.match(s.nodes['#admin-content'].innerHTML,/登录 Watt Admin/);assert.equal(s.calls.length,1);});
test('Quality offers sealed holdout and separates canonical cohorts',async()=>{const s=surface('/admin/quality');await s.ready();assert.match(s.nodes['#admin-content'].innerHTML,/生成封存未见场景/);assert.match(s.nodes['#admin-content'].innerHTML,/同一个 Case 身份/);});
test('Operations preserves actual finite Worker capacity',async()=>{const s=surface('/admin/operations');await s.ready();assert.match(s.nodes['#admin-content'].innerHTML,/cloud-worker-1/);assert.match(s.nodes['#admin-content'].innerHTML,/可接任务/);assert.match(s.nodes['#admin-content'].innerHTML,/等待与执行队列/);assert.doesNotMatch(s.nodes['#admin-content'].innerHTML,/提高并发/);});
test('Infrastructure renders exact node placement and unknown health separately',async()=>{const s=surface('/admin/infrastructure');await s.ready();const html=s.nodes['#admin-content'].innerHTML;assert.match(html,/i-exact/);assert.match(html,/cn-wulanchabu/);assert.match(html,/CPU/);assert.match(html,/网络观测/);assert.match(html,/需连续采样/);assert.match(html,/服务健康/);});
test('Assurance explicitly needs independent oracle',async()=>{const s=surface('/admin/assurance');await s.ready();assert.match(s.nodes['#admin-content'].innerHTML,/独立确定性判据/);assert.match(s.nodes['#admin-content'].innerHTML,/独立质量评价/);});
test('Arena differences and approval require explicit Human submission',async()=>{const s=surface('/admin/arena');await s.ready();assert.match(s.nodes['#admin-content'].innerHTML,/版本化实验/);assert.match(source,/data-promotion-form/);assert.match(source,/rationale:data.get\('rationale'\)/);assert.doesNotMatch(source,/rationale:'Human 在 Admin/);});

test('Campaign page restores persisted Run and exposes safe controls and truthful queued case',async()=>{const run={id:'run-1',state:'PAUSED',lifecycle:'PAUSED',watt_revision:'d'.repeat(40),created_at:new Date().toISOString(),cases:[],controls:[],progress:{total:10,QUEUED:9,RUNNING:0,completed:1,PASS:1,FAIL:0,BLOCKED:0,UNKNOWN:0,NOT_RUN:0},members:[{case_version_id:'v-1',version:1,title:'queued scenario',cohorts:['GOLDEN'],state:'QUEUED',definition:{motive:'repo change',context:{},invariants:['exact']},attempt:null}],operations_samples:[],fresh_holdout:[]};const s=surface('/admin/quality',true,run);await s.ready();await s.ready();const h=s.nodes['#admin-content'].innerHTML;assert.match(h,/本轮验证/);assert.match(h,/run-1/);assert.match(h,/<details class="admin-evidence"><summary>查看证据与血缘/);assert.match(h,/继续本次运行/);assert.match(h,/等待执行/);assert.match(h,/跳过排队场景/);assert.match(h,/重跑所选场景/);assert.doesNotMatch(h,/添加独立模型意见/);assert.match(h,/安全边界/);});
test('Completed run offers new immutable reruns and seals Holdout answers',async()=>{const run={id:'run-2',state:'FAIL',lifecycle:'COMPLETED',watt_revision:'d'.repeat(40),created_at:new Date().toISOString(),cases:[],controls:[],progress:{total:1,completed:1,FAIL:1},members:[{case_version_id:'v-1',version:1,title:'sealed scenario',cohorts:['FRESH_HOLDOUT'],state:'FAIL',definition:{sealed:true},attempt:{id:'a-1',state:'FAIL',lineage:{sealed:true},evaluations:[{evaluator:'DETERMINISTIC',outcome:'FAIL'}]}}]};const s=surface('/admin/quality',true,run);await s.ready();await s.ready();const h=s.nodes['#admin-content'].innerHTML;assert.match(h,/重跑此失败场景/);assert.match(h,/重跑全部场景/);assert.match(h,/封存/);assert.doesNotMatch(h,/添加独立模型意见/);assert.match(h,/完成/);});

function traceFixture(){return{scene:'工律官网首次生产',purpose:'受治理官网请求推进到候选',first_human_input:'我要开发一个工律的官网',basis:{mode:'HISTORICAL_QUALIFICATION',at:'2026-10-07T01:00:00Z'},conversation:[{actor:'HUMAN',text:'我要开发一个工律的官网',timestamp:'2026-10-07T01:00:00Z'},{actor:'WATT',text:'已形成 Work，进入受治理生产。',timestamp:'2026-10-07T01:00:01Z'}],semantic:[],contexts:[{contract_id:'MANAGED_GREENFIELD_PRODUCTION',protected_obligations:[{context_class:'PRODUCT_INTENT',content:JSON.stringify({desired_outcome:'工律官网'})}]}],steering:[],plan_history:[],units:[],queue:[],search:[],search_note:'本 Case 未使用外部搜索。',model_calls:[],tool_calls:[],verification:[],guardian:[{gate:'PASS'}],candidate:[{id:'exact-candidate',fingerprint:'exact-fingerprint'}],governance:[],artifacts:[{path:'index.html',change:'CREATE'}],recovery:[],deployment:[],deployment_note:'本 Case 未执行部署；资格范围止于 Candidate。',diagnosis:{quality_label:'场景符合预期',production_result:'候选已封存，尚需 Human 授权或验收',production_label:'生产结果需查看实际 owner 证据',divergence_label:'尚未观测到可归因偏离',stability:'没有已保存的自修复记录',safety:'存在独立保护证据'},diagnostic_owners:[{owner:'ECF',events:[]},{owner:'GUARDIAN',events:[]}],source_references:['immutable-owner'],advanced:{owners:{}},missing_note:'未采集不会显示为0'};}
test('Historical Trace opens story with exact input, readable context and truthful non-deployment',async()=>{const s=surface('/admin/trace',true,null,traceFixture());await s.ready();await s.ready();const h=s.nodes['#admin-content'].innerHTML;assert.match(h,/我要开发一个工律的官网/);assert.match(h,/和 Watt 的完整交流/);assert.match(h,/工律官网/);assert.match(h,/不会用当前产品状态补写历史/);assert.match(h,/未执行部署/);assert.match(h,/尚未采集 Human 接受事件/);assert.match(h,/高级工程证据/);assert.match(h,/故事视图/);assert.match(h,/诊断视图/);assert.doesNotMatch(h,/已自动验收/);});
test('Story and diagnostic toggles use the same facts without new owner calls',async()=>{const s=surface('/admin/trace',true,null,traceFixture());await s.ready();await s.ready();const n=s.calls.length;await s.listeners.click({target:{closest:()=>({dataset:{traceMode:'diagnostic'}})}});assert.match(s.nodes['#admin-content'].innerHTML,/最早可证明的偏离/);assert.match(s.nodes['#admin-content'].innerHTML,/独立保证/);assert.equal(s.calls.length,n);});
test('Trace escapes Human prose and preserves missing-data statements',async()=>{const t=traceFixture();t.first_human_input='<script>steal()</script>';const s=surface('/admin/trace',true,null,t);await s.ready();await s.ready();const h=s.nodes['#admin-content'].innerHTML;assert.match(h,/&lt;script&gt;/);assert.doesNotMatch(h,/<script>steal/);assert.match(h,/未采集模型调用/);});
test('Operations exposes actual CPU, memory, disk and network on primary page',async()=>{const s=surface('/admin/operations');await s.ready();const h=s.nodes['#admin-content'].innerHTML;for(const word of ['CPU','内存','磁盘','网络','服务器与服务'])assert.ok(h.includes(word));assert.match(h,/5%/);assert.match(h,/需连续采样|不能证明当前资源充足/);});
test('Six primary navigation entries are human-readable and Workspace stays separate',()=>{const h=fs.readFileSync('src/spg/web/admin.html','utf8');for(const word of ['总览','质量','问题','学习与改进','风险与保证','运行与资源'])assert.ok(h.includes(word));assert.doesNotMatch(h,/data-quadrant/);});

test('Trace summary avoids cockpit census and loads execution evidence only on demand',async()=>{const t=traceFixture();t.detail_level='summary';const s=surface('/admin/trace',true,null,t);await s.ready();await s.ready();assert.ok(s.calls.some(([path])=>path.endsWith('/trace?view=summary')));assert.ok(!s.calls.some(([path])=>path==='/api/admin/overview'));assert.match(s.nodes['#admin-content'].innerHTML,/读取执行详情与完整工程证据/);const n=s.calls.length;await s.listeners.click({target:{closest:()=>({dataset:{},matches:()=>false,hasAttribute:k=>k==='data-trace-details'})}});assert.equal(s.calls.length,n+1);assert.ok(s.calls.at(-1)[0].endsWith('/trace'));});
