"""add watt native executor runtime

Revision ID: 20260911_34
Revises: 20260910_33
Create Date: 2026-09-11 16:20:57.463170
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260911_34'
down_revision: str | Sequence[str] | None = '20260910_33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_source_vectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('non_repository_assets', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_source_vectors')),
    sa.UniqueConstraint('digest', name=op.f('uq_execution_source_vectors_digest'))
    )
    op.create_table('executor_scheduler_state',
    sa.Column('scheduler_identity', sa.String(length=128), nullable=False),
    sa.Column('policy_version', sa.String(length=128), nullable=False),
    sa.Column('last_fairness_group', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scheduler_identity', name=op.f('pk_executor_scheduler_state'))
    )
    op.create_table('execution_source_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_vector_id', sa.Uuid(), nullable=False),
    sa.Column('mount_id', sa.String(length=255), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('repository_identity', sa.String(length=1024), nullable=False),
    sa.Column('source_baseline_ref', sa.String(length=255), nullable=False),
    sa.Column('source_commit_oid', sa.String(length=128), nullable=False),
    sa.Column('source_tree_oid', sa.String(length=128), nullable=False),
    sa.Column('git_object_format', sa.String(length=16), nullable=False),
    sa.Column('container_path', sa.String(length=1024), nullable=False),
    sa.Column('read_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('write_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forbidden_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('integration_target', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['source_vector_id'], ['execution_source_vectors.id'], name=op.f('fk_execution_source_members_source_vector_id_execution_source_vectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_source_members')),
    sa.UniqueConstraint('source_vector_id', 'container_path', name='uq_source_members_destination'),
    sa.UniqueConstraint('source_vector_id', 'mount_id', name='uq_source_members_mount')
    )
    op.create_table('execution_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('causation_id', sa.Uuid(), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_execution_events_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_events')),
    sa.UniqueConstraint('pwu_id', 'sequence', name='uq_execution_events_sequence')
    )
    op.create_table('execution_resource_envelopes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.String(length=128), nullable=False),
    sa.Column('provider_profile', sa.String(length=255), nullable=False),
    sa.Column('max_inference_submissions', sa.Integer(), nullable=False),
    sa.Column('max_tool_effects', sa.Integer(), nullable=False),
    sa.Column('max_active_seconds', sa.Integer(), nullable=False),
    sa.Column('max_successor_recoveries', sa.Integer(), nullable=False),
    sa.Column('max_parallel_workers', sa.Integer(), nullable=False),
    sa.Column('max_cost_units', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_active_seconds > 0', name='ck_execution_resource_envelopes_active_time_positive'),
    sa.CheckConstraint('max_inference_submissions > 0', name='ck_execution_resource_envelopes_inference_budget_positive'),
    sa.CheckConstraint('max_parallel_workers > 0', name='ck_execution_resource_envelopes_worker_budget_positive'),
    sa.CheckConstraint('max_successor_recoveries >= 0', name='ck_execution_resource_envelopes_recovery_budget_nonnegative'),
    sa.CheckConstraint('max_tool_effects > 0', name='ck_execution_resource_envelopes_tool_budget_positive'),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_execution_resource_envelopes_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_resource_envelopes'))
    )
    op.create_table('execution_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('parent_checkpoint_id', sa.Uuid(), nullable=True),
    sa.Column('current_checkpoint_id', sa.Uuid(), nullable=True),
    sa.Column('current_working_state_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_execution_sessions_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_sessions'))
    )
    op.create_table('pwu_contract_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('contract_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contract_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_pwu_contract_versions_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pwu_contract_versions')),
    sa.UniqueConstraint('pwu_id', 'contract_digest', name='uq_pwu_contract_versions_digest'),
    sa.UniqueConstraint('pwu_id', 'revision', name='uq_pwu_contract_versions_revision')
    )
    op.create_table('checkpoint_bundles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('step_sequence', sa.Integer(), nullable=False),
    sa.Column('worker_epoch', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('source_vector_digest', sa.String(length=64), nullable=False),
    sa.Column('repository_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('semantic_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('consistency_class', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_checkpoint_bundles_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['execution_sessions.id'], name=op.f('fk_checkpoint_bundles_session_id_execution_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkpoint_bundles'))
    )
    op.create_table('event_outbox',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.String(length=32), server_default='PENDING', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['execution_events.id'], name=op.f('fk_event_outbox_event_id_execution_events')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_event_outbox'))
    )
    op.create_table('execution_control_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('actor_identity', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('expected_control_version', sa.Integer(), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_execution_control_requests_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_control_requests')),
    sa.UniqueConstraint('command_id', name=op.f('uq_execution_control_requests_command_id'))
    )
    op.create_table('execution_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('effect_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('producer_identity', sa.String(length=255), nullable=False),
    sa.Column('subject_digest', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_execution_evidence_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_execution_evidence_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_evidence'))
    )
    op.create_table('execution_recovery_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('basis_checkpoint_id', sa.Uuid(), nullable=True),
    sa.Column('observed_reality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('residual_obligations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effect_uncertainty', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_execution_recovery_cases_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_execution_recovery_cases_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_recovery_cases'))
    )
    op.create_table('execution_resource_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('envelope_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('reservation_key', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('certainty', sa.String(length=32), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_execution_resource_usage_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['envelope_id'], ['execution_resource_envelopes.id'], name=op.f('fk_execution_resource_usage_envelope_id_execution_resource_envelopes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_resource_usage')),
    sa.UniqueConstraint('envelope_id', 'reservation_key', 'resource_type', name='uq_execution_resource_usage_reservation')
    )
    op.create_table('execution_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_digest', sa.String(length=64), nullable=True),
    sa.Column('context_revision', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_execution_steps_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['execution_sessions.id'], name=op.f('fk_execution_steps_session_id_execution_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_steps')),
    sa.UniqueConstraint('session_id', 'sequence', name='uq_execution_steps_sequence')
    )
    op.create_table('execution_workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('source_vector_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('host_storage_id', sa.String(length=255), nullable=False),
    sa.Column('materialization_path', sa.String(length=2048), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest_digest', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_execution_workspaces_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_execution_workspaces_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_vector_id'], ['execution_source_vectors.id'], name=op.f('fk_execution_workspaces_source_vector_id_execution_source_vectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_workspaces')),
    sa.UniqueConstraint('attempt_id', name=op.f('uq_execution_workspaces_attempt_id'))
    )
    op.create_table('executor_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('request_digest', sa.String(length=64), nullable=False),
    sa.Column('actor_identity', sa.String(length=255), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('grant_revision', sa.Integer(), nullable=False),
    sa.Column('fairness_group', sa.String(length=255), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('required_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_provider_profile', sa.String(length=255), nullable=False),
    sa.Column('required_resource_profile', sa.String(length=255), nullable=False),
    sa.Column('wait_reason', sa.Text(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resume_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_executor_queue_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_executor_queue_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executor_queue')),
    sa.UniqueConstraint('command_id', name=op.f('uq_executor_queue_command_id'))
    )
    op.create_index('ix_executor_queue_runnable', 'executor_queue', ['condition', 'available_at', 'enqueued_at'], unique=False)
    op.create_index('uq_executor_queue_active_grant', 'executor_queue', ['attempt_id', 'grant_revision'], unique=True, postgresql_where=sa.text("condition IN ('QUEUED','WAITING_RESOURCE','WAITING_HUMAN','ALLOCATED','EXECUTING','CHECKPOINTED','RETURNED_TO_QUEUE')"))
    op.create_table('native_attempt_states',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('grant_state', sa.String(length=32), nullable=False),
    sa.Column('runtime_mode', sa.String(length=32), nullable=False),
    sa.Column('terminal_outcome', sa.String(length=64), nullable=True),
    sa.Column('control_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('worker_epoch', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_step_sequence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_checkpoint_id', sa.Uuid(), nullable=True),
    sa.Column('blocker_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('effect_uncertainty', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_native_attempt_states_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id', name=op.f('pk_native_attempt_states'))
    )
    op.create_table('execution_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('queue_entry_id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('grant_revision', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('worker_profile', sa.String(length=255), nullable=False),
    sa.Column('provider_profile', sa.String(length=255), nullable=False),
    sa.Column('lease_epoch', sa.Integer(), nullable=False),
    sa.Column('lease_token_digest', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=128), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_execution_allocations_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_execution_allocations_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['executor_queue.id'], name=op.f('fk_execution_allocations_queue_entry_id_executor_queue'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_allocations'))
    )
    op.create_index('uq_execution_allocations_active_attempt', 'execution_allocations', ['attempt_id'], unique=True, postgresql_where=sa.text("condition IN ('ISSUED','ACTIVE')"))
    op.create_table('execution_effects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_index', sa.Integer(), nullable=False),
    sa.Column('tool_identity', sa.String(length=255), nullable=False),
    sa.Column('tool_version', sa.String(length=64), nullable=False),
    sa.Column('semantic_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('semantic_input_digest', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('conflict_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['execution_steps.id'], name=op.f('fk_execution_effects_step_id_execution_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_effects')),
    sa.UniqueConstraint('step_id', 'proposal_index', name='uq_execution_effects_proposal')
    )
    op.create_table('native_attempt_bindings',
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('pwu_contract_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_vector_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('resource_envelope_id', sa.Uuid(), nullable=False),
    sa.Column('binding_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('binding_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_native_attempt_bindings_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pwu_contract_version_id'], ['pwu_contract_versions.id'], name=op.f('fk_native_attempt_bindings_pwu_contract_version_id_pwu_contract_versions')),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_native_attempt_bindings_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_envelope_id'], ['execution_resource_envelopes.id'], name=op.f('fk_native_attempt_bindings_resource_envelope_id_execution_resource_envelopes')),
    sa.ForeignKeyConstraint(['session_id'], ['execution_sessions.id'], name=op.f('fk_native_attempt_bindings_session_id_execution_sessions')),
    sa.ForeignKeyConstraint(['source_vector_id'], ['execution_source_vectors.id'], name=op.f('fk_native_attempt_bindings_source_vector_id_execution_source_vectors')),
    sa.ForeignKeyConstraint(['workspace_id'], ['execution_workspaces.id'], name=op.f('fk_native_attempt_bindings_workspace_id_execution_workspaces')),
    sa.PrimaryKeyConstraint('attempt_id', name=op.f('pk_native_attempt_bindings'))
    )
    op.create_table('result_ready_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pwu_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('checkpoint_bundle_id', sa.Uuid(), nullable=False),
    sa.Column('contract_digest', sa.String(length=64), nullable=False),
    sa.Column('output_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('residual_obligations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claimant_identity', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_result_ready_claims_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checkpoint_bundle_id'], ['checkpoint_bundles.id'], name=op.f('fk_result_ready_claims_checkpoint_bundle_id_checkpoint_bundles')),
    sa.ForeignKeyConstraint(['pwu_id'], ['production_work_units.id'], name=op.f('fk_result_ready_claims_pwu_id_production_work_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_ready_claims'))
    )
    op.create_table('effect_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('effect_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('host_identity', sa.String(length=255), nullable=False),
    sa.Column('host_nonce', sa.String(length=255), nullable=False),
    sa.Column('condition', sa.String(length=32), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['effect_id'], ['execution_effects.id'], name=op.f('fk_effect_receipts_effect_id_execution_effects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_effect_receipts')),
    sa.UniqueConstraint('effect_id', 'delivery_id', name='uq_effect_receipts_delivery')
    )
    op.create_table('executor_leases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['execution_allocations.id'], name=op.f('fk_executor_leases_allocation_id_execution_allocations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.id'], name=op.f('fk_executor_leases_attempt_id_execution_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executor_leases')),
    sa.UniqueConstraint('attempt_id', 'epoch', name='uq_executor_leases_attempt_epoch')
    )
    op.create_index('uq_executor_leases_live_attempt', 'executor_leases', ['attempt_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_executor_leases_live_attempt', table_name='executor_leases', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_table('executor_leases')
    op.drop_table('effect_receipts')
    op.drop_table('result_ready_claims')
    op.drop_table('native_attempt_bindings')
    op.drop_table('execution_effects')
    op.drop_index('uq_execution_allocations_active_attempt', table_name='execution_allocations', postgresql_where=sa.text("condition IN ('ISSUED','ACTIVE')"))
    op.drop_table('execution_allocations')
    op.drop_table('native_attempt_states')
    op.drop_index('uq_executor_queue_active_grant', table_name='executor_queue', postgresql_where=sa.text("condition IN ('QUEUED','WAITING_RESOURCE','WAITING_HUMAN','ALLOCATED','EXECUTING','CHECKPOINTED','RETURNED_TO_QUEUE')"))
    op.drop_index('ix_executor_queue_runnable', table_name='executor_queue')
    op.drop_table('executor_queue')
    op.drop_table('execution_workspaces')
    op.drop_table('execution_steps')
    op.drop_table('execution_resource_usage')
    op.drop_table('execution_recovery_cases')
    op.drop_table('execution_evidence')
    op.drop_table('execution_control_requests')
    op.drop_table('event_outbox')
    op.drop_table('checkpoint_bundles')
    op.drop_table('pwu_contract_versions')
    op.drop_table('execution_sessions')
    op.drop_table('execution_resource_envelopes')
    op.drop_table('execution_events')
    op.drop_table('execution_source_members')
    op.drop_table('executor_scheduler_state')
    op.drop_table('execution_source_vectors')
    # ### end Alembic commands ###
